### ISSUE TITLE
TFT where target history is unknown

### ISSUE THREAD

**Issue by rickdzekman** [jdb78/pytorch-forecasting#1012]
I'm forecasting the probability that a particular event will occur within K time steps. The true value is either 1 or 0. So a sequence may look like this: `[0, 0, 0, 0, 1, 1, 1, 1, 1, 1*]`. The actual event occurs at 1* but at k=6 time steps we want to start predicting the event. But we actually don't know whether the event happens until 1* (and actually much later). So I don't want the target history passed to the network as an input.

What's the best way to do this?

**Comment by rickdzekman** [comment]
Is it the case that the target variable will not be used by the encoder or decoder if it's not assigned as one of the `time_varying_*` variables?

After some digging through the docs/code I _think_ that's the case but I'm not 100% sure.

**Comment by pdurham2** [comment]
@rickdzekman unsure if you still need confirmation, but you are correct. The TFT will not use the target variable for prediction without including it in either `time_varying_known` (used in encoder and decoder) or `time_varying_unknown` (used just in the encoder).

**Comment by rickdzekman** [comment]
> 

Thanks @pdurham2 that does help to know. I dug into it just to make sure but that was not immediately obvious
