### ISSUE TITLE
MQF2 loss Installation Error

### ISSUE THREAD

**Issue by zhaobozb** [jdb78/pytorch-forecasting#1144]
Hi Guys,

I got an error when installing the MQF2 loss following the documentation:
```bash
pip install pytorch-forecasting[mqf2]
```
with the error:
```bash
zsh: no matches found: pytorch-forecasting[mqf2]
```
Does anybody know how to solve this issue? Thanks.

**Comment by wzbitl** [comment]
You have to prefix it with \ or “ to make zsh recognize as a normal string
```
pip install 'pytorch-forecasting[mqf2]'
```
or
```
pip install pytorch-forecasting\[mqf2\]
```

**Comment by signalworker123** [comment]
an error occur ：Invalid requirement: "'pytorch-forecasting[mqf2]'"
can you help me？ 
thanks

**Comment by zhaobozb** [comment]
Thank you so much for your reply @wzbitl. It works.
