### ISSUE TITLE
Update scikit-learn version requirement to allow v1.2

### ISSUE THREAD

**Issue by melanopsis** [jdb78/pytorch-forecasting#1206]
Greetings,

Scikit-learn 1.2.0 was released recently https://github.com/scikit-learn/scikit-learn/releases/tag/1.2.0. Pytorch-forecasting currently requires `scikit-learn = ">=0.24,<1.2"`. It would be nice to let version 1.2 install. 

Thank you.

**Comment by graille** [comment]
Any update on this ?
