### ISSUE TITLE
N-Beats on M4 Dataset (with NAN)

### ISSUE THREAD

**Issue by dean-sh** [jdb78/pytorch-forecasting#121]
Hey,
I'm trying to run N-Beats from the tutorial on M4 dataset.

For example, using the hourly data:
V1 | V2 | V3 | V4 | V5 | V6 | V7 | V8 | V9 | V10 | ... | V952 | V953 | V954 | V955 | V956 | V957 | V958 | V959 | V960 | V961
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
H1 | 605.0 | 586.0 | 586.0 | 559.0 | 511.0 | 443.0 | 422.0 | 395.0 | 382.0 | ... | NaN | NaN | NaN | NaN | NaN | NaN | NaN | NaN | NaN | NaN
H2 | 3124.0 | 2990.0 | 2862.0 | 2809.0 | 2544.0 | 2201.0 | 1996.0 | 1861.0 | 1735.0 | ... | NaN | NaN | NaN | NaN | NaN | NaN | NaN | NaN | NaN | NaN

I've melted the dataset to the `TimeSeriesDataSet` format and used the tutorial.
The difference with the M4 data compared to the toy dataset in the tutorial is that the series are of unequal length, therefore there are NAN's at the end. I've used the `allow_missings=True` option.

The baseline predictions are filled with NANs, which causes a warning and gives a very high SMAPE loss.
```
baseline_predictions
>>> tensor([[nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        ...

SMAPE()(baseline_predictions, actuals)
>>>UserWarning: Loss is not finite. Resetting it to 1e9
  warnings.warn("Loss is not finite. Resetting it to 1e9")
```

The above is "solved" by dropping NA's from the dataset - the net is training as expected. But this leaves me with very little data.
How can I still work around the NAs? 

- PyTorch-Forecasting version: 0.5.2
- PyTorch lightening version:1.0.3
- Python version: 3.8
- Operating System: Ubuntu 20.04

**Comment by jdb78** [comment]
The issue seems to be a misunderstanding of what `allow_missings=True` does which allows you to fill in missing datapoints (that are not recorded but exist such as zero demand). I should clarify this in the docs.
You should drop the NaNs because they are not real datapoints. Set the min_encoder_length to something reasonable to get a sufficient number of training datapoints.

**Comment by dean-sh** [comment]
Hey,

**Comment by dean-sh** [comment]
ank

**Comment by dean-sh** [comment]
Hey, thanks for the quick reply!
(sorry, closed by mistake).
I understand the logic now. removed the NA's.
If all of the data has the same time_idx (start to end) - there's no issue.

However, I'm struggling with creation of the data loaders in cases where the time series are of **unequal length** - some are longer than others (without NAs).

In this case, I'd like the training/val splitting to be according to each serie length.

This is my code, based on the example notebook:
```
# create dataset and dataloaders
max_encoder_length = 100
max_prediction_length = 30

training_cutoff = data["time_idx"].max() - max_prediction_length

context_length = max_encoder_length
prediction_length = max_prediction_length

# create trainer
training = TimeSeriesDataSet(
    data[lambda x: x.time_idx <= training_cutoff],
    time_idx="time_idx",
    target="value",
    categorical_encoders={"ID": NaNLabelEncoder().fit(data.ID)},
    group_ids=["ID"],
    time_varying_unknown_reals=["value"],
    max_encoder_length=context_length,
    max_prediction_length=prediction_length,
    min_encoder_length=max_encoder_length,
)

validation = TimeSeriesDataSet.from_dataset(training, data, min_prediction_idx = training_cutoff+1, stop_randomization=True)
batch_size = 128
train_dataloader = training.to_dataloader(train=True, batch_size=batch_size, num_workers=0)
val_dataloader = validation.to_dataloader(train=False, batch_size=batch_size, num_workers=0)
```
When doing so, basically I'm getting only 1 prediction range, for only one series, in my validation set - because `data[lambda x: x.time_idx <= training_cutoff]` basically cuts the entire training set without grouping it.

I've tried to solve it by creating a training and validation datasets, like so, 
```
max_prediction_length = 100
dfg = data.groupby('ID')
training_data = dfg.apply(lambda x: x.iloc[:-max_prediction_length]).reset_index(level=0, drop=True)
val_data = dfg.apply(lambda x: x.iloc[-max_prediction_length:]).reset_index(level=0, drop=True)
```
but then I'm getting an error while creating the validation TimeSeriesDataSet.
```
validation = TimeSeriesDataSet.from_dataset(training, val_data ,stop_randomization=True)
>>>AssertionError: filters should not remove entries```

Any ideas? :) 

Thank you!

**Comment by jdb78** [comment]
What is happening is that complete series/groups are removed from your val_data because of the length restrictions. I think there are multiple remedies. Either:
* You could run with a reduced `min_encoder_length`
* I guess you can determine your time_idx by series and cut it accordingly. Or the simplest way (if you want to predict the last `max_prediction_length` samples. Is to create a val_dataloader with `validation.to_dataloader(train=False, predict=True)` where validation was created without `min_prediction_idx`. This effectively uses the last `max_prediction_length` samples for validation.
