### ISSUE TITLE
Support PyTorch (Lightning) 2.0

### ISSUE THREAD

**Issue by antolu** [jdb78/pytorch-forecasting#1285]
- PyTorch-Forecasting version: 0.10.3
- PyTorch-Lightning version: 1.9.3
- PyTorch version: 2.0
- Python version: 3.9
- Operating System: Linux

Pytorch 2.0 is 100% backwards compatible, however Pytorch Lightning 2.0 that leverages the power of Pytorch 2.0 is incompatible.

Significant changes were made in the LightningModule class that breaks compatibility: https://lightning.ai/docs/pytorch/stable/upgrade/migration_guide.html

**Comment by jdb78** [comment]
#1280
