### ISSUE TITLE
Bug .get_parameters()

### ISSUE THREAD

**Issue by silvioba** [jdb78/pytorch-forecasting#131]
- PyTorch-Forecasting version: 0.5.2
- PyTorch version: 1.7.0
- Python version: 3.7
- Operating System: macOS 10.15.7

### Expected behavior

`df_train` is a pandas dataframe with columns `'timestamp', 'user_id', 'content_id', 'content_type_id',
                     'prior_question_elapsed_time',
                     'prior_question_had_explanation_False',
                     'prior_question_had_explanation_True',
                     'question_cluster', 'answered_correctly'`
a minimal version of the code is:

    from pytorch_forecasting import TimeSeriesDataSet, TemporalFusionTransformer
    max_prediction_length = 1  # forecast 1 question
    max_encoder_length = 5  # use 5 question of history

    training = TimeSeriesDataSet(data=df_train,
                                 time_idx="timestamp",
                                 target="answered_correctly",
                                 group_ids=["user_id"],
                                 min_encoder_length=0,  # allow predictions without history
                                 max_encoder_length=max_encoder_length,
                                 min_prediction_length=1,
                                 max_prediction_length=max_prediction_length,
                                 static_categoricals=["user_id"],
                                 allow_missings=True,
                                 static_reals=[],
                                 time_varying_known_categoricals=[],
                                 time_varying_known_reals=[],
                                 time_varying_unknown_categoricals=[],
                                 time_varying_unknown_reals=['content_id',
                                                             'content_type_id',
                                                             'prior_question_elapsed_time',
                                                             'prior_question_had_explanation_False',
                                                             'prior_question_had_explanation_True',
                                                             'question_cluster']
                                 )
    print(training.get_parameters())
 I would expect to get a dict with the parameters on the std output

### Actual behavior

However, I get the following:

> Traceback (most recent call last):
>   File "/Users/silvio/Desktop/working/train_TS_nn.py", line 144, in <module>
>     print(training.get_parameters())
>   File "/Users/silvio/Desktop/working/venv/lib/python3.7/site-packages/pytorch_forecasting/data/timeseries.py", line 615, in get_parameters
>     name: getattr(self, name) for name in inspect.signature(self.__class__).parameters.keys() if name != "data"
>   File "/Users/silvio/Desktop/working/venv/lib/python3.7/site-packages/pytorch_forecasting/data/timeseries.py", line 615, in <dictcomp>
>     name: getattr(self, name) for name in inspect.signature(self.__class__).parameters.keys() if name != "data"
> AttributeError: 'TimeSeriesDataSet' object has no attribute 'args'

**Comment by jdb78** [comment]
The current master has this issue fixed #117.

**Comment by jdb78** [comment]
Fix was released in [v0.5.3](https://github.com/jdb78/pytorch-forecasting/releases/tag/v0.5.3).
