### ISSUE TITLE
TemporalFusionTransformer logging active during prediction by Default

### ISSUE THREAD

**Issue by vilorel** [jdb78/pytorch-forecasting#1315]
- PyTorch-Forecasting version: 1.0.0
- PyTorch version: 2.0.1+cpu
- Python version: 3.10
- Operating System: Ubuntu

### Expected behavior

I execute the following code to use a trained TemporalFusionTransformer model to make real-time (not batch) predictions. I am serving the model via FastAPI.   

### Actual behavior

The predictions are coming clean (no issues there). However, for every prediction, logs are also active and generated. 

How do I deactivate them? (No logging during prediction)

### Code to reproduce the problem

```
model = TemporalFusionTransformer.load_from_checkpoint(
        model_path + best_checkpoint)
model.eval()
model.freeze()
raw_predictions = model.predict(df, mode="raw", return_x=False, output_dir=None)
```

**Comment by vilorel** [comment]
I guess these are tensorboard log files but how do I stop them from being generated?

**Comment by Nephdz** [comment]
You can put this in your predict method:

`trainer_kwargs={'logger':False}`

If you look at the predict method in the BaseModel class, pytorch lightning's Trainer is called to perform the predict. The Trainer has an option to turn off logging to TensorBoard.

https://github.com/jdb78/pytorch-forecasting/blob/7c775c1a2fe3effe62eac0a476db98ca5b24ca4c/pytorch_forecasting/models/base_model.py#LL1340C5-L1427C39

**Comment by vilorel** [comment]
@Nephdz thanks so much!
