### ISSUE TITLE
N steps ahead forecasting

### ISSUE THREAD

**Issue by erl61** [jdb78/pytorch-forecasting#1371]
- PyTorch-Forecasting version: 1.0.0
- PyTorch version: 2.0.1
- Python version: 3.9.6
- Operating System: MacOS

Hi everyone! 

When I fit my model I set max_prediction_length=120 time steps, and tft.predict(data) returns next 120 time steps. Is there any method to forecast N next time steps, where N > max_prediction_length ?
I think I can forecast max_prediction_length time steps ahead, then add it to my known data and then forecast next 120 time steps. So I will get 2*max_prediction_length time steps ahead. But I didn't find any function like this in the library. Is it possible to add this function or am I wrong here?

Thanks!

**Comment by afanasjev82** [comment]
It's possible to do by passing dataloader to `.predict` function:
### Load the model
`model = TemporalFusionTransformer.load_from_checkpoint(/path/to/checkpoint.ckpt)`

### Create dataset
`dataset = TimeSeriesDataSet.from_parameters(parameters=model.dataset_parameters, data=data, predict=True, max_prediction_length=model.dataset_parameters["max_prediction_length"]*2)
`

### Create dataloader
`dataloader = dataset.to_dataloader(train=False)`

### Predict using dataloader
`raw_predictions = best_tft.predict(dataloader)`
