### ISSUE TITLE
Questions about TimeSeriesDataSet structure and sampling

### ISSUE THREAD

**Issue by fraserprice** [jdb78/pytorch-forecasting#144]
First of all, this library is **fantastic**- thanks so much for the work!

I am attempting to train TFT on a very large time series dataset, but am finding working with the TimeSeriesDataSet fairly confusing with the current documentation; it would be great if anyone can clarify the following:

- **Should group_ids identify samples of time series or whole time series?** If i have some time series (call it 'PRICE') with a length of 1,000 but a sample length of 100 for my model, should I create e.g. 10 group identifiers ('PRICE0-PRICE9') to specify training examples, or should I keep as single series?

- **How are training examples sampled from a TimeSeriesDataSet?** Assuming group_ids identify whole time series, how are training examples sampled from a series? Are random blocks taken? Are they taken in order? This is not very clear.

- **Are samples aligned by time_idx?** If I have multiple time series which should be aligned (e.g. prices of multiple securities), will they be aligned by time_idx when sampled? If so, what happens when points are missing?

- **How are validation examples sampled?**

- **Is there support for very large datasets?** The dataset I am working with is >100GB of time series data; loading it all into a DataFrame isn't possible. Is there support for building custom DataLoaders which can load batches at train time?

I would be happy to update documentation if these are answered, thanks a lot!

**Comment by jdb78** [comment]
I started to improve the documentation. Could you have a look at the PR #145 and see if it answers your questions?

**Comment by fraserprice** [comment]
This is absolutely fantastic, thank you so much!
