### ISSUE TITLE
Construction of TimeSeriesDataSet for interrupted sequences and variable sequence sampling frequency

### ISSUE THREAD

**Issue by tomasvanoyen** [jdb78/pytorch-forecasting#154]
Hi, 
I have a question on the TimeSeriesDataSet class. In my case, I have a time series sequence with a sampling frequency of 15 minutes, and one target variable. Unfortunately, the sequence is extensively interrupted (too extensively to impute the np.nan's with values) at several points in the sequence; e.g. it looks like: 
|                           |   target |   input_0 |
|:--------------------------|---------:|----------:|
| 2004-10-31 23:00:00+00:00 |     90   |      3.3  |
| 2004-10-31 23:15:00+00:00 |     91.5 |      3.3  |
| ..... |     91.5 |      3.3  |
| 2004-11-30 23:15:00+00:00 |     91.5 |      3.3  |
| 2004-11-30 23:30:00+00:00 |     np.nan   |      np.nan |
| .... |     np.nan   |      np.nan |
| 2004-12-01 23:30:00+00:00 |     89.5 |      3.25 |
| 2004-12-01 23:45:00+00:00 |     86   |      3.2  |

How to handle this? From the documentation, I have understood that I could handle this by assigning to each uninterrupted chunk of the time series a different 'timeseries' number: 
|                           |   target |   input_0 | timeseries |
|:--------------------------|---------:|----------:|----------:|
| 2004-10-31 23:00:00+00:00 |     90   |      3.3  | 0 |
| 2004-10-31 23:15:00+00:00 |     91.5 |      3.3  | 0 |
| ..... |     91.5 |      3.3  | 0 |
| 2004-11-30 23:15:00+00:00 |     91.5 |      3.3  | 0 |
| 2004-12-01 23:30:00+00:00 |     89.5 |      3.25 | 1 |
| 2004-12-01 23:45:00+00:00 |     86   |      3.2  | 1 |

Is this correct? 

In addition, I understand that to make predictions for 6 points in the future based on 24 points in the past I need to set  `max_prediction_length = 6` and `max_encoder_length = 24` (is this correct?). However, suppose that I want to predict 6 points in the future, with a frequency of 30 minutes; using 24 points in the past with a different sampling frequency (say an hour).  How to achieve this? Should I make one dataframe with many 'time series', where each time series only has 30 points (the 24 first points the input sampled every hour and the final 6 points to predict which are sampled every 30 minutes)? Would that work? 

Many thanks in any case!
Tomas

**Comment by jdb78** [comment]
Thanks Tomas for your interest in the package!

> How to handle this? From the documentation, I have understood that I could handle this by assigning to each uninterrupted chunk of the time series a different 'timeseries' number:
> [...]
> Is this correct?

Yes, that is a correct understanding.

> In addition, I understand that to make predictions for 6 points in the future based on 24 points in the past I need to set max_prediction_length = 6 and max_encoder_length = 24 (is this correct?)

Yes. However, the number of encoder and prediction/decoder time steps should be larger than the number of timesteps in the timeseries (as you want to learn something!). You can also use a min_encoder_length and min_prediction_length to that means if the algorithm you want to use, can work with it (be careful not to set a min_encoder_length smaller than, say 1/4 of the max_encoder_length).

> However, suppose that I want to predict 6 points in the future, with a frequency of 30 minutes; using 24 points in the past with a different sampling frequency (say an hour). How to achieve this?

Prediction and encoder granularity must be the same, i.e. you cannot train on samples 15min ahead and make predictions every 30min. Either, you predict 12 points into the future and then aggregate the results or you resample your timeseries to 30min and then predict 6 points into the future.

Does this answer your questions?

**Comment by tomasvanoyen** [comment]
Hi Jan, 
thank you for your fast reply. 
I think your answers clarified most of my questions. I am only a bit puzzled by the following: 

> Yes. However, the number of encoder and prediction/decoder time steps should be larger than the number of timesteps in the timeseries (as you want to learn something!). 

I guess you mean: the number of encoder and prediction/decoder time steps should be _**smaller**_ than the number of timesteps in the timeseries? E.g. in the temporal fusion transformer tutorial, `max_prediction_length = 6` and 
`max_encoder_length = 24` . Together this is 30 and this is **_smaller_** than the number of sequential time points in each timeseries (which is 60). 

Thanks in any case!

**Comment by jdb78** [comment]
Yes. you are right. Sorry for the confusion!
