### ISSUE TITLE
KeyError: 'module name can\'t contain "."'

### ISSUE THREAD

**Issue by dnwldnwl2** [jdb78/pytorch-forecasting#155]
while following tutorial with my own dataset error occured.

baseline model was ok but TFT not working

## code

pl.seed_everything(42) ## 
trainer = pl.Trainer( 
    gpus=0,
    # clipping gradients is a hyperparameter and important to prevent divergance
    # of the gradient for recurrent neural networks
    gradient_clip_val=0.1, 
)

tft = TemporalFusionTransformer.from_dataset(
    training,
    # not meaningful for finding the learning rate but otherwise very important
    learning_rate=0.03,
    hidden_size=16,  # most important hyperparameter apart from learning rate  
    # number of attention heads. Set to up to 4 for large datasets
    attention_head_size=1,
    dropout=0.1,  # between 0.1 and 0.3 are good values
    hidden_continuous_size=8,  # set to <= hidden_size 
    output_size=7,  # 7 quantiles by default 
    loss=QuantileLoss(),
    # reduce learning rate if no improvement in validation loss after x epochs
    reduce_on_plateau_patience=4
)
print(f"Number of parameters in network: {tft.size()/1e3:.1f}k")

## error
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-19-d191349cbecf> in <module>
     24     loss=QuantileLoss(),
     25     # reduce learning rate if no improvement in validation loss after x epochs
---> 26     reduce_on_plateau_patience=4, ## patience after which learning rate is reduced by a factor of 10 
     27 )
     28 print(f"Number of parameters in network: {tft.size()/1e3:.1f}k")

/kaggle/working/pytorch_forecasting/models/temporal_fusion_transformer/__init__.py in from_dataset(cls, dataset, allowed_encoder_known_variable_names, **kwargs)
    341         # create class and return
    342         return super().from_dataset(
--> 343             dataset, allowed_encoder_known_variable_names=allowed_encoder_known_variable_names, **new_kwargs
    344         )
    345 

/kaggle/working/pytorch_forecasting/models/base_model.py in from_dataset(cls, dataset, allowed_encoder_known_variable_names, **kwargs)
    887         )
    888         new_kwargs.update(kwargs)
--> 889         return super().from_dataset(dataset, **new_kwargs)
    890 
    891     def calculate_prediction_actual_by_variable(

/kaggle/working/pytorch_forecasting/models/base_model.py in from_dataset(cls, dataset, **kwargs)
    534         if "output_transformer" not in kwargs:
    535             kwargs["output_transformer"] = dataset.target_normalizer
--> 536         net = cls(**kwargs)
    537         net.dataset_parameters = dataset.get_parameters()
    538         return net

/kaggle/working/pytorch_forecasting/models/temporal_fusion_transformer/__init__.py in __init__(self, hidden_size, lstm_layers, dropout, output_size, loss, attention_head_size, max_encoder_length, static_categoricals, static_reals, time_varying_categoricals_encoder, time_varying_categoricals_decoder, categorical_groups, time_varying_reals_encoder, time_varying_reals_decoder, x_reals, x_categoricals, hidden_continuous_size, hidden_continuous_sizes, embedding_sizes, embedding_paddings, embedding_labels, learning_rate, log_interval, log_val_interval, log_gradient_flow, reduce_on_plateau_patience, monotone_constaints, share_single_variable_networks, logging_metrics, **kwargs)
    144             embedding_paddings=self.hparams.embedding_paddings,
    145             x_categoricals=self.hparams.x_categoricals,
--> 146             max_embedding_size=self.hparams.hidden_size,
    147         )
    148 

/kaggle/working/pytorch_forecasting/models/nn/embeddings.py in __init__(self, embedding_sizes, categorical_groups, embedding_paddings, x_categoricals, max_embedding_size)
     43         self.x_categoricals = x_categoricals
     44 
---> 45         self.init_embeddings()
     46 
     47     def init_embeddings(self):

/kaggle/working/pytorch_forecasting/models/nn/embeddings.py in init_embeddings(self)
     66                     self.embedding_sizes[name][0],
     67                     embedding_size,
---> 68                     padding_idx=padding_idx,
     69                 )
     70 

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/container.py in __setitem__(self, key, module)
    285 
    286     def __setitem__(self, key: str, module: Module) -> None:
--> 287         self.add_module(key, module)
    288 
    289     def __delitem__(self, key: str) -> None:

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in add_module(self, name, module)
    345             raise KeyError("attribute '{}' already exists".format(name))
    346         elif '.' in name:
--> 347             raise KeyError("module name can't contain \".\"")
    348         elif name == '':
    349             raise KeyError("module name can't be empty string \"\"")

KeyError: 'module name can\'t contain "."'

**Comment by jdb78** [comment]
To narrow down the problem, what are your pytorch and pytorch forecasting versions? If you install the latest, does the problem persist?

**Comment by dnwldnwl2** [comment]
> 
> 
> To narrow down the problem, what are your pytorch and pytorch forecasting versions? If you install the latest, does the problem persist?

Torch 1.6.0 and pytorch_forcasting latest. Both worked well on stallion data. It persisted after updating torch 1.7.0. I think there is something wrong with the data processing.

**Comment by jdb78** [comment]
Could you post your dataset definition and if possible a first couple of rows of the pandas dataframe itself?

**Comment by dnwldnwl2** [comment]
> 
> 
> Could you post your dataset definition and if possible a first couple of rows of the pandas dataframe itself?

Embarrassingly, I renamed all columns and now it works... Thanks for your helping.
