### ISSUE TITLE
[BUG] Import error with `numpy 2.X` due to the `np.lib.function_base.iterable` 

### ISSUE THREAD

**Issue by shengy90** [jdb78/pytorch-forecasting#1568]
- PyTorch-Forecasting version: 1.0.0
- PyTorch version: 2.3.0
- Python version: 3.9
- Operating System: Mac OS Sonoma
- Numpy version: 2.0.0rc

### Expected behavior
from pytorch_forecasting.utils import autocorrelation

### Actual behavior

Import error: `No module named 'numpy.lib.function_base'`

### Code to reproduce the problem

```
from pytorch_forecasting.utils import autocorrelation
```

I think the issue is from `from numpy.lib.function_base import iterable` in base_model.py, but function_base is deprecated. You can now import iterable directly in numpy like so: `from numpy import iterable`. 

I'm on Numpy 2.0, but I think this change is already in latest version of numpy 1.26 (https://numpy.org/doc/stable/reference/generated/numpy.iterable.html)

**Comment by diegovilarinho** [comment]
We had any update on this issue? Some PR, maybe?

**Comment by fkiraly** [comment]
Fixed by @XinyuWuu in https://github.com/jdb78/pytorch-forecasting/pull/1599, but there seems to be a different `numpy 2` issue as well, only on mac though: https://github.com/jdb78/pytorch-forecasting/issues/1594
