### ISSUE TITLE
question : dataloader size?

### ISSUE THREAD

**Issue by dnwldnwl2** [jdb78/pytorch-forecasting#158]
- PyTorch-Forecasting version: latest
- PyTorch version: 1.7
- Python version: 3.7
- Operating System: debian

##
Hi. I thought TimeSeriesDataSet automatically group input data using group_id. In stallion data, there are 351 unique groups and there are 20651 items in train_dataloader (when i set batch size =1). What makes this difference? 

And how is the size of the valdiation determined? I checked to_dataloader but couldn't find the answer.

**Comment by JakeForsey** [comment]
I couldn't reproduce this using exampls/stallion.py as a base (see below).

Could you share your dataset code?


in:
```
import warnings

import numpy as np
from pandas.core.common import SettingWithCopyWarning

from pytorch_forecasting import GroupNormalizer, TimeSeriesDataSet
from pytorch_forecasting.data.examples import get_stallion_data

warnings.simplefilter("error", category=SettingWithCopyWarning)


data = get_stallion_data()

data["month"] = data.date.dt.month.astype("str").astype("category")
data["log_volume"] = np.log(data.volume + 1e-8)

data["time_idx"] = data["date"].dt.year * 12 + data["date"].dt.month
data["time_idx"] -= data["time_idx"].min()
data["avg_volume_by_sku"] = data.groupby(["time_idx", "sku"], observed=True).volume.transform("mean")
data["avg_volume_by_agency"] = data.groupby(["time_idx", "agency"], observed=True).volume.transform("mean")
# data = data[lambda x: (x.sku == data.iloc[0]["sku"]) & (x.agency == data.iloc[0]["agency"])]
special_days = [
    "easter_day",
    "good_friday",
    "new_year",
    "christmas",
    "labor_day",
    "independence_day",
    "revolution_day_memorial",
    "regional_games",
    "fifa_u_17_world_cup",
    "football_gold_cup",
    "beer_capital",
    "music_fest",
]
data[special_days] = data[special_days].apply(lambda x: x.map({0: "", 1: x.name})).astype("category")

training_cutoff = data["time_idx"].max() - 6
max_encoder_length = 36
max_prediction_length = 6

training = TimeSeriesDataSet(
    data[lambda x: x.time_idx <= training_cutoff],
    time_idx="time_idx",
    target="volume",
    group_ids=["agency", "sku"],
    min_encoder_length=max_encoder_length // 2,  # allow encoder lengths from 0 to max_prediction_length
    max_encoder_length=max_encoder_length,
    min_prediction_length=1,
    max_prediction_length=max_prediction_length,
    static_categoricals=["agency", "sku"],
    static_reals=["avg_population_2017", "avg_yearly_household_income_2017"],
    time_varying_known_categoricals=["special_days", "month"],
    variable_groups={"special_days": special_days},  # group of categorical variables can be treated as one variable
    time_varying_known_reals=["time_idx", "price_regular", "discount_in_percent"],
    time_varying_unknown_categoricals=[],
    time_varying_unknown_reals=[
        "volume",
        "log_volume",
        "industry_volume",
        "soda_volume",
        "avg_max_temp",
        "avg_volume_by_agency",
        "avg_volume_by_sku",
    ],
    target_normalizer=GroupNormalizer(
        groups=["agency", "sku"], coerce_positive=1.0
    ),  # use softplus with beta=1.0 and normalize by group
    add_relative_time_idx=True,
    add_target_scales=True,
    add_encoder_length=True,
)


validation = TimeSeriesDataSet.from_dataset(training, data, predict=True, stop_randomization=True)
print("Validation dataset: ", len(validation))

batch_size = 64
train_dataloader = training.to_dataloader(train=True, batch_size=batch_size, num_workers=0)
val_dataloader = validation.to_dataloader(train=False, batch_size=1, num_workers=0)
print("Validation dataloader: ", len(val_dataloader))

```

out:
```
Validation dataset:  350
Validation dataloader:  350
```

**Comment by dnwldnwl2** [comment]
> 
> 
> I couldn't reproduce this using exampls/stallion.py as a base (see below).
> 
> Could you share your dataset code?
> 
> in:
> 
> ```
> import warnings
> 
> import numpy as np
> from pandas.core.common import SettingWithCopyWarning
> 
> from pytorch_forecasting import GroupNormalizer, TimeSeriesDataSet
> from pytorch_forecasting.data.examples import get_stallion_data
> 
> warnings.simplefilter("error", category=SettingWithCopyWarning)
> 
> 
> data = get_stallion_data()
> 
> data["month"] = data.date.dt.month.astype("str").astype("category")
> data["log_volume"] = np.log(data.volume + 1e-8)
> 
> data["time_idx"] = data["date"].dt.year * 12 + data["date"].dt.month
> data["time_idx"] -= data["time_idx"].min()
> data["avg_volume_by_sku"] = data.groupby(["time_idx", "sku"], observed=True).volume.transform("mean")
> data["avg_volume_by_agency"] = data.groupby(["time_idx", "agency"], observed=True).volume.transform("mean")
> # data = data[lambda x: (x.sku == data.iloc[0]["sku"]) & (x.agency == data.iloc[0]["agency"])]
> special_days = [
>     "easter_day",
>     "good_friday",
>     "new_year",
>     "christmas",
>     "labor_day",
>     "independence_day",
>     "revolution_day_memorial",
>     "regional_games",
>     "fifa_u_17_world_cup",
>     "football_gold_cup",
>     "beer_capital",
>     "music_fest",
> ]
> data[special_days] = data[special_days].apply(lambda x: x.map({0: "", 1: x.name})).astype("category")
> 
> training_cutoff = data["time_idx"].max() - 6
> max_encoder_length = 36
> max_prediction_length = 6
> 
> training = TimeSeriesDataSet(
>     data[lambda x: x.time_idx <= training_cutoff],
>     time_idx="time_idx",
>     target="volume",
>     group_ids=["agency", "sku"],
>     min_encoder_length=max_encoder_length // 2,  # allow encoder lengths from 0 to max_prediction_length
>     max_encoder_length=max_encoder_length,
>     min_prediction_length=1,
>     max_prediction_length=max_prediction_length,
>     static_categoricals=["agency", "sku"],
>     static_reals=["avg_population_2017", "avg_yearly_household_income_2017"],
>     time_varying_known_categoricals=["special_days", "month"],
>     variable_groups={"special_days": special_days},  # group of categorical variables can be treated as one variable
>     time_varying_known_reals=["time_idx", "price_regular", "discount_in_percent"],
>     time_varying_unknown_categoricals=[],
>     time_varying_unknown_reals=[
>         "volume",
>         "log_volume",
>         "industry_volume",
>         "soda_volume",
>         "avg_max_temp",
>         "avg_volume_by_agency",
>         "avg_volume_by_sku",
>     ],
>     target_normalizer=GroupNormalizer(
>         groups=["agency", "sku"], coerce_positive=1.0
>     ),  # use softplus with beta=1.0 and normalize by group
>     add_relative_time_idx=True,
>     add_target_scales=True,
>     add_encoder_length=True,
> )
> 
> 
> validation = TimeSeriesDataSet.from_dataset(training, data, predict=True, stop_randomization=True)
> print("Validation dataset: ", len(validation))
> 
> batch_size = 64
> train_dataloader = training.to_dataloader(train=True, batch_size=batch_size, num_workers=0)
> val_dataloader = validation.to_dataloader(train=False, batch_size=1, num_workers=0)
> print("Validation dataloader: ", len(val_dataloader))
> ```
> 
> out:
> 
> ```
> Validation dataset:  350
> Validation dataloader:  350
> ```

It is correct that validation and val_dataloader have the same size.  My question was two. And in the first question, what I'm saying is about training_dataloader and groups in stallion data. val_dataloader is related to the second question and it was that if there is a way to determine val_dataloader size. Of course I could control it manually...

Oh, 351 was my mistake it's 350. 

in your code:
###

train_dataloader = training.to_dataloader(train=True, batch_size=1, num_workers=0)
val_dataloader = validation.to_dataloader(train=False, batch_size=1, num_workers=0)
print("train dataloader: ", len(train_dataloader))
print("Validation dataloader: ", len(val_dataloader))

###
train dataloader:  20650
Validation dataloader:  350

**Comment by JakeForsey** [comment]
Apologies, I miss read your questions!

My understanding is that based on the max_encoder_length and max_prediction_length many samples can be drawn from a single time series.

For example if we have a single time series with a length 10, max_encoder_length=8 and max_prediction_length=1 we could drawn two samples:
 * Sample 1:
   * input: 0 -> 8 
   * target: 8 -> 9
 * Sample 2:
   * input: 1->9
   * target: 9 -> 10

When you create a dataloader using to_dataloader(train=False) you only get the last sample in the above example.

**Comment by jdb78** [comment]
Just adding here: The items in the dataloader are all the subsequences that will be used for training. If a sequence is longer than the maximum encoder and decoder length, subsequences will be generated.

**Comment by dnwldnwl2** [comment]
Oh i see. Thank you JakeForsey and jdb78!
