### ISSUE TITLE
warnings.warn Type error: expected string or bytes-like object

### ISSUE THREAD

**Issue by diditforlulz273** [jdb78/pytorch-forecasting#159]
- PyTorch-Forecasting version: 0.6.0
- PyTorch version: 1.6
- Python version: 3.8
- Operating System: Ubuntu 20.04

I updated PyTorch-Forecasting from 0.5.2. to 0.6.0.
Seems like a part of your code in timeseries.py around [804:812] has a mistake.
Here how it looks:

**warnings.warn(
                (
                    "Min encoder length and/or min_prediction_idx and/or min prediction length is too large for "
                    f"{len(missing_groups)} series/groups which therefore are not present in the dataset index. "
                    "This means no predictions can be made for those series",
                    f"First 10 removed groups: {list(missing_groups.iloc[:10].to_dict(orient='index').values())}",
                ),
                UserWarning,
            )**

which results in **Typeerror: expected string or bytes-like object**

You have two redundant commas in the message part which crashes the code. Should look like:

warnings.warn(
                (
                    "Min encoder length and/or min_prediction_idx and/or min prediction length is too large for "
                    f"{len(missing_groups)} series/groups which therefore are not present in the dataset index. "
                    "This means no predictions can be made for those series"**<NO_COMMA>**
                    f"First 10 removed groups: {list(missing_groups.iloc[:10].to_dict(orient='index').values())}"**<NO_COMMA>**
                ),
                UserWarning,
            )

am I right?

**Comment by jdb78** [comment]
Thanks for the pointer! Being fixed.
