### ISSUE TITLE
[MNT] manage core dependencies prior to 1.1.0 release

### ISSUE THREAD

**Issue by fkiraly** [jdb78/pytorch-forecasting#1616]
Before we release 1.1.0, we should make sure we have managed the core dependencies carefully.

For instance, we do not want to add core dependencies that can be avoided, and potentially remove core dependencies that can be isolated.

Things to ensure we watch out for:

* current fixes to CI added core dependencies - `optuna-integration`, `pyarrow`, `tensorflow`, `cpflows`.
    * `optuna-integrations` is required only if `optuna>=3.3.0`
* downwards compatibility of depedency sets, we should not remove `mqf2`
* bounds compatibility

**Comment by fkiraly** [comment]
@benHeid, @yarnabrina, @fnhirwa, @XinyuWuu, question: what should be the end state of core/soft dependencies?

We should discuss soft dependencies and potential soft dependencies:

* `optuna`, `statsmodels` - used only in the tuner, very localized scope of coupling; the dependency locus requires `optuna-integration` from `optuna 3.3.0` onwards
* `matplotlib` - heavy dependency, used in some loggers. Can be turned off
* pre-existing softdep sets `graph`, `mqf2`, `github-actions`
* `scikit-learn`, `pandas` - less localized, more central
* `scipy` - imported only twice for special `scipy.stats`, but an indirect dep of `scikit-learn`

**Comment by fkiraly** [comment]
My suggested end state for the 1.1.0 release:

core = `torch`, `lightning`, `scikit-learn`, `pandas`, `scipy`

`all_extras` = `optuna`, `optuna-integration`, `statsmodels`, `matplotlib`, `pytorch_optimizer`

existing dep sets `graph`, `mqf2`, `github-actions` remain unchanged

**Comment by benHeid** [comment]
I agree to your proposed end state.

**Comment by fnhirwa** [comment]
> My suggested end state for the 1.1.0 release:
> 
> core = `torch`, `lightning`, `scikit-learn`, `pandas`, `scipy`
> 
> `all_extras` = `optuna`, `optuna-integration`, `statsmodels`, `matplotlib`, `pytorch_optimizer`
> 
> existing dep sets `graph`, `mqf2`, `github-actions` remain unchanged

This makes sense to me also

**Comment by fkiraly** [comment]
done with 1.1.0 release
