### ISSUE TITLE
KeyError: 'module name can\'t contain "."'

### ISSUE THREAD

**Issue by jbelisario** [jdb78/pytorch-forecasting#175]
- PyTorch-Forecasting version: 0.6.1
- PyTorch version: 1.7.0+cu101
- Python version: 3.6.9
- Operating System: Windows 

### Expected behavior
I executed code with the intention of creating the TFT model object from a TimeSeriesDataset.

The expected result was a TFT model object that I would proceed to evaluate.

### Actual behavior
The result was the following: KeyError: 'module name can\'t contain "."'

I'm not sure what it has to do with, spent a while digging through the PyTorch source code but this issue is rooted deep. 
Not really sure what module is being added, where I can see the names of the modules, and why a module name would have a period in it. 

### Code to reproduce the problem

```
# configure network and trainer
pl.seed_everything(42)
trainer = pl.Trainer(
    gpus=0,
    # clipping gradients is a hyperparameter and important to prevent divergance
    # of the gradient for recurrent neural networks
    gradient_clip_val=0.1,
)


tft = TemporalFusionTransformer.from_dataset(
    training,
    # not meaningful for finding the learning rate but otherwise very important
    learning_rate=0.03,
    hidden_size=16,  # most important hyperparameter apart from learning rate
    # number of attention heads. Set to up to 4 for large datasets
    attention_head_size=1,
    dropout=0.1,  # between 0.1 and 0.3 are good values
    hidden_continuous_size=8,  # set to <= hidden_size
    output_size=7,  # 7 quantiles by default
    loss=QuantileLoss(),
    # reduce learning rate if no improvement in validation loss after x epochs
    reduce_on_plateau_patience=4,
)
print(f"Number of parameters in network: {tft.size()/1e3:.1f}k")
```

Here is the condensed traceback: 
![image](https://user-images.githubusercontent.com/24784133/100312621-d1604a00-2f80-11eb-93bc-3c82d30ea26b.png)

Expanded traceback: 
![image](https://user-images.githubusercontent.com/24784133/100312665-e9d06480-2f80-11eb-8ed2-029bc902051c.png)
![image](https://user-images.githubusercontent.com/24784133/100312679-f359cc80-2f80-11eb-9e57-7e0199e9a6d0.png)

Any help is greatly appreciated.

**Comment by diditforlulz273** [comment]
@jbelisario I had this issue with dataframe columns names containing " . " Try to deltele dots from your dataframe with this:
data.columns = [x.replace('.', '') for x in data.columns]

**Comment by jbelisario** [comment]
> @jbelisario I had this issue with dataframe columns names containing " . " Try to deltele dots from your dataframe with this:
> data.columns = [x.replace('.', '') for x in data.columns]

Thank you so much! I really appreciate the quick response as well. Cheers!
