### ISSUE TITLE
Prediction as a DataFrame

### ISSUE THREAD

**Issue by jfogelberg** [jdb78/pytorch-forecasting#177]
What would be the best way to get the tft prediction in the same format as my input dataframe?
Instead of just having tensors with predicted values and encoded group_ids I want to have a dataframe with my original group_ids (single value prediction or all quantiles).

I want to go from:
tensor([[0, 0], [0, 1]])
tensor([[234, 375], [73, 70]])

To:

| region         | sku               | time_idx       | prediction   | 
| ------------- | ------------- | ------------- | ------------- |
| reg1            | sku1            |   100             | 234              |
| reg1            | sku1            |   101             | 375              |
| reg1            | sku2            |   100             | 73                |
| reg1            | sku2            |   101             | 70                |

Thank you for a fantastic library!

**Comment by LukeOliv** [comment]
That is an excellent question. I've also struggled to figure out the raw predictions.

**Comment by jdb78** [comment]
You can use the [predict method](https://pytorch-forecasting.readthedocs.io/en/latest/api/pytorch_forecasting.models.base_model.BaseModel.html#pytorch_forecasting.models.base_model.BaseModel.predict):

```
prediction, prediction_index_df = network.predict(x, return_index=True)

prediction_df["prediction"] = prediction[:, 0]  # pick first prediction after encoding
```
You can return as prediction also quantiles or even the raw network output by specifying the `mode` argument.

**Comment by jfogelberg** [comment]
Perfect, just what I was looking for.
