### ISSUE TITLE
Forecasting after big change in trend

### ISSUE THREAD

**Issue by Tato14** [jdb78/pytorch-forecasting#178]
- PyTorch-Forecasting version:0.6.1
- PyTorch version:1.7.0
- Python version:3.7.8
- Operating System: Ubuntu 18.04

### Expected behavior
Following [demand forecasting tutorial](https://pytorch-forecasting.readthedocs.io/en/latest/tutorials/stallion.html#Demand-forecasting-with-the-Temporal-Fusion-Transformer)
I have a dataset that has a variable that changes the whole trend of the timeseries:
![Rplot](https://user-images.githubusercontent.com/33808607/100484855-4dcc6780-30fe-11eb-91ab-aa4b874e96fc.jpeg)

The thing is that I want to make the prediction *immediately after* this key point. I coded the variable in my dataset ('is_gx') but, since is different in my trianing and validation, when I added it in `time_varying_known_categoricals` (like `["special_days", "month"]` in stallion data) and run `validation = TimeSeriesDataSet.from_dataset(training, dat, predict=True, stop_randomization=True)` I got an error:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/home/jg/anaconda3/envs/PyTorch_forecasting/lib/python3.7/site-packages/pytorch_forecasting/data/encoders.py in transform(self, y)
    105             try:
--> 106                 encoded = [self.classes_[v] for v in y]
    107             except KeyError as e:

/home/jg/anaconda3/envs/PyTorch_forecasting/lib/python3.7/site-packages/pytorch_forecasting/data/encoders.py in <listcomp>(.0)
    105             try:
--> 106                 encoded = [self.classes_[v] for v in y]
    107             except KeyError as e:

KeyError: 'Generic'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-99-5d33ba4d21ac> in <module>()
      1 # create validation set (predict=True) which means to predict the last max_prediction_length points in time for each series
----> 2 validation = TimeSeriesDataSet.from_dataset(training, nov_dat, predict=True, stop_randomization=True)

/home/jg/anaconda3/envs/PyTorch_forecasting/lib/python3.7/site-packages/pytorch_forecasting/data/timeseries.py in from_dataset(cls, dataset, data, stop_randomization, predict, **update_kwargs)
    725         """
    726         return cls.from_parameters(
--> 727             dataset.get_parameters(), data, stop_randomization=stop_randomization, predict=predict, **update_kwargs
    728         )
    729 

/home/jg/anaconda3/envs/PyTorch_forecasting/lib/python3.7/site-packages/pytorch_forecasting/data/timeseries.py in from_parameters(cls, parameters, data, stop_randomization, predict, **update_kwargs)
    765         parameters.update(update_kwargs)
    766 
--> 767         new = cls(data, **parameters)
    768         return new
    769 

/home/jg/anaconda3/envs/PyTorch_forecasting/lib/python3.7/site-packages/pytorch_forecasting/data/timeseries.py in __init__(self, data, time_idx, target, group_ids, weight, max_encoder_length, min_encoder_length, min_prediction_idx, min_prediction_length, max_prediction_length, static_categoricals, static_reals, time_varying_known_categoricals, time_varying_known_reals, time_varying_unknown_categoricals, time_varying_unknown_reals, variable_groups, dropout_categoricals, constant_fill_strategy, allow_missings, add_relative_time_idx, add_target_scales, add_encoder_length, target_normalizer, categorical_encoders, scalers, randomize_length, predict_mode)
    317 
    318         # preprocess data
--> 319         data = self._preprocess_data(data)
    320 
    321         # create index

/home/jg/anaconda3/envs/PyTorch_forecasting/lib/python3.7/site-packages/pytorch_forecasting/data/timeseries.py in _preprocess_data(self, data)
    460         # encode them
    461         for name in set(group_ids_to_encode + self.flat_categoricals):
--> 462             data[name] = self.transform_values(name, data[name], inverse=False)
    463 
    464         # save special variables

/home/jg/anaconda3/envs/PyTorch_forecasting/lib/python3.7/site-packages/pytorch_forecasting/data/timeseries.py in transform_values(self, name, values, data, inverse, group_id)
    583                 return encoder.inverse_transform(values)
    584             else:
--> 585                 return encoder.transform(values)
    586 
    587         # reals

/home/jg/anaconda3/envs/PyTorch_forecasting/lib/python3.7/site-packages/pytorch_forecasting/data/encoders.py in transform(self, y)
    107             except KeyError as e:
    108                 raise KeyError(
--> 109                     f"Unknown category '{e.args[0]}' encountered. Set `add_nan=True` to allow unknown categories"
    110                 )
    111 

KeyError: "Unknown category 'Generic' encountered. Set `add_nan=True` to allow unknown categories"
```

As answered [here](https://github.com/jdb78/pytorch-forecasting/issues/157), adding this variable in `categorical_encoders={'is_gx': NaNLabelEncoder(add_nan=True)}` seems to solve the problem but I am not quite sure if this is the proper place to add it.

**Comment by Tato14** [comment]
Giving a little bit more of context. I found that this is something called "Extreme event forecasting" and that Uber team [has a paper on this](https://eng.uber.com/neural-networks/).

I found a TF implementation [here](https://github.com/cerlymarco/MEDIUM_NoteBook/tree/master/Extreme_Event_Forecasting). I would like to know if a FR could be ask in order to implement this in the library

**Comment by jdb78** [comment]
I think the key here is to have some extreme events including some time points afterwards in the training set. Only this way the network can learn about them. Also make sure that you have a sufficient high number of time series with an extreme event to facilitate learning from each other. In your case, the extreme event is in the validation set and I cannot think of any model that will be able to capture its significance during training.

**Comment by Tato14** [comment]
Thanks for the quick feedback. No, I actually want to predict the behaviour. It is expected to behave this way, so I guess its something like seasonality but "only once".

If I understood how the library work, it breaks the time series in two by the breackpoint you specify, right?

So, I was wondering if you could train on the whole time series. Then apply this model on a validation set without the points after the break? This is what you mention, right? How this could be done?

**Comment by jdb78** [comment]
> If I understood how the library work, it breaks the time series in two by the breackpoint you specify, right?

No, the library does not break the time series into two but learns that the event leads to a regime change (well, depending on the algorithm, but the TFT has been demonstrated to work well).

> So, I was wondering if you could train on the whole time series. Then apply this model on a validation set without the points after the break? This is what you mention, right? How this could be done?

You should always tune the algorithm with a validation set to obtain the necessary number of epochs, etc. If you want to truly train on the entire dataset, just do not specify a validation set. Probably in your case, just use a "short" validation set at the end of the time series. Make sure to train on multiple time series of which at least a few should contain the same kind of breakpoints you expect to encounter in the future (if you have a single one, traditional statistical methods might be a better choice).
