### ISSUE TITLE
Qusetion : order of group in processed input data?

### ISSUE THREAD

**Issue by dnwldnwl2** [jdb78/pytorch-forecasting#192]
i grouped my data with column name 'no'.

If i set .to_dataloader(shuffle=False), the order in x[group] is same with that of df['no'].unique()?

What i want is finding original data to debug model.

Is there something else I missed?

**Comment by jdb78** [comment]
You can use the [`x_to_index` method](https://pytorch-forecasting.readthedocs.io/en/latest/api/pytorch_forecasting.data.timeseries.TimeSeriesDataSet.html#pytorch_forecasting.data.timeseries.TimeSeriesDataSet.x_to_index). You might want to read [this section of the How to implement new model tutorial](https://pytorch-forecasting.readthedocs.io/en/latest/tutorials/building.html#Passing-data-to-a-model)

**Comment by dnwldnwl2** [comment]
Thank you for really quick reply! It works.
