### ISSUE TITLE
Question: Predict on unseen data - time varying variables known in advance

### ISSUE THREAD

**Issue by ganzinotti** [jdb78/pytorch-forecasting#194]
Great repository. I have a question about predicting on unseen data. I already looked at this gem of a notebook: https://github.com/jdb78/pytorch-forecasting/blob/master/docs/source/tutorials/stallion.ipynb

I however have doubts whether it is implemented correctly. More specifically these cells:

![image](https://user-images.githubusercontent.com/20625383/101757503-85acb500-3ad7-11eb-82d0-5a45972e2fb1.png)

What I am missing here is how the known time varying variables are incorporated. 

![image](https://user-images.githubusercontent.com/20625383/101757294-454d3700-3ad7-11eb-9cdb-3994ad971499.png)

Shouldn't these variables with the values be merged to this dataset... 

Please let me know what I am overlooking.

**Comment by jdb78** [comment]
Yes. The tutorial uses this as toy example and just adjusts the time index and month. We assume that special days and prices are the same as for the last data point. When building a real prediction engine, you should specify all known covariates. I omitted that in the tutorial for simplicity. Will add a disclaimer.

**Comment by ganzinotti** [comment]
Ok clear! Thank you for the quick answer and great work!
