### ISSUE TITLE
Example ar.py uses TemporalFusionTransformer instead of DeepAR

### ISSUE THREAD

**Issue by JustinNeumann** [jdb78/pytorch-forecasting#202]
Dear authors,

since the implementation of DeepAR works, you could also use it in the example (https://github.com/jdb78/pytorch-forecasting/blob/master/examples/ar.py).

Let me know if I can help.

Best
Justin

**Comment by jdb78** [comment]
Please give it a go! - Would be keen to merge such a PR. Generally speaking, the examples are not well-kept.

**Comment by JustinNeumann** [comment]
Solved through https://github.com/jdb78/pytorch-forecasting/pull/203
