### ISSUE TITLE
Predictions by grouping variable

### ISSUE THREAD

**Issue by athammad** [jdb78/pytorch-forecasting#208]
Hi @jdb78,

thank you very much for developing this wonderful library.

I have 3 questions:
1)The data in the Demand Forecasting example take the structure of a panel dataset with repeated observations over the time variable for each group, right?
2)the resulting prediction is the average predicted value over the grouping variables. Is this correct? ... I am not sure about it.
2) Let's say that I have on grouping variable only (let's call it `regions`) that takes 6 values (`A,B,C,D,E,F`). Can I get separated predictions for each region or do I have to run separated models for each one of them?

Cheers,
Ahmed

-

**Comment by jdb78** [comment]
Great to hear you like it!

1) yes correct
2) The prediction is for each observation - associated with a group - nothing is averaged
2) You will always get separate predictions.

It is probably best to use the [`predict()`](https://pytorch-forecasting.readthedocs.io/en/latest/api/pytorch_forecasting.models.base_model.BaseModel.html#pytorch_forecasting.models.base_model.BaseModel.predict) method. Its implementation (see the documentation for options) gives you fine-grained control over what exactly is returned.

**Comment by athammad** [comment]
Thank you for the clarification @jdb78 !! 
:+1:
