### ISSUE TITLE
 AssertionError: data index has to be unique

### ISSUE THREAD

**Issue by jbelisario** [jdb78/pytorch-forecasting#209]
PyTorch-Forecasting version: 0.6.1
PyTorch version: 1.4.0
Python version: 3.7.8
Operating System: Windows

### Expected behavior

Executed code in order to create a data loader object. Expected to get a data loader object. 

### Actual behavior

However, the result was: **AssertionError: data index has to be unique** 
I think it has to do with the fact that my dataset is comprised of multiple datasets that are conjoined. We are working with real estate data so let's say that each separate real estate market is 1 data frame consisting of ~30-40k rows. I have concatenated multiple real estate market data frames together in order to train the TFT model on all of these cities at one time. 

Could there be an issue stemming from adding the time_idx to those conjoined data frames? 

The property_id's for each property in the dataset are also unique. Could it be something regarding that unique id? 

### Code to reproduce the problem

```
max_prediction_length = 36
max_encoder_length = 60 
training_cutoff = data["time_idx"].max() - max_prediction_length

training = TimeSeriesDataSet(
    data[lambda x: x.time_idx <= training_cutoff],
    time_idx = col_def['time_idx'],
    target = col_def['target'], #Value
    group_ids = col_def['group_ids'], 
    #group_ids = ['PID'], 
    min_encoder_length=max_encoder_length // 2,  # keep encoder length long (as it is in the validation set)
    max_encoder_length=max_encoder_length,
    min_prediction_length=1,
    max_prediction_length=max_prediction_length,
    static_categoricals = col_def['static_categoricals'], 
    static_reals = col_def['static_reals'], 
    time_varying_known_categoricals = col_def['time_varying_known_categoricals'], 
    variable_groups = {},  # group of categorical variables can be treated as one variable
    time_varying_known_reals = col_def['time_varying_known_reals'], 
    time_varying_unknown_categoricals = [], 
    time_varying_unknown_reals = col_def['time_varying_unknown_reals'],
    target_normalizer=GroupNormalizer(
        groups = col_def['group_ids']
        #groups = ['PID'], coerce_positive=1.0
    ),  # use softplus with beta=1.0 and normalize by group
    add_relative_time_idx = True,
    add_target_scales = True,
    add_encoder_length = True,
)
```

If there was a crash, please include the traceback here.
![image](https://user-images.githubusercontent.com/24784133/102553118-575b4680-4090-11eb-9b77-774f266cf5ee.png)

**Comment by jdb78** [comment]
Could you try `pd.concat(list_of_df, ignore_index=True)`?

**Comment by tiago1405** [comment]
Hi jdb78,

I am partnering with jbelisario for this. After implementing you suggestion we now get an error: "ValueError: Input contains infinity or a value too large for dtype('float64')" (full traceback below). Investigating into this and making sure its not an issue in our datasets nor the joining of said datasets.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-19-f40638914491> in <module>
     31 
     32 # create validation set (predict=True) which means to predict the last max_prediction_length points in time for each series
---> 33 validation = TimeSeriesDataSet.from_dataset(training, data, predict = True, stop_randomization = True)
     34 
     35 # create dataloaders for model

/opt/conda/lib/python3.7/site-packages/pytorch_forecasting/data/timeseries.py in from_dataset(cls, dataset, data, stop_randomization, predict, **update_kwargs)
    725         """
    726         return cls.from_parameters(
--> 727             dataset.get_parameters(), data, stop_randomization=stop_randomization, predict=predict, **update_kwargs
    728         )
    729 

/opt/conda/lib/python3.7/site-packages/pytorch_forecasting/data/timeseries.py in from_parameters(cls, parameters, data, stop_randomization, predict, **update_kwargs)
    765         parameters.update(update_kwargs)
    766 
--> 767         new = cls(data, **parameters)
    768         return new
    769 

/opt/conda/lib/python3.7/site-packages/pytorch_forecasting/data/timeseries.py in __init__(self, data, time_idx, target, group_ids, weight, max_encoder_length, min_encoder_length, min_prediction_idx, min_prediction_length, max_prediction_length, static_categoricals, static_reals, time_varying_known_categoricals, time_varying_known_reals, time_varying_unknown_categoricals, time_varying_unknown_reals, variable_groups, dropout_categoricals, constant_fill_strategy, allow_missings, add_relative_time_idx, add_target_scales, add_encoder_length, target_normalizer, categorical_encoders, scalers, randomize_length, predict_mode)
    317 
    318         # preprocess data
--> 319         data = self._preprocess_data(data)
    320 
    321         # create index

/opt/conda/lib/python3.7/site-packages/pytorch_forecasting/data/timeseries.py in _preprocess_data(self, data)
    537                         self.scalers[name] = self.scalers[name].fit(data[[name]])
    538             if self.scalers[name] is not None and name != self.target:
--> 539                 data[name] = self.transform_values(name, data[name], data=data, inverse=False)
    540 
    541         # encode constant values

/opt/conda/lib/python3.7/site-packages/pytorch_forecasting/data/timeseries.py in transform_values(self, name, values, data, inverse, group_id)
    603                 else:
    604                     values = values.reshape(-1, 1)
--> 605                 return transform(values).reshape(-1)
    606 
    607         return values  # fallback

/opt/conda/lib/python3.7/site-packages/sklearn/preprocessing/_data.py in transform(self, X, copy)
    792                                 accept_sparse='csr', copy=copy,
    793                                 estimator=self, dtype=FLOAT_DTYPES,
--> 794                                 force_all_finite='allow-nan')
    795 
    796         if sparse.issparse(X):

/opt/conda/lib/python3.7/site-packages/sklearn/base.py in _validate_data(self, X, y, reset, validate_separately, **check_params)
    418                     f"requires y to be passed, but the target y is None."
    419                 )
--> 420             X = check_array(X, **check_params)
    421             out = X
    422         else:

/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py in inner_f(*args, **kwargs)
     70                           FutureWarning)
     71         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 72         return f(**kwargs)
     73     return inner_f
     74 

/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator)
    643         if force_all_finite:
    644             _assert_all_finite(array,
--> 645                                allow_nan=force_all_finite == 'allow-nan')
    646 
    647     if ensure_min_samples > 0:

/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py in _assert_all_finite(X, allow_nan, msg_dtype)
     97                     msg_err.format
     98                     (type_err,
---> 99                      msg_dtype if msg_dtype is not None else X.dtype)
    100             )
    101     # for object dtype data, we only check for NaNs (GH-13254)

ValueError: Input contains infinity or a value too large for dtype('float64').

**Comment by jbelisario** [comment]
@jdb78 just wanted to follow up on this.

**Comment by jdb78** [comment]
Can you check with the debugger which variable is affected and check the fitted scaler (`training.scalers[var_name].__dict__`)? I am rather sure that this issue is data-related. Probably either your fitted scale is incredibly small or there are infinite values directly in the dataset.

**Comment by jbelisario** [comment]
Fixed the issue. There was an infinite value that was simple to replace with data.replace([np.inf, -np.inf], np.nan, inplace=True).

Thank you for your help.
