### ISSUE TITLE
Question - TFT

### ISSUE THREAD

**Issue by fg1985** [jdb78/pytorch-forecasting#224]
Hi,

I'm probably missing something in the documentation but I can't understand how to generate predictions vector from a model I've created. 

Let's assume I created a TFT model, trained and validated it on a specific dataset (just like in the Stallion example).
Now I want to generate predictions for a new dataset and to store them alongside the real values for plotting/evaluation. 
For example, the output would be:
![image](https://user-images.githubusercontent.com/76685658/103207706-a8c4ca80-4907-11eb-99de-b2b9e108dc6a.png)

Just for clarification, I am succeeding to get a prediction for the last time_idx in a data_loader (using the model.predict method, what I'm looking for is a function that returns a vector of predictions for a range of timesteps in the data so, later on, I will be able to compare/plot/extract them in any manner I want.

How would I achieve that?

I have one more question, assuming the model is predicting the target at time_idx 5 at a certain point, the input values would be the features at time_idx-1 (and up to the encoder length) or beginning right from time_idx ?

Thank you!

**Comment by jdb78** [comment]
> Just for clarification, I am succeeding to get a prediction for the last time_idx in a data_loader (using the model.predict method, what I'm looking for is a function that returns a vector of predictions for a range of timesteps in the data so, later on, I will be able to compare/plot/extract them in any manner I want.

Important to understand is that we return predictions at multiple horizons. This essentially means that we can have multiple predictions for a single point in time as each prediction is related to a different forecasting horizon.

Here is a way to directly compare predictions to the original target. Depending on the use case you might prefer the dataframe created at line 5.
```python
# make predictions
res, index = tft.predict(validation, return_index=True)

# turn predictions into dataframe: time_idx is at horizon=0 (first prediction)
df = pd.DataFrame(res.numpy(), index=pd.MultiIndex.from_frame(index), columns=pd.RangeIndex(0, res.size(1), name="horizon"))

# change time_idx to correspond to each prediction
df = (
    df
    .stack()
    .reset_index(["time_idx", "horizon"])
    .assign(time_idx=lambda x: x.time_idx + x.horizon - 1)
    .set_index(["time_idx", "horizon"], append=True)[0]
    .unstack("horizon")
    .add_prefix("prediction_at_horizon_")
)

# add predictions to original dataframe
data.join(df, on=df.index.names)
```

> I have one more question, assuming the model is predicting the target at time_idx 5 at a certain point, the input values would be the features at time_idx-1 (and up to the encoder length) or beginning right from time_idx ?

The returned `time_idx` is the first time index of the decoder/prediction sequence, i.e. features for encoding are at `time_idx - encoder_length` to `time_idx -1` and the features for decoding are at `time_idx` to `time_idx + decoder_length -1`. The TFT uses not only features at the time of prediction but also a history of features.

**Comment by fg1985** [comment]
That was really helpful :) Thank you!
