### ISSUE TITLE
What does the `max_encoder_length` argument govern?  

### ISSUE THREAD

**Issue by kschmaus** [jdb78/pytorch-forecasting#232]
I am new to forecasting and sequence modeling, and I'm not 100% certain how to interpret the `max_encoder_length` argument in the `TimeSeriesDataSet` AND `TemporalFusionTransformer` objects. What does it govern? Or how should I interpret different values? Relatedly, I see the default for `TimeSeriesDataSet` is 30, but the default for `TemporalFusionTransformer` is 10; does one override the other? 

Thank you, 
Kyle

**Comment by jdb78** [comment]
It determines what the maximum length of the history from which a model will build features before forecasting/predicting/decoding. Yes. There is an override IF you initialize the TemporalFusionTransformer from a dataset (which is the recommended method).
