### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by binjiaqm** [jdb78/pytorch-forecasting#240]
I used the ar.py for testing. 

Number of parameters in network: 13.5k

  | Name                   | Type                   | Params
------------------------------------------------------------------
0 | loss                   | NormalDistributionLoss | 0
1 | logging_metrics        | ModuleList             | 0
2 | embeddings             | MultiEmbedding         | 1
3 | rnn                    | LSTM                   | 13.4 K
4 | distribution_projector | Linear                 | 66
------------------------------------------------------------------
13.5 K    Trainable params
0         Non-trainable params
13.5 K    Total params
Epoch 5: 100%|█| 33/33 [00:02<00:00, 11.05it/s, loss=3.3, v_num=0, val_loss=2.74, train_loss_step=2.76, train_loss_epoc
Traceback (most recent call last):
  File "ar.py", line 116, in <module>
    actuals = torch.cat([y for x, y in iter(val_dataloader)])
TypeError: expected Tensor as element 0 in argument 0, but got tuple

**Comment by jdb78** [comment]
`actuals = torch.cat([y for x, (y, weight) in iter(val_dataloader)])` fixes it. Has to to with the latest version that introduced a breaking change.
