### ISSUE TITLE
Question: sliding window for validation?

### ISSUE THREAD

**Issue by huayicodes** [jdb78/pytorch-forecasting#248]
Is it possible to do sliding window validation with TFT? Right now, the validation only includes a single period of max_prediction_length.

**Comment by jdb78** [comment]
Just do not use the `predict=True` keyword when initializing the validation dataset. It is just handy to get the last labels. You should, however, use then a `min_prediction_idx`.

**Comment by ikulyatin** [comment]
Show we also set stop_randomization to True in that case?

**Comment by LukeOliv** [comment]
So the min_prediction_idx refers to time_idx right?

Does it not get messed up when you have several group_ids? Or should you not reset time_idx between groups?

**Comment by jdb78** [comment]
You should set the time index as the data was recorded in the actual world. This will ensure your validation results are applicable in the real world. If you do not reset it between groups, you should not use the `min_prediction_idx` I guess. Otherwise, there should not be any issues.

**Comment by LukeOliv** [comment]
Thank you for the clarification, it really helps.
