### ISSUE TITLE
Order of "plot_prediction"

### ISSUE THREAD

**Issue by jiryang** [jdb78/pytorch-forecasting#256]
- PyTorch-Forecasting version: 0.7.1
- PyTorch version: 1.8.0
- Python version: 3.6.9
- Operating System: Ubuntu 18.04

### Expected behavior

Following the Demand forecasting w/ TFT tutorial, I executed code

for idx in range(10):  # plot 10 examples
    best_tft.plot_prediction(x, raw_predictions, idx=idx, add_loss_to_title=True);

and

for idx in range(10):  # plot 10 examples
    best_tft.plot_prediction(new_x, new_raw_predictions, idx=idx, show_future_observed=False);

in order to plot the validation and prediction results.

It works fine, but the plots seem to be in an order different from the original dataset (raw Pandas DataFrame or TimeSeriesDataSet).

Could I know how it is ordered? Or is there a way to print out certain data field into the plot, for example as its title?

**Comment by jdb78** [comment]
You can use the [`x_to_index`](https://pytorch-forecasting.readthedocs.io/en/latest/api/pytorch_forecasting.data.timeseries.TimeSeriesDataSet.html#pytorch_forecasting.data.timeseries.TimeSeriesDataSet.x_to_index) method to re-identify the data points.
