### ISSUE TITLE
MAPE metric issue

### ISSUE THREAD

**Issue by jbelisario** [jdb78/pytorch-forecasting#265]
- PyTorch-Forecasting version: 0.8.2
- PyTorch version: 1.7.0+cu101
- Python version: 3.6.9
- Operating System: Windows 

Just wanted to notify you that MAPE in the latest version might be calculated incorrectly. 

Also wanted to point out in the docs & code comments, MAPE & MAE are Mean Absolute. There's a typo listing those metrics as Mean Average...
![image](https://user-images.githubusercontent.com/24784133/104771325-1d896880-5740-11eb-88b2-f7a75b0f39ab.png)

Also as you can see the difference of how MAPE looks in previous versions of Pytorch Forecasting (on the right) vs. the most recent (on the left). The screenshot is from different runs logged in Weights & Biases.
![image](https://user-images.githubusercontent.com/24784133/104772540-9806b800-5741-11eb-97fd-42c8417e1f70.png)

**Comment by jdb78** [comment]
Great catch. Noticed as well that pytorch lightning adjusted the naming conventions. Will give it a look.

**Comment by jdb78** [comment]
The left side was the incorrect version. MAPE should never be optimized because outliers can drive it very high (what is happening here). There was an issue in 0.8.1 with target rescaling leading to the misleading small MAPE (but generally far worse results).
