### ISSUE TITLE
Question: Is there any way to access data loaders after saving a tft checkpoint?

### ISSUE THREAD

**Issue by dempseyryan** [jdb78/pytorch-forecasting#274]
- PyTorch-Forecasting version: 0.8.2
- PyTorch version: 1.7.1
- Python version: 3.7.6
- Operating System: Ubuntu 18.04

I'm looking to be able to load a tft from my directory and do analysis on it, as if I had started from scratch (i.e. I would have access to all the same variables that would normally be defined if I had just created the tft and trainer). My current understanding is that saving a tft with `trainer.save_checkpoint()` and loading with `TemporalFusionTransformer.load_from_checkpoint()` do not save the data loaders. However I want to be able to calculate error and such with the recommended method in the tutorial, i.e.:
```
# calculate mean absolute error on validation set
actuals = torch.cat([y[0] for x, y in iter(best_tft.val_dataloader())])
prediction, prediction_index = best_tft.predict(best_tft.val_dataloader(), mode='prediction', return_index=True, return_x=False)
(actuals - prediction).abs().mean()
```
My understanding is that this method ensures that the actuals correspond with the correct predictions (since it's not necessarily in the same order as the data frame from what I can tell?).

However, it seems that the dataloader properties get saved as None when saving the checkpoint.

### Expected behavior
When saving and loading a tft, I expect the dataloader properties to get saved in the file.

### Actual behavior

However, the dataloader properties are None when loaded from a .ckpt, as you can seen below.

### Code to reproduce the problem

```
tft.val_dataloader() == val_dataloader # make sure original dataloader property is as expected
True
```
```
trainer.save_checkpoint("test_checkpoint.ckpt")
test_tft = TemporalFusionTransformer.load_from_checkpoint("test_checkpoint.ckpt")
test_tft.val_dataloader() == val_dataloader # check if loading from checkpoint loaded the dataloader
False
```
```
print(test_tft.val_dataloader())
None
```
Is there any way around this? Or is there a better way of doing what I'm trying to do? Also please let me know if there's something I'm misunderstanding because I suspect part of what I'm saying is not accurate and causing my issue. Thanks so much.

(Here are some of the main commands to initialize the original model):
```
training = TimeSeriesDataSet(
    data[lambda x: x.time_idx <= training_cutoff],
    time_idx="time_idx",
    target="occupancy",
    group_ids=parameters,
    min_encoder_length=MIN_ENCODER_LENGTH,
    max_encoder_length=max_encoder_length,
    min_prediction_length=MIN_PREDICTION_LENGTH,
    max_prediction_length=max_prediction_length,
    static_categoricals=parameters,
    static_reals=[],
    time_varying_known_categoricals=[],
    variable_groups={},
    time_varying_known_reals=["time_idx"],
    time_varying_unknown_categoricals=[],
    time_varying_unknown_reals=["occupancy"],
    target_normalizer=GroupNormalizer(groups=parameters, transformation='relu'),
    add_relative_time_idx=True,
    add_target_scales=True,
    add_encoder_length=True,
)
```
```
# create validation set (predict=True) which means to predict the last max_prediction_length points in time
# for each series
validation = TimeSeriesDataSet.from_dataset(training, data, predict=True, stop_randomization=True)

# create dataloaders for model
train_dataloader = training.to_dataloader(train=True, batch_size=BATCH_SIZE, num_workers=NUM_WORKERS)
val_dataloader = validation.to_dataloader(train=False, batch_size=BATCH_SIZE * 10, num_workers=NUM_WORKERS)
```
```
trainer = pl.Trainer(
    max_epochs=30,
    gpus=1,
    weights_summary="top",
    gradient_clip_val=0.1,
    limit_train_batches=30,  # coment in for training, running valiation every 30 batches
    # fast_dev_run=True,  # comment in to check that networkor dataset has no serious bugs
    callbacks=[lr_logger, early_stop_callback],
    logger=logger,
)


tft = TemporalFusionTransformer.from_dataset(
    training,
    learning_rate=0.01,
    hidden_size=16,
    attention_head_size=1,
    dropout=0.1,
    hidden_continuous_size=8,
    output_size=7,  # 7 quantiles by default
    loss=QuantileLoss(),
    log_interval=10,  # uncomment for learning rate finder and otherwise, e.g. to 10 for logging every 10 batches
    reduce_on_plateau_patience=4,
)
print(f"Number of parameters in network: {tft.size()/1e3:.1f}k")

# fit network
trainer.fit(
    tft,
    train_dataloader=train_dataloader,
    val_dataloaders=val_dataloader,
)
```

**Comment by jdb78** [comment]
You could save the datasets with [`.save`](https://pytorch-forecasting.readthedocs.io/en/latest/api/pytorch_forecasting.data.timeseries.TimeSeriesDataSet.html#pytorch_forecasting.data.timeseries.TimeSeriesDataSet.save) and then reconvert them to dataloaders when you want to continue training.

**Comment by dempseyryan** [comment]
Awesome, exactly what I was looking for. Thank you!
