### ISSUE TITLE
How to Offline install  PyTorch-Forecasting ?

### ISSUE THREAD

**Issue by 2017wxyzwxyz** [jdb78/pytorch-forecasting#278]
How to Offline install  PyTorch-Forecasting ?

Because online installation always fails.

**Comment by LukeOliv** [comment]
From the main page, under Releases you can find the packages. Latest is https://github.com/jdb78/pytorch-forecasting/archive/v0.8.2.zip

**Comment by jdb78** [comment]
Or you download the wheel directly from PyPI (https://pypi.org/project/pytorch-forecasting/#files) and pip install it (https://stackoverflow.com/questions/28002897/wheel-file-installation)

**Comment by 2017wxyzwxyz** [comment]
According to the instructions, my problem has been solved, thank you !  But I'd like to know Can PyTorch-Forecasting predict (pure)signal data?  i.e.  question 378.
