### ISSUE TITLE
How can I restrict the range of valid data?

### ISSUE THREAD

**Issue by dempseyryan** [jdb78/pytorch-forecasting#281]
- PyTorch-Forecasting version: 0.8.2
- PyTorch version: 1.7.1
- Python version: 3.7.6
- Operating System: Ubuntu 18.04

My target values should be restricted between 0 and 1, as they are proportions. Sometimes the network predicts values >1 or <0, I assume because the loss is smaller in some cases.

To fix this, I would like to apply sigmoid activation function to the very last layer in order to force the predictions to be in (0, 1). I couldn't find anything for activation function in the source code or docs, but I did find "output_transformer." Is this the right parameter? What I did was set this equal to torch's implementation of sigmoid but this doesn't seem to work. There are a few different versions below.

### Expected behavior

I applied sigmoid as the output transformer for the tft, hoping this would make the network output be fed into sigmoid each time before calculating errors.

### Actual behavior

However, in the case of the sigmoid function, this doesn't work because it requires a Tensor, but Forecasting seems to call it with a dict (I had a look at the source code, I guess this is the 'out' var that it is inputting?).

In the case of the sigmoid method, it seems to also expect some sort of tensor.

Then I figured I might need to use a normalizer, so I used TorchNormalizer with sigmoid as the transform (and defined logit as its inverse). That seems to introduce a whole other problem.

### Code to reproduce the problem

```
tft = TemporalFusionTransformer.from_dataset(
    training,
    learning_rate=0.01,
    hidden_size=16,
    attention_head_size=1,
    dropout=0.1,
    hidden_continuous_size=8,
    output_size=7,  # 7 quantiles by default
    loss=QuantileLoss(),
    log_interval=10,  # uncomment for learning rate finder and otherwise, e.g. to 10 for logging every 10 batches
    reduce_on_plateau_patience=4,
    output_transformer=torch.sigmoid,
#    output_transformer=torch.Tensor.sigmoid,
#    output_transformer=TorchNormalizer(center=False, transformation=(torch.sigmoid, torch.logit))

)


# fit network
trainer.fit(
    tft,
    train_dataloader=train_dataloader,
    val_dataloaders=val_dataloader,
)
```
### Output for torch.sigmoid
```
TypeError: sigmoid(): argument 'input' (position 1) must be Tensor, not dict
```
### Output for torch.Tensor.sigmoid
```
TypeError: descriptor 'sigmoid' requires a 'torch._C._TensorBase' object but received a 'dict'
```
### Output for TorchNormalizer()
```
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

Is there a way to do what I have in mind? I.e. teach the model that a specific range of data ((0, 1) in my case) is acceptable? I'm sure I'm missing something from the docs and/or going about this the wrong way. Any ideas?

Thanks again,
Ryan

Edit: I also just noticed the existence of this output_layer property. I tried overwriting it from Linear in a similar way to the source code, except that Sigmoid doesn't seem to take positional arguments:
```
tft.output_layer = torch.nn.Sigmoid()
```
Will update soon.

And here is the main code that initialized the Time Series:

```
### Create the trainer instance

max_prediction_length = VALIDATION_LENGTH
max_encoder_length = MAX_ENCODER_LENGTH 

training_cutoff = data["time_idx"].max() - max_prediction_length # which hour value to stop training
parameters = list(data.columns[:3])

warnings.simplefilter(action='ignore', category=FutureWarning) # ignore false positives

training = TimeSeriesDataSet(
    data[lambda x: x.time_idx <= training_cutoff],
    time_idx="time_idx",
    target="occupancy",
#     group_ids=parameters,
    group_ids=[parameters[0]],
    min_encoder_length=MIN_ENCODER_LENGTH,
    max_encoder_length=max_encoder_length,
    min_prediction_length=MIN_PREDICTION_LENGTH,
    max_prediction_length=max_prediction_length,
#     static_categoricals=parameters,
    static_categoricals=[parameters[0]],
#     static_reals=[],
    static_reals=parameters[1:3],
    time_varying_known_categoricals=[],
    variable_groups={},
    time_varying_known_reals=["time_idx"],
    time_varying_unknown_categoricals=[],
    time_varying_unknown_reals=["occupancy"],
    target_normalizer=GroupNormalizer(groups=[parameters[0]], transformation=None),
#     target_normalizer=GroupNormalizer(
#         groups=parameters,
#         transformation=(torch.sigmoid, torch.logit),
#     ),
#     target_normalizer=EncoderNormalizer(transformation=(torch.sigmoid, torch.logit), center=False),
#     target_normalizer=None,
    add_relative_time_idx=True,
    add_target_scales=True,
    add_encoder_length=True,
)

# create validation set (predict=True) which means to predict the last max_prediction_length points in time
# for each series
validation = TimeSeriesDataSet.from_dataset(training, data, predict=True, stop_randomization=True)

# create dataloaders for model
train_dataloader = training.to_dataloader(train=True, batch_size=BATCH_SIZE, num_workers=NUM_WORKERS)
val_dataloader = validation.to_dataloader(train=False, batch_size=BATCH_SIZE * 10, num_workers=NUM_WORKERS)
warnings.simplefilter(action='default', category=FutureWarning)
```

**Comment by ML-IEE** [comment]
Hello @dempseyryan, 

I am currently working on a similar problem and was sad to see that your post is closed. Could you maybe elaborate, if you were able to fix the logit-transformation problem ?

**Comment by dempseyryan** [comment]
@ML-IEE hello, the way I ended up fixing this was by creating a subclass that inherits from TemporalFusionTransformer and overriding the output_layer attribute in the __init__ constructor, like so:

```
self.output_layer = torch.nn.Sequential(
    OrderedDict(
        [
            ("linear", self.output_layer), # original un-activated output, originally just linear
            ("output", torch.nn.Sigmoid()) # new activation function
        ]
    )
)
```
(Before doing this, I call the `super().__init__()` with all the arguments passed to make sure that everything else is the same).

Now whenever a class method is called, such as `.from_dataset()` it knows that the output_layer actually has a sigmoid activation, and so the state dicts and all that are configured properly.

This should work for any activation function you desire on the output layer.

Hope that helps.

**Comment by ML-IEE** [comment]
Hi @dempseyryan,

thank you very much, this helps a lot.
