### ISSUE TITLE
Additional columns added to "data" after calling "TimeSeriesDataSet.from_dataset"

### ISSUE THREAD

**Issue by huayicodes** [jdb78/pytorch-forecasting#283]
- PyTorch-Forecasting version: 0.8.2
- PyTorch version: 1.7.1
- Python version: 3.8.5
- Operating System: Windows 10

### Expected behavior

When running `validation = TimeSeriesDataSet.from_dataset(training, data, predict=True, stop_randomization=True)`, `data` is not supposed to change. 

### Actual behavior
The columns `'relative_time_idx', 'encoder_length'` are added to `data`

### Code to reproduce the problem

Code in the tutorial works. 

### Additional information

This problem is not present in version 0.7.1. Not sure about intermediate versions.

**Comment by huayicodes** [comment]
Same issues after calling `raw_predictions, x, index  = tft.predict(data, mode="raw", return_x= True, return_index = True)`

**Comment by huayicodes** [comment]
Change `data` to 'data.copy()' at 
https://github.com/jdb78/pytorch-forecasting/blob/master/pytorch_forecasting/data/timeseries.py#L1136
seem to resolve the issue.

**Comment by jdb78** [comment]
This is fixed in the current master which will be released shortly
