### ISSUE TITLE
Prediction results differ depending on amount of timeseries passed into the dataset

### ISSUE THREAD

**Issue by huayicodes** [jdb78/pytorch-forecasting#284]
PyTorch-Forecasting version: 0.8.2
PyTorch version: 1.7.1
Python version: 3.8.5
Operating System: Windows 10

### Expected behavior

Expect to get the same prediction for the same timeseries either when one timeseries is passed into ` tft.predict(data_one_timeseries)` or when multiples are passed into the function together , i.e. tft.predict(data_multiple_timeseries)` 

### Actual behavior

The prediction for the same timeseries differs depending on what other timeseries are passed together. 

### Code to reproduce the problem

Code from the tutorial works. To check, do something like below, and the two plots look pretty different!
```
# Single timeseries 
raw_predictions, x, index  = tft.predict(data[(data.sku == 'SKU_02')&(data.agency == 'Agency_22')], mode="raw", return_x= True, return_index = True)
tft.plot_prediction(x, raw_predictions, idx=0, add_loss_to_title=True)    

# All timeseries
raw_predictions, x, index  = tft.predict(data, mode="raw", return_x= True, return_index = True)
idx = index[(index.sku == 'SKU_02') & (index.agency ==  'Agency_22')].index
tft.plot_prediction(x, raw_predictions, idx=idx, add_loss_to_title=True)    
```
### Addtional information
Version 0.7.1 doesn't have this problem 

Paste the command(s) you ran and the output. Including a link to a colab notebook will speed up issue resolution.
If there was a crash, please include the traceback here.
The code used to initialize the TimeSeriesDataSet and model should be also included.

**Comment by huayicodes** [comment]
My temporary fix:
change the lines here  https://github.com/jdb78/pytorch-forecasting/blob/master/pytorch_forecasting/data/timeseries.py#L633
to 
``` for name, group_name in self._group_ids_mapping.items():
            transformer = self.get_transformer(name)
            if not self.predict_mode:
               # when generating a new dataset for training 
                transformer = NaNLabelEncoder().fit(data[name].to_numpy().reshape(-1))
            self.categorical_encoders[group_name] = transformer
            data[group_name] = self.transform_values(name, data[name], inverse=False, group_id=True)```

**Comment by jdb78** [comment]
Ah. This is a really good catch. The issue is that the group ids are used when getting the target scale from the group normalizer.
A fix would be to add categories to the existing ones. This essentially requires a change in the NaNLabelEncoder.
