### ISSUE TITLE
How long should the encoder and decoder/prediction length be?

### ISSUE THREAD

**Issue by bingblackbean** [jdb78/pytorch-forecasting#287]
as I check the FAQ about How long should the encoder and decoder/prediction length be in the link: https://pytorch-forecasting.readthedocs.io/en/latest/faq.html
it suggests that  **not much longer than 500 for the encoder length and 200 for the decoder length**

why the exact number 500 and 200 are proposed here? are they hardcoded anyhow?

**Comment by jdb78** [comment]
Those are just rough guidelines because of memory limits. You can of course beyond that but I would assume that downsampling is more efficient.

**Comment by bingblackbean** [comment]
Thanks for clarifying. It is clear to me now.
