### ISSUE TITLE
How to test whether pytorch forecasting is successfully installed ?

### ISSUE THREAD

**Issue by 2017wxyzwxyz** [jdb78/pytorch-forecasting#293]
- PyTorch-Forecasting version:
- PyTorch version:
- Python version:
- Operating System:

### Expected behavior

I executed code ... in order to ... and expected to get result ...

### Actual behavior

However, result was .... I think it has to do with ... because of ...

### Code to reproduce the problem

```

```

Paste the command(s) you ran and the output. Including a link to a colab notebook will speed up issue resolution.
If there was a crash, please include the traceback here.
The code used to initialize the TimeSeriesDataSet and model should be also included.

**Comment by jdb78** [comment]
You could just try `import pytorch_forecasting`

**Comment by 2017wxyzwxyz** [comment]
thanks1

**Comment by 2017wxyzwxyz** [comment]
thanks!
