### ISSUE TITLE
[TFT] AssertionError: relative_time_idx is a protected column and must not be present in data

### ISSUE THREAD

**Issue by jiryang** [jdb78/pytorch-forecasting#301]
- PyTorch-Forecasting version: 0.8.2
- PyTorch version: 1.8.0
- Python version: 3.6.9
- Operating System: Ubuntu 18.04

Tutorial produces this error:
>> AssertionError: relative_time_idx is a protected column and must not be present in data

Not sure whether this occurred before I upgrade PyTorch-Forecasting version to latest.
Could someone please take a look?

**Comment by jdb78** [comment]
This is fixed in the current master.
