### ISSUE TITLE
ModuleAttributeError: 'QuantileLoss' object has no attribute 'metrics'

### ISSUE THREAD

**Issue by turmeric-blend** [jdb78/pytorch-forecasting#307]
from the [tutorial](https://pytorch-forecasting.readthedocs.io/en/stable/tutorials/stallion.html), I am trying out the multi-target architecture, I add a `target` and removed `target_normalizer`

```
training = TimeSeriesDataSet(
    data[lambda x: x.time_idx <= training_cutoff],
    time_idx="time_idx",
    target=["volume", "log_volume"],      <------------------------------ added target
    group_ids=["agency", "sku"],
    min_encoder_length=max_encoder_length // 2,  # keep encoder length long (as it is in the validation set)
    max_encoder_length=max_encoder_length,
    min_prediction_length=1,
    max_prediction_length=max_prediction_length,
    static_categoricals=["agency", "sku"],
    static_reals=["avg_population_2017", "avg_yearly_household_income_2017"],
    time_varying_known_categoricals=["special_days", "month"],
    variable_groups={"special_days": special_days},  # group of categorical variables can be treated as one variable
    time_varying_known_reals=["time_idx", "price_regular", "discount_in_percent"],
    time_varying_unknown_categoricals=[],
    time_varying_unknown_reals=[
        "volume",
        "log_volume",
        "industry_volume",
        "soda_volume",
        "avg_max_temp",
        "avg_volume_by_agency",
        "avg_volume_by_sku",
    ],
#     target_normalizer=GroupNormalizer(         <------------------------------ removed target_normalizer
#         groups=["agency", "sku"], transformation="softplus"
#     ),  # use softplus and normalize by group
    add_relative_time_idx=True,
    add_target_scales=True,
    add_encoder_length=True,
)
```

When running this part:

```
tft = TemporalFusionTransformer.from_dataset(
    training,
    # not meaningful for finding the learning rate but otherwise very important
    learning_rate=0.03,
    hidden_size=11,  # most important hyperparameter apart from learning rate
    # number of attention heads. Set to up to 4 for large datasets
    attention_head_size=1,
    dropout=0.1,  # between 0.1 and 0.3 are good values
    hidden_continuous_size=8,  # set to <= hidden_size
    output_size=7,  # 7 quantiles by default
    loss=QuantileLoss(),
    # reduce learning rate if no improvement in validation loss after x epochs
    reduce_on_plateau_patience=4,
)
```

I get error:

> ModuleAttributeError: 'QuantileLoss' object has no attribute 'metrics'

which I believe is from [here](https://github.com/jdb78/pytorch-forecasting/blob/fa2663f4dfd7223636dc2ec6a665916931669986/pytorch_forecasting/models/temporal_fusion_transformer/__init__.py#L364)

**Comment by jdb78** [comment]
You need to use a [`MultiLoss`](https://pytorch-forecasting.readthedocs.io/en/latest/api/pytorch_forecasting.metrics.MultiLoss.html). Same for using a [`MultiNormalizer`](https://pytorch-forecasting.readthedocs.io/en/latest/api/pytorch_forecasting.data.encoders.MultiNormalizer.html#pytorch_forecasting.data.encoders.MultiNormalizer).

**Comment by turmeric-blend** [comment]
I also realised that there are other params that need to be different to run `TemporalFusionTransformer` as multi-target. Instead of me asking one by one when I run into the issue, maybe you could put up a simple example to run it as multi-target? When you're free of course. Thank you. :)

**Comment by jdb78** [comment]
This might be helpful: https://pytorch-forecasting.readthedocs.io/en/latest/tutorials/building.html#Predicting-multiple-targets-at-the-same-time. Probably a couple of additional checks giving better error message would be helpful.

**Comment by turmeric-blend** [comment]
My bad I missed that part of the docs. Everything works now.

Also apparently output_size has to be a list where number of elements equal to number of target like `TemporalFusionTransformer.from_dataset(..., output_size=[7, 7], ...)`, this was not in the docs :/
