### ISSUE TITLE
How to properly format data and TimeSeriesDataSet for multi-asset forecasting?

### ISSUE THREAD

**Issue by hjh27** [jdb78/pytorch-forecasting#308]
I am trying out multi-asset forecasting. From the examples, I first tried to format my data as follows:

```
time_idx | date | asset | price
0 | 2018-01-01 | A | 5.5
0 | 2018-01-01 | B | 6.7
0 | 2018-01-01 | C | 8.9
1 | 2018-01-02 | A | 6.5
1 | 2018-01-02 | B | 7.7
1 | 2018-01-02 | C | 9.9
2 | 2018-01-03 | A | 7.5
2 | 2018-01-03 | B | 8.7
2 | 2018-01-03 | C | 10.9
```
In this case the `TimeSeriesDataSet` definition would have `group_ids=["asset"]` and `target=["price"]`. However, this does not seem right as it won't be forecasting for individual assets.

So I try to format my data like this instead:

```
time_idx | date | asset A | asset B | asset C
0 | 2018-01-01 | 5.5 | 6.7 | 8.9
1 | 2018-01-02 | 6.5 | 7.7 | 9.9
2 | 2018-01-03 | 7.5 | 8.7 | 10.9
```
and for the `TimeSeriesDataSet` definition, `target=["asset A", "asset B", "asset C"]`. But what is the `group_ids` in this case?

Or is there a better way to format the data for multi-asset forecasting?

**Comment by jdb78** [comment]
Both approaches are valid but the first one is more common and scalable. For the second one you can add a constant column for the groupid. Pros and cons

1. The first approach will not directly learn react to movements in asset A if you are forecasting for asset B, e.g. the model will not learn that if asset A moves up that this is some early signal for asset B to move up as well. However, it will learn form asset B how to better forecast asset A.
2. You are creating more parameters in the network to learn. This approach will also not scale well beyond ~10 assets for most algorithms. I am planning on the a flow transformer that can do this more efficiently (and requires the first format).

**Comment by hjh27** [comment]
1. For the first approach, it can only forecast **one** asset at a time, right? Doesn't this defeat the purpose of multi-asset forecasting?

2. Will this flow transformer be able to forecast **multiple** assets in a single forward pass?

**Comment by jdb78** [comment]
1. Correct, you only forecast one asset at a time. You learn how to make a good forecast for this one asset from other assets.
2. I believe yes. This is a very active field of research and it is anything but trivial for an algorithm to capture inter time series dependencies. It has also its scalability limits as each training example has to consist of all time series.
