### ISSUE TITLE
TemporalFusionTransformer losses

### ISSUE THREAD

**Issue by lorenzo-caruso** [jdb78/pytorch-forecasting#309]
Hi, can I use a loss different from Quantile with TFT? Because with any other loss it gives me an assertion error about shape of predictions.
Thanks, Lorenzo

**Comment by jdb78** [comment]
Could you post your error and the code that creates it?

**Comment by rahimBK** [comment]
From my understanding, you have to change the output size to match the expected output of your loss. 
If you follow the tutorial with the Quantile loss, the parameter output_size is set to 7 (default number of quantiles) in TemporalFusionTransformer.from_dataset() method. 
To use the RMSE() for example you need to set output_size=1 and loss=RMSE().
From the tutorial : 
```
tft = TemporalFusionTransformer.from_dataset(
    training,
    learning_rate=0.03,
    hidden_size=16,  # most important hyperparameter apart from learning rate
    # number of attention heads. Set to up to 4 for large datasets
    attention_head_size=1,
    dropout=0.1,  # between 0.1 and 0.3 are good values
    hidden_continuous_size=8,  # set to <= hidden_size
    output_size=1,  # Change here from 7
    loss=RMSE(),  # changer here from QuantileLoss
    # reduce learning rate if no improvement in validation loss after x epochs
    reduce_on_plateau_patience=4,
)
```
Don't forget to import RMSE
```
from pytorch_forecasting.metrics import RMSE
```
Hope this helps

**Comment by domplexity** [comment]
hi @rahimBK ,
any idea what the output_size should be for NegativeBinomialDistributionLoss ? neither 7 (default number of quantiles) nor 2 (number of parameters of negative binomial distribution) worked for me. 

`RuntimeError: selected number k out of range`

**Comment by jdb78** [comment]
Currently, the temporal fusion transformer does not work with distribution losses. Would be a great addition to the library to enable them!

**Comment by domplexity** [comment]
understood. will look into it

**Comment by domplexity** [comment]
So essentially it seems to be fully implemented with just some minor issues

- to_quantiles is causing an error, but I dont see why this should only occur in the context of a TFT as this part does not really depend on the network architecture used
  - this is triggered during training (log creates a plot, which in turn creates quantiles - and fails). deactivate this plot in log and training looks good
- training generates proper n, p as it seems
- trained model can generate predictions (of n, p)
- tft.loss.sample(raw['predictions'], N) converts these two target value predictions

What remains is a fix of the to_quantiles

- it remains a bit unclear as to whether this should be quantiles for the predictions of the NegBin parameters (n, p) or rather quantiles for the target values (I assume/prefer the latter for the sake of consistency and as uncertainty is encapsulated in these parameters already)
- that leaves us with two options:
  - generate samples and calculate quantiles from these
  - obtain quantiles analytically from the CDF, but .cdf is not implemented on torch.distributions.NegativeBinomial. i suggest to go for the sampling version.

What do you say?

**Comment by lorenzo-caruso** [comment]
Thank you very much! This is what I was looking for!
