### ISSUE TITLE
Problem when using MultiLoss

### ISSUE THREAD

**Issue by hanskasan** [jdb78/pytorch-forecasting#310]
Hi,

We are trying to use the multi-target (2 targets) prediction using TFT.

We set the loss to be calculated as follows:
loss = MultiLoss(QuantileLoss(), QuantileLoss())

However, when we run the hyperparameter optimization (using Optuna), we get this error:
ModuleAttributeError: 'QuantileLoss' object has no attribute 'metrics'

Are there any suggestions that you can give us regarding this error?

Thanks :)

**Comment by jdb78** [comment]
Can you post the code to reproduce the issue?

**Comment by hanskasan** [comment]
Sure.

We tried to use Temporal Fusion Transformer as our model. The loss is defined using MultiLoss().


`tft = TemporalFusionTransformer.from_dataset( 
    training,
    learning_rate=0.03,
    hidden_size=128,
    attention_head_size=1,
    dropout=0.1,
    hidden_continuous_size=8,
    output_size=[7,7],
    loss=MultiLoss([QuantileLoss(), QuantileLoss()]),
    log_interval=10,
    reduce_on_plateau_patience=4,
)`

The hyperparameter optimization is done as follows:
`study = optimize_hyperparameters(
    train_dataloader,
    val_dataloader,
    model_path="optuna_test",
    n_trials=5,
    max_epochs=50,
    gradient_clip_val_range=(0.01, 1.0),
    hidden_size_range=(8, 128),
    hidden_continuous_size_range=(8, 128),
    attention_head_size_range=(1, 4),
    learning_rate_range=(0.001, 0.1),
    dropout_range=(0.1, 0.3),
    trainer_kwargs=dict(limit_train_batches=30),
    reduce_on_plateau_patience=4,
    use_learning_rate_finder=False,
)`

Can you please also inform us if there is any example or tutorial on how to use multi target prediction, especially about how to handle loss function in multi-target cases?

Thanks!

**Comment by jdb78** [comment]
Could you add the definition of the dataset? Have you tried with version 0.8.3 which provides better error messages?

**Comment by JakeForsey** [comment]
I suspect this was resolved by https://github.com/jdb78/pytorch-forecasting/pull/328!
