### ISSUE TITLE
Using other groups as unknown input values

### ISSUE THREAD

**Issue by vakker** [jdb78/pytorch-forecasting#316]
- PyTorch-Forecasting version: 0.8.2
- PyTorch version: 1.7.1

Using information from different groups could be useful, e.g. if you have temperature data from 10 cities, then they would go into 10 groups (if I understand it correctly), but it might help to predict the temperature in certain cities based on the temperature in other cities.

Is this possible at the moment? The only way I can think of is to explicitly include each group as a column, e.g. `t-0`, `t-1` and just have a `target` that corresponds to the row's `groups_id`, essentially duplicating the columns for each group like:
| idx | t-0 | t-1 | target | group |
| -:| -:| -:| -:| -:|
| 0 | 10 | 11 | 10 | 0 |
| 1 | 9 | 10 | 9 | 0 |
| 0 | 10 | 11 | 11 | 1 |
| 1 | 9 | 10 | 10 | 1 |

**Comment by jdb78** [comment]
Yes. This is not possible at the moment. Actually, this is a very interesting problem generally in time series forecasting and very difficult to solve. I am currently implementing the temporal flow transformer (#238). Another approach is Graph DeepFactors (see #128) or DeepFactors. You are very welcome to implementing it. If you are talking about temperature data, I wonder if a convolutional model would be the better fit so you explicitly model spatial dependencies.

**Comment by vakker** [comment]
Thanks, I'll take a deeper look on those models.
I worked with GNNs before, I could work on the Graph DeepFactors.
Would that be ok to use external libraries, e.g. [Pytorch Geometric](https://github.com/rusty1s/pytorch_geometric)? 

Thanks for your suggestion for using the spatial bias. Actually, that was just a simple example, I'm working with financial data at the moment, so using a set of stock prices together was my original idea.

**Comment by jdb78** [comment]
Sure, PyTorch geometric is a good idea. We should make is an extra dependency so that it is only installed if the model is required by users, i.e.
`pip install pytorch-forecasting[graphs]` would be the install command. Happy to help changing poetry config if you feel this is difficult.
