### ISSUE TITLE
The predict function concatenates the outputs which leads to GPU OOM for large datasets

### ISSUE THREAD

**Issue by vakker** [jdb78/pytorch-forecasting#322]
- PyTorch-Forecasting version: 0.8.2
- PyTorch version: 1.7.1

### Expected behavior
I should be able to loop through a large dataset with `predict` and not run out of memory.

### Actual behavior
If I have a large validation set that I want to go through after the training, then it causes a GPU OOM error, because all the outputs are stored on the GPU and not transferred back to the GPU.

So moving the outputs to CPU or converting them to numpy inside `predict` during the iterations might be a better way, or allow a method that accepts the batches directly (instead of a dataset, dataloader or dataframe).

E.g. somewhere around [here](https://github.com/jdb78/pytorch-forecasting/blob/master/pytorch_forecasting/models/base_model.py#L867) use `out.cpu()` or something similar.

### Code to reproduce the problem
```
# create large dataset
# create data loader (or just use the ds directly)
raw_predictions, x = ptf_module.predict(val_dl, mode="raw", return_x=True)
```

Edit:
Actually `out` is a dictionary, so:
```
for k in out:
    out[k] = out[k].cpu().detach()
```

**Comment by jdb78** [comment]
That is a good point. Will add a device keyword in the predict method.

**Comment by vakker** [comment]
Or it could also help to have a separate method that accepts the tensors returned by the dataloader iterator (or `dataset.__getitem__`), and not a dataset/dataloader/dataframe.

The usecase is that I want to spot check part of the validation set, and with small datasets it was fine to pass the whole dataset to predict and plot specific indices from the returned predictions, but with a large dataset I run into the above mentioned problem.

A workaround that I'm using at the moment is this:
```
# data is the training dataframe
raw_predictions, x = ptf_module.predict(data[:idx], mode="raw", return_x=True)
```
when the daraframe is converted to the dataset, it only uses the last sample because of the `predict=True` flag, so essentially I get the prediction at `idx`.

**Comment by jdb78** [comment]
Hm. Essentially, you are are asking for a way to filter the dataset. That could be indeed useful. One can already manually modify the index but that is probably a bit cumbersome.
