### ISSUE TITLE
[QUESTION] metrics.MASE() API usage

### ISSUE THREAD

**Issue by pnmartinez** [jdb78/pytorch-forecasting#323]
Hi,

I've trying to **use `MASE()`** to do a single evaluation of the model. 

Being in the same module as `SMAPE()`, I would guess its usage is similar, so I instead of:

```
actuals = torch.cat([y[0] for x, y in iter(val_dataloader)])
baseline_predictions = Baseline().predict(val_dataloader)
SMAPE()(baseline_predictions, actuals)
```

I replaced the last line with:

```
In []: MASE()(baseline_predictions, actuals)
```
```
Out []: TypeError: update() missing 1 required positional argument: 'encoder_target'
```

May you give us a **usage example**? 

_Note_: I would guess the expected value for a Baseline model on MASE is, well, `1`.

**Comment by jdb78** [comment]
Most metrics are ok with only decoder predictions and corresponding decoder targets. MASE also needs targets from the encoder.

**Comment by jdb78** [comment]
Try this:

```python
actuals = torch.cat([y for _, (y, _) in dl], dim=0)
y_hat, x = Baseline().predict(dl, return_x=True)
MASE()(y_hat, actuals, x["encoder_target"], x["encoder_lengths"])
```

**Comment by pnmartinez** [comment]
Hi again @jdb78 ,

That works indeed! However, I was obtaining **MASE values greater than 1**. By definition, a **naive approach** would render `MASE=1` ([wikipedia](https://en.wikipedia.org/wiki/Mean_absolute_scaled_error#Rationale)).

Digging into the baseline model, I now understand why this is not the case. The library is not using exactly the naive approach, because of the baseline prediction returning a _multi-step_ and _not autoregressive_ prediction. That means the _last known value_ is used as a forecast for the __whole prediction period__, which obviously is very different from the naive approach.

From the `Baseline()` on the library:

![imagen](https://user-images.githubusercontent.com/29891887/107219463-6962c100-6a11-11eb-84ff-86caad53579b.png)

How the pure "naive approach" would look:

![imagen](https://user-images.githubusercontent.com/29891887/107219894-fb6ac980-6a11-11eb-898f-a6c8e4cc0e6b.png)

I think adding the naive approach would be an interesting feature to enrich model benchmarking. The logic is not that hard (shifting one row), and I have it somewhere. If I have the time, I will open a PR next week.
