### ISSUE TITLE
What is the recommended method to separate test data from validation data?

### ISSUE THREAD

**Issue by dempseyryan** [jdb78/pytorch-forecasting#324]
- PyTorch-Forecasting version: 0.8.3
- PyTorch version: 1.7.1
- Python version: 3.7.6
- Operating System: Ubuntu 18.04

I have a DataFrame 'data', containing hourly samples which I would like to model. I would like the last x hours to be reserved for comparing predictions on the fully fit model, and the x hours before that to be used for validation during training. I have looked at the tutorial for predicting unseen data, but I'm trying to find a simpler way since the test set is contiguous with the rest of the data.

### Expected behavior

I initialized another TimeSeriesDataSet and dataloader to include both the validation set and test set, and did the usual way of predicting on that. I wanted to see the predicted values for both the validation and test sets, i.e. the predictions for the last 2x hours.

```
test_and_val = TimeSeriesDataSet.from_dataset(training, data, min_prediction_idx=training.index.time.max() + 1, stop_randomization=True)

test_dataloader = test_and_val.to_dataloader(train=False, batch_size=BATCH_SIZE * 4, num_workers=NUM_WORKERS)

actual_test = torch.cat([y[0] for x, y in iter(test_dataloader)])
new_predictions, pred_idx = best_tft.predict(test_dataloader, mode='prediction', return_index=True, return_x=False)
(actual_test - new_predictions).abs().mean()

```
What I did differently was that when I initialized the validation set (before training) instead of inputting data, I inputted data <= test cutoff, as below. The training was initialized the 'typical' way I think.

```
max_prediction_length = VALIDATION_LENGTH + TEST_LENGTH # Number of hours NOT shown to network

training_cutoff = data["time_idx"].max() - max_prediction_length # which hour value to stop training
parameters = data.columns[:3].tolist()

max_prediction_length -= TEST_LENGTH # Only predict val length out of val set
warnings.simplefilter(action='ignore', category=FutureWarning) # ignore false positives

## Create training dataset
training = TimeSeriesDataSet(
    data[lambda x: x.time_idx <= training_cutoff],
    time_idx="time_idx",
    target="occupancy",
#     group_ids=parameters,
    group_ids=[parameters[0]],
    min_encoder_length=MIN_ENCODER_LENGTH,
    max_encoder_length=MAX_ENCODER_LENGTH,
    min_prediction_length=MIN_PREDICTION_LENGTH,
    max_prediction_length=max_prediction_length,
    static_categoricals=[parameters[0]],
    static_reals=parameters[1:3],
    time_varying_known_categoricals=[],
    variable_groups={},
    time_varying_known_reals=["time_idx"],
    time_varying_unknown_categoricals=[],
    time_varying_unknown_reals=["occupancy"],
    target_normalizer=GroupNormalizer(transformation=None, center=False),
    randomize_length=True,
    add_relative_time_idx=True,
    add_target_scales=True,
    add_encoder_length=True,
)



val_cutoff = data["time_idx"].max() - TEST_LENGTH
validation = TimeSeriesDataSet.from_dataset(
    training,
    data[lambda x: x.time_idx <= val_cutoff],
    predict=True,
    stop_randomization=True
)

## Configure sampling
batch_sampler = torch.utils.data.RandomSampler(
    training,
    replacement=True,
    num_samples=7500,
    generator=torch.Generator(),
)
batch_sampler = torch.utils.data.BatchSampler(batch_sampler, batch_size=16, drop_last=False)

# create dataloaders for model
train_dataloader = training.to_dataloader(
    train=True,
    batch_size=BATCH_SIZE,
    num_workers=NUM_WORKERS,
    batch_sampler=batch_sampler,
)

val_dataloader = validation.to_dataloader(
    train=False,
    batch_size=BATCH_SIZE * 10,
    num_workers=NUM_WORKERS,
)
```

### Actual behavior

When I try to get the actuals, it runs for a very long time and then provides this error:
```
RuntimeError: received 0 items of ancdata
```

### Code to reproduce the problem

```
actual_test = torch.cat([y[0] for x, y in iter(test_dataloader)])
```

And to initialize the tft:
```
### configure network and trainer
early_stop_callback = EarlyStopping(monitor="val_loss", min_delta=1e-4, patience=10, verbose=False, mode="min")
lr_logger = LearningRateMonitor()  # log the learning rate
logger = TensorBoardLogger("lightning_logs")  # logging results to a tensorboard

trainer = pl.Trainer(
    max_epochs=100,
    gpus=1,
    weights_summary="top",
    gradient_clip_val=10,
#     limit_train_batches=300,
#     shuffle=True,
#     fast_dev_run=True,  # comment in to check that networkor dataset has no serious bugs
    callbacks=[lr_logger, early_stop_callback, PrintCallback(100)],
    logger=logger,
    replace_sampler_ddp=False,
)


tft = TemporalFusionTransformer.from_dataset(
    training,
    learning_rate=0.001,
    lstm_layers=2,
    hidden_size=128,
    attention_head_size=4,
    dropout=0.05,
    hidden_continuous_size=128,
    output_size=7,  # 7 quantiles by default
    loss=QuantileLoss(),
    log_interval=10,  # uncomment for learning rate finder and otherwise, e.g. to 10 for logging every 10 batches
    reduce_on_plateau_patience=1000,
)
tft.output_layer = torch.nn.Sigmoid()
print(f"Number of parameters in network: {tft.size()/1e3:.1f}k")
```
(if you're curious PrintCallback just prints certain info to the console, doesn't affect the model)

I figure it has something to do with how I'm initializing one (or multiple) of the TimeSeries. I also figure there is already a commonly-used way to do exactly what I'm trying to do, but I haven't yet found it.

Thanks.

**Comment by jdb78** [comment]
Not exactly sure what is going on. Do you happen to have a colab notebook to share?

Maybe also try `next(iter(test_dataloader))` which should be very fast and should give you immediate results. If it runs for a very long time, it is an indicator that some edge case is failing.

I am also pretty sure that you do not want
`max_prediction_length -= TEST_LENGTH` because this limits fundamentally how far your network is able to forecast.

**Comment by dempseyryan** [comment]
> I am also pretty sure that you do not want
> `max_prediction_length -= TEST_LENGTH` because this limits fundamentally how far your network is able to forecast.

Yep, that seems to have been my issue. I was trying to prevent it from using the test set as validation but I realized that's definitely not the way. Thank you for your help!


If anyone is later curious, I think the way should just be to manually override the min_prediction_idx and prediction length flags and such. As follows:

```
validation = TimeSeriesDataSet.from_dataset(
    training,
    data[lambda x: x.time_idx <= val_cutoff],
    predict=True,
    min_prediction_idx=training_cutoff + 1, # since max pred len of train > val len, set min val index
    max_prediction_length=VALIDATION_LENGTH,
    min_prediction_length=1,
    stop_randomization=True,
)
```
```
test_and_val = TimeSeriesDataSet.from_dataset(
    validation,
    data,
    predict=True,
    min_prediction_idx=training_cutoff + 1,
    max_prediction_length=VALIDATION_LENGTH + TEST_LENGTH,
    stop_randomization=True,
)
```

**Comment by eliassz** [comment]
@dempseyryan, hi! I have same issue. Can you share you work with pytorch-forecasting (if it's possible)? Like google colab or Jupyter Notebook?
