### ISSUE TITLE
Sliding Window Training for TFT?

### ISSUE THREAD

**Issue by tiago1405** [jdb78/pytorch-forecasting#326]
- PyTorch-Forecasting version: 0.8.1
- PyTorch version: 1.7 + CU 101 
- Python version: 3.6.9
- Operating System: Google Colab Compute

**Question:**
In the source code while looking into whether the TFT architecture already trains using a Sliding Window Method I saw the following snippet:
![image](https://user-images.githubusercontent.com/23642755/106930753-e32e3e00-66e3-11eb-91de-82925b145216.png)

My question is if the TFT architecture implemented in Pytorch Forecasting learns through a Sliding Window method? And if it not would it be possible to implement such a method within the Pytorch Forecasting Framework?

**Comment by jdb78** [comment]
It is using a sliding window for learning. You can use the EncoderNormalizer to normalize the decoder variables only based on the encoder.
