### ISSUE TITLE
[QUESTION] Navigating the three different ways to generate predictions with predict()

### ISSUE THREAD

**Issue by pnmartinez** [jdb78/pytorch-forecasting#331]
Hi @jdb78 ,

I am still getting familiar with the API methods **generate new predictions**. Retrieving the correct scale of the prediction is something that escapes me.

The `Model.predict()` method **accepts three kinds of objects**: 

- `df`, 
- `TimeSeriesDataset` 
- and `DataLoader`. 

However, the results they generate are very different (image below). 

- **Can you elaborate a bit on what to expect in each case? Why do the predictions built a dataset and a dataloader are able to differ?**

- **What's the proper way to feed the model a new timeseries (say, in a df), and then retrieve the proper prediction with a proper, ready-to-be-plot scale?**

![imagen](https://user-images.githubusercontent.com/29891887/107352998-cff8e500-6acc-11eb-8b9f-38e34423c506.png)

**Comment by jdb78** [comment]
I suggest:
- use `return_x=True` in the predict function to ensure that the index is the same
- use `torch.isclose()` instead of `==` to compare results. Floating point issues might be the reason for failing comparisons

**Comment by pnmartinez** [comment]
Thanks @jdb78 . Getting familiar with the API day-by-day.

Didn't know about `torch.isclose()`, so cheers for that too! Closing issue.
