### ISSUE TITLE
Add simple MLP to models

### ISSUE THREAD

**Issue by jdb78** [jdb78/pytorch-forecasting#333]
MLPs often perform very well. We can add a MLP that only works on the decoder input.

**Comment by blacksnail789521** [comment]
@jdb78 
Hi, I want to ask why do you use `decoder_cont` and `decoder_cat` to be the input of the model?
I thought the definition of "data windowing" is to feed `encoder_cont` and `encoder_cat` into the model.


Thanks.

**Comment by kvyaswanth** [comment]
decoder_cat can always be empty array and tft still works; decoder_cont is time varying known reals attributed to the targets, I guess they employed it into the model as they help for better prediction

but some times when I have to send in a sequence of consecutive timeseries >> max encoder length it gives

"AssertionError: filters should not remove entries all entries - check encoder/decoder lengths and lags" at somepoint
