### ISSUE TITLE
Example get_stallion_data()

### ISSUE THREAD

**Issue by JK87iab** [jdb78/pytorch-forecasting#334]
- PyTorch-Forecasting version:0.8.2
- PyTorch version: 1.7.1
- Python version:3.7
- Operating System: Windwos 10
- pyarrow: 3.0
### Expected behavior

`running data = get_stallion_data()`

returns 
`OSError: NotImplemented: Support for codec 'snappy' not built
`

### Work around
It works if I download the file manually and run

`pd.read_parquet("../stallion.parquet", engine='fastparquet')`

**Comment by jdb78** [comment]
Hm. This is really weird. We are currently not testing on Windows because there the official torch package is not on PyPI. I wonder if this is an arrow issue at the core. Have you tried installing arrow via conda?
