### ISSUE TITLE
loading .ckpt file for forecasting get unexpected keyword 'n_targets' 

### ISSUE THREAD

**Issue by BlockWaving** [jdb78/pytorch-forecasting#336]
I copied a .ckpt file from the training machine to an idle machine to testing forecasting.
Both machine configured with the same packages:

- PyTorch-Forecasting version: current
- PyTorch version: 1.7.1
- Python version: 3.8
- Operating System: Windows 10

But when calling 

`model = TemporalFusionTransformer.load_from_checkpoint(path)`

I got the following error message:

>   model = TemporalFusionTransformer.load_from_checkpoint(path)
> File "D:\Progs\Anaconda3\envs\Torch171_Ltn114\lib\site-packages\pytorch_lightning\core\saving.py", line 159, in load_from_checkpoint
>     model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
> File "D:\Progs\Anaconda3\envs\Torch171_Ltn114\lib\site-packages\pytorch_lightning\core\saving.py", line 199, in _load_model_state
>     model = cls(**_cls_kwargs)
>   File "D:\Progs\Anaconda3\envs\Torch171_Ltn114\lib\site-packages\pytorch_forecasting\models\temporal_fusion_transformer\__init__.py", line 137, in __init__
>     super().__init__(loss=loss, logging_metrics=logging_metrics, **kwargs)
> TypeError: __init__() got an unexpected keyword argument 'n_targets'
> 

By verification, called:
```
checkpoint = torch.load(path
print(checkpoint['hyper_parameters'])
```

the checkpoint was successfully loaded, and all hyper parameters were printed, and can see 'n_targets': 1.

wondering what went wrong here, and how to fix.
Thanks,

**Comment by jdb78** [comment]
Are you sure that machines have the same version installed? Line 137 looks different to me for version 0.8.3: https://github.com/jdb78/pytorch-forecasting/blob/v0.8.3/pytorch_forecasting/models/temporal_fusion_transformer/__init__.py#L137
