### ISSUE TITLE
categorical prediction crossentropy error

### ISSUE THREAD

**Issue by dnwldnwl2** [jdb78/pytorch-forecasting#346]
- PyTorch-Forecasting version: 0.8.3
- PyTorch version: 1.7
- Python version: 3.7
- Operating System:ubuntu

### Expected behavior

encoded my target as int and use cross entropy as mentioned here (https://github.com/jdb78/pytorch-forecasting/issues/91)

error occured while finding best learning rate

### Actual behavior

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-30-6fa6e18694a8> in <module>
      8     val_dataloaders=val_dataloader,
      9     max_lr=1.0,
---> 10     min_lr=1e-6,
     11 )
     12 

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/tuner/tuning.py in lr_find(self, model, train_dataloader, val_dataloaders, min_lr, max_lr, num_training, mode, early_stop_threshold, datamodule)
    137             mode,
    138             early_stop_threshold,
--> 139             datamodule,
    140         )
    141 

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/tuner/lr_finder.py in lr_find(trainer, model, train_dataloader, val_dataloaders, min_lr, max_lr, num_training, mode, early_stop_threshold, datamodule)
    186                 train_dataloader=train_dataloader,
    187                 val_dataloaders=val_dataloaders,
--> 188                 datamodule=datamodule)
    189 
    190     # Prompt if we stopped early

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in fit(self, model, train_dataloader, val_dataloaders, datamodule)
    508         self.call_hook('on_fit_start')
    509 
--> 510         results = self.accelerator_backend.train()
    511         self.accelerator_backend.teardown()
    512 

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py in train(self)
     55     def train(self):
     56         self.trainer.setup_trainer(self.trainer.model)
---> 57         return self.train_or_test()
     58 
     59     def teardown(self):

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py in train_or_test(self)
     72         else:
     73             self.trainer.train_loop.setup_training()
---> 74             results = self.trainer.train()
     75         return results
     76 

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in train(self)
    530 
    531     def train(self):
--> 532         self.run_sanity_check(self.get_model())
    533 
    534         # set stage for logging

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in run_sanity_check(self, ref_model)
    729 
    730             # run eval step
--> 731             _, eval_results = self.run_evaluation(max_batches=self.num_sanity_val_batches)
    732 
    733             # allow no returns from eval

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in run_evaluation(self, max_batches, on_epoch)
    641                 # lightning module methods
    642                 with self.profiler.profile("evaluation_step_and_end"):
--> 643                     output = self.evaluation_loop.evaluation_step(batch, batch_idx, dataloader_idx)
    644                     output = self.evaluation_loop.evaluation_step_end(output)
    645 

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/evaluation_loop.py in evaluation_step(self, batch, batch_idx, dataloader_idx)
    169         else:
    170             model_ref._current_fx_name = "validation_step"
--> 171             output = self.trainer.accelerator_backend.validation_step(args)
    172 
    173         # capture any logged information

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/cpu_accelerator.py in validation_step(self, args)
     63 
     64     def validation_step(self, args):
---> 65         return self._step(self.trainer.model.validation_step, args)
     66 
     67     def test_step(self, args):

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/cpu_accelerator.py in _step(self, model_step, args)
     56                 output = model_step(*args)
     57         else:
---> 58             output = model_step(*args)
     59         return output
     60 

/opt/conda/lib/python3.7/site-packages/pytorch_forecasting/models/base_model.py in validation_step(self, batch, batch_idx)
    273     def validation_step(self, batch, batch_idx):
    274         x, y = batch
--> 275         log, _ = self.step(x, y, batch_idx)  # log loss
    276         self.log("val_loss", log["loss"], on_step=False, on_epoch=True, prog_bar=True)
    277         return log

/opt/conda/lib/python3.7/site-packages/pytorch_forecasting/models/temporal_fusion_transformer/__init__.py in step(self, x, y, batch_idx)
    545         """
    546         # extract data and run model
--> 547         log, out = super().step(x, y, batch_idx)
    548         # calculate interpretations etc for latter logging
    549         if self.log_interval > 0:

/opt/conda/lib/python3.7/site-packages/pytorch_forecasting/models/base_model.py in step(self, x, y, batch_idx, **kwargs)
    373                 )
    374             else:
--> 375                 loss = self.loss(prediction, y)
    376 
    377         # log

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/metrics/metric.py in forward(self, *args, **kwargs)
    152         # add current step
    153         with torch.no_grad():
--> 154             self.update(*args, **kwargs)
    155         self._forward_cache = None
    156 

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/metrics/metric.py in wrapped_func(*args, **kwargs)
    198         def wrapped_func(*args, **kwargs):
    199             self._computed = None
--> 200             return update(*args, **kwargs)
    201         return wrapped_func
    202 

/opt/conda/lib/python3.7/site-packages/pytorch_forecasting/metrics.py in update(self, y_pred, target)
    493             lengths = torch.full((target.size(0),), fill_value=target.size(1), dtype=torch.long, device=target.device)
    494 
--> 495         losses = self.loss(y_pred, target)
    496         # weight samples
    497         if weight is not None:

/opt/conda/lib/python3.7/site-packages/pytorch_forecasting/metrics.py in loss(self, y_pred, target)
    681     def loss(self, y_pred, target):
    682 
--> 683         loss = F.cross_entropy(y_pred.view(-1, y_pred.size(-1)), target.view(-1), reduction="none").view(
    684             -1, target.size(-1)
    685         )

/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py in cross_entropy(input, target, weight, size_average, ignore_index, reduce, reduction)
   2466     if size_average is not None or reduce is not None:
   2467         reduction = _Reduction.legacy_get_string(size_average, reduce)
-> 2468     return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
   2469 
   2470 

/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py in nll_loss(input, target, weight, size_average, ignore_index, reduce, reduction)
   2262                          .format(input.size(0), target.size(0)))
   2263     if dim == 2:
-> 2264         ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
   2265     elif dim == 4:
   2266         ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)

RuntimeError: expected scalar type Long but found Float

### Code to reproduce the problem

training = TimeSeriesDataSet(
    df,
    time_idx="timestamp", 
    target="target", 
    group_ids=["no"], 
    max_encoder_length=max_encoder_length, 
    max_prediction_length=max_prediction_length, 
    time_varying_unknown_reals=['target'],
    target_normalizer=GroupNormalizer( 
        groups=["no"], transformation="softplus" 
    ), 
    add_target_scales=False, 
    add_encoder_length=False,
    add_relative_time_idx=True
)

tft = TemporalFusionTransformer.from_dataset(
    training,
    allowed_encoder_known_variable_names = "all", 
    learning_rate=0.03,
    hidden_size=16, 
    attention_head_size=4,
    dropout=0.1,  
    hidden_continuous_size=8,  
    output_size=1,  
    loss=CrossEntropy(),
    reduce_on_plateau_patience=4, 
)

res = trainer.tuner.lr_find(
    tft,
    train_dataloader=train_dataloader,
    val_dataloaders=val_dataloader,
    max_lr=1.0,
    min_lr=1e-6,
)

print(f"suggested learning rate: {res.suggestion()}")
fig = res.plot(show=True, suggest=True)
fig.show()

**Comment by jdb78** [comment]
Try using a string target (the library will encode it for you) and place it into the time_varying_unknown_categoricals.

**Comment by dnwldnwl2** [comment]
Thanks it works, but seems none of normalizer not working. I triese EncoderNormalizer and GroupNormlizer both failed. Not using any normalizer as a temporary measure.

**Comment by jdb78** [comment]
Go with the NaNLabelEncoder for classification tasks. The TimeseriesDataSet will choose it by default.
