### ISSUE TITLE
GPU Training is slower than CPU training on Kubeflow

### ISSUE THREAD

**Issue by lorenzo-caruso** [jdb78/pytorch-forecasting#349]
Hi, 
I'm using pytorch-forecasting on Kubeflow and training TFT and using torch version 1.7.1, pytorch-forecasting 0.8.2 and pytorch lightning 1.1.5:

1) Available resources - Pipeline (GPU)
- Docker image: pytorch/pytorch:1.6.0-cuda10.1-cudnn7-runtime (torch==1.6.0 overwritten with torch==1.7.1+cu101)
- N. CPU: 4
- RAM: 16 GB
- GPU: Nvidia K80 24 GB

2) Available resources - Pipeline (CPU)
- Docker image: base ubuntu 16.04
- N. CPU: 4
- RAM: 16 GB
- GPU: None

3) Available resources - Notebook
- N. CPU: 1
- RAM: 2 GB
- GPU: None

The problem is that training in cases 2 and 3 is faster than training on case 1. In pytorch lightning Trainer I tried to use -1, [0], '-1' and '0', as said on pytorch lightning website (https://pytorch-lightning.readthedocs.io/en/stable/multi_gpu.html#select-gpu-devices) under "Select GPU devices". In dataloader I tried to set num_of_workers = 4 and pin_memory=True, but nothing changed. In Kubeflow console, in case 1, I looks that the model is using GPU and pytorch lightning summary prints:

"GPU available: True, used: True"

But as I said before perfomances using GPU are worst than not using it.

Thanks,
Lorenzo

**Comment by jdb78** [comment]
Question of the bottleneck. If you model is small and the batch size is also not too big, transferring data to the GPU might cost more time than evaluating on the CPU. The cost of using a bigger transfer model might be negligible on GPU though, so you that you can scale up easily. There is a great paper on language models: "Train Large, Then Compress"

**Comment by lorenzo-caruso** [comment]
Ok, I think this could be the problem. Thank you very much!
