### ISSUE TITLE
Predicting on unseen data: Error "check encoder/decoder lengths and lags"

### ISSUE THREAD

**Issue by Rmk17** [jdb78/pytorch-forecasting#352]
- PyTorch-Forecasting version: 0.8.3
- rest is Google Colab environment

I am tasked with electricity peak prediction task. For that I have data from 2013 till 2020 with hourly observation taken on weekdays only, so Mon-Fri. Data has power load + various predictor features: weather, street light, sunlight etc. Data has natural gaps, which TimeSeriesDataSet can handle with `allow_missings=True`. Target lags also specified manually (from ACF) - `[1, 23, 24, 25, 47, 48, 49, 71, 72, 73, 95, 96, 97, 120, 144, 168, 192]`

To better understand the nature of time series I have included validation prediction below:

![download](https://user-images.githubusercontent.com/35836423/108379111-85c6e080-71fd-11eb-82ca-fa57d4a8afdd.png)

By following this tutorial https://pytorch-forecasting.readthedocs.io/en/latest/tutorials/stallion.html#Predict-on-new-data I was able to handle most parts, including prediction on val_dataloader, up until predicting on unseen data. 

'time_idx' was created uniformly as a function of datetime in the beginning before the split to train and test. So that

```
# add time index needed by PyTorch Forecasting
df['dt_iso'] = df.index
df['dt'] = df['dt_iso'].apply(lambda x : calendar.timegm(pd.to_datetime(x).timetuple()))
df['time_idx'] = (df['dt'] / 3600).astype(int) # 1 increment of the time_idx corresponds to +1H
df['time_idx'] -= df['time_idx'].min()

def train_test_split(df, split_date, n_steps):
    train: pd.DataFrame = df.loc[(df.index < split_date)].copy()
    test: pd.DataFrame = df.loc[df.index >= split_date].copy()[:n_steps]  # test only first 24 hours
    return train, test
   
SPLIT_DATE = '2020-12-02'
data, test = train_test_split(df, SPLIT_DATE, 24)
```

If i repeat the Stallion data example exactly, 
`encoder_data = data[lambda x: x.time_idx > x.time_idx.max() - max_encoder_length]`
then I get 120 observations in the encoder_data (because data from Sat, Sun is missing)

or with
```
encoder_data = data.iloc[-max_encoder_length:, ]
decoder_data = test.copy(deep=True)
```
i get 168 observations in encoder and 24 in decoder:

```
encoder_data.shape, decoder_data.shape
((168, 48), (24, 48))
```

```
encoder_data.time_idx.max(), decoder_data.time_idx.min()
(67247, 67248)
```

**But when I do** 
`new_prediction_data = pd.concat([encoder_data, decoder_data], ignore_index=True/False)`
and feed it to best_tft.predict
`new_predictions, new_x = best_tft.predict(new_prediction_data, return_x=True)`

I get 

> /usr/local/lib/python3.6/dist-packages/pytorch_forecasting/data/timeseries.py in _construct_index(self, data, predict_mode)
    1235         assert (
    1236             len(df_index) > 0
->1237         ), "filters should not remove entries all entries - check encoder/decoder lengths and lags"
    1238 
    1239         return df_index
AssertionError: filters should not remove entries all entries - check encoder/decoder lengths and lags

no matter what size of new_prediction_data I supply.

So my question is : 
1) Might the issue be that 'time_idx' is dependent on date, and in case of missing dates it goes skewed?
When I test the encoder_data.time_idx at the Fri - Mon border, I obviously get gaps in 'time_idx', since it was created a function of date:
```
data.loc['2020-11-27 22:00:00':'2020-11-30 02:00:00', 'time_idx']

dt_iso
2020-11-27 22:00:00    67150
2020-11-27 23:00:00    67151
2020-11-30 00:00:00    67200
2020-11-30 01:00:00    67201
2020-11-30 02:00:00    67202
```

2) Shall I replace 'time_idx' from being function of datetime to a simple increment counter?
`df['time_idx'] = range(1, 1 + len(df))`

The code used to initialize the TimeSeriesDataSet:

```
max_prediction_length = 24 # forecast 24 hours
max_encoder_length = 24*7 # use 168 hours of hourly history
training_cutoff = data['time_idx'].max() - max_prediction_length
lags_0935 = [1, 23, 24, 25, 47, 48, 49, 71, 72, 73, 95, 96, 97, 120, 144, 168, 192] # acf(load) >= 0.935

training = TimeSeriesDataSet(
    data[lambda x: x.time_idx <= training_cutoff], # all data except last 24 hours
    time_idx='time_idx',
    target='load',
    group_ids=['group'],
    min_encoder_length=max_encoder_length // 2,  # keep encoder length long (as it is in the validation set)
    # or max_encoder_length,
    max_encoder_length=max_encoder_length,
    min_prediction_length=1, # max_prediction_length,
    max_prediction_length=max_prediction_length,
    static_categoricals=['group'],
    static_reals=[],
    time_varying_known_categoricals=['special_days'],
    variable_groups={'special_days': special_days},  # group of categorical variables can be treated as one variable
    time_varying_known_reals=real_vars,
    time_varying_unknown_categoricals=[],
    time_varying_unknown_reals=[
        'load',
    ],
    #target_normalizer=GroupNormalizer(
    #    groups=['group'], transformation='softplus'
    #),  # use softplus and normalize by group
    #add_relative_time_idx=True,
    add_target_scales=True,
    #add_encoder_length=True,
    allow_missings=True,
    lags={'load': lags_0935}
)

```

UPD:

Issue closed. Had to set `max_encoder_length > max_lag.` and able to run `predict `successfully

**Comment by Rmk17** [comment]
Tried with monotonic incremental time_idx instead of one that is function of date. 
```
# or time index as a counter:
df['time_idx'] = range(1, 1 + len(df))
```
Now there are no gaps.
```
# check the border between Fri and Mon, is monotonic?
data.loc['2020-11-27 22:00:00':'2020-11-30 02:00:00', 'time_idx']
```
```
dt_iso
2020-11-27 22:00:00    45095
2020-11-27 23:00:00    45096
2020-11-30 00:00:00    45097
2020-11-30 01:00:00    45098
2020-11-30 02:00:00    45099
Name: time_idx, dtype: int64

encoder_data.index[-1], decoder_data.index[0]
(Timestamp('2020-12-01 23:00:00'), Timestamp('2020-12-02 00:00:00'))
```
But I still get the same error.
> AssertionError: filters should not remove entries all entries - check encoder/decoder lengths and lags

P.S. Also RMSE, MAE, MAPE all went quite a bit and model missed the peak,
whereas it was able to identify correctly before.

![download (1)](https://user-images.githubusercontent.com/35836423/108401168-f973e800-7213-11eb-9a34-751382807a9a.png)
![download (2)](https://user-images.githubusercontent.com/35836423/108401180-fbd64200-7213-11eb-82c3-913195ab7152.png)

**Comment by Rmk17** [comment]
Ran all this under debugger.

in TimeSeriesDataSet constructor (called from predict) `_init_` there is a call to `_preprocess_data()` method.
Before entering method data.shape is (192, 48), after exiting (0, 70).

Inside the method: 

```
# shorten data by maximum of lagged sequences to avoid NA values - shorten only after encoding
if self.max_lag > 0:
    # negative tail implementation as .groupby().tail(-self.max_lag) is not implemented in pandas
	g = data.groupby(self._group_ids, observed=True)
	data = g._selected_obj[g.cumcount() >= self.max_lag] # <- kill all the data
    return data
```

And since I specified 192 among lags, while having `max_encoder_length = 168` 
that led that auto created target_lagged_by_192 to be all NaNs. 
So somewhere inside it drops NaNs and effectively squishes all my test data.

**Comment by KovalevEvgeny** [comment]
@Rmk17 Hello, I am having the same issue. Could you please tell me more about your solution? What is max_lag and how do I change it?

**Comment by Rmk17** [comment]
Hey Evgeny, 

I picked lags for the time series based on auto-correlation function return, so in my case lags were 
lags_0935 = [1, 23, 24, 25, 47, 48, 49, 71, 72, 73, 95, 96, 97, 120, 144, 168, 192].

Then lags were passed to TimeSeriesDataset manually, since I am not sure it can detect seasonality on its own, and basically there is no need for this.
```
training = TimeSeriesDataSet(
	...
 	max_encoder_length = 168
	lags={'load': lags_0935}
)
```
In the same time I used 1 week (168h) as `max_encoder_length`. And 24h as  `max_prediction_length `

Internally, PTF creates extra features by concatenating features created by pandas shift()’s for every lags you specify. So at some point there will be column load_lag_192 among others, which for test dataset will contain only NaNs since encoder length is smaller – 168. And whole test data becomes truncated because of this call in the source code:
```
timeseries.py
# shorten data by maximum of lagged sequences to avoid NA values - shorten only after encoding
if self.max_lag > 0:
    # negative tail implementation as .groupby().tail(-self.max_lag) is not implemented in pandas
	g = data.groupby(self._group_ids, observed=True)
	data = g._selected_obj[g.cumcount() >= self.max_lag] # <- kills all the data
    return data
```
So, the error message means what it reads, but since it was confusing to me, so I had to go all the way with debugger into source code of PTF. To summarize, **make sure that lags you pass to TimeSeriesDataser are within `max_encoder_length` range, or you are going to get NaNs**.

The other source for this error message can be gaps in `time_idx`.
Also as you can see from the picture in previous post my time series has natural gaps, i.e missing data for Sat & Sun. 
In my case time_idx was a function of time of current observation. 
```
df['dt'] = df['dt_iso'].apply(lambda x : calendar.timegm(pd.to_datetime(x).timetuple()))
df['time_idx'] = (df['dt'] / 3600).astype(int) # 1 increment of the time_idx corresponds to +1H
```

You can see below that it also has gaps: '2020-11-27' is Fri, '2020-11-30' is Mon.
```
2020-11-27 22:00:00    67150
2020-11-27 23:00:00    67151
2020-11-30 00:00:00    67200
2020-11-30 01:00:00    67201
2020-11-30 02:00:00    67202
```

So when you predict on new data, instead of 
`encoder_data = data[lambda x: x.time_idx > x.time_idx.max() - max_encoder_length]`
which resulted in 120 hours

I had to specify 
`encoder_data = data.iloc[-max_encoder_length:, ]`
which has 168 records (or other respective to max_encoder_length)

You do not have to do this if your time_idx is monotonic and has no gaps
`df['time_idx'] = range(1, 1 + len(df))`

Then either of calls will work fine.

**Comment by KovalevEvgeny** [comment]
@Rmk17 Thank you so much for a very detailed answer! You gave me the insight about the encoder lengths, and I have finally solved my problem. Actually, it was a much simpler issue than yours. I wanted to run inference on the test data, which was pretty short. I solved my problem by setting `min_encoder_length=0` - I guess the reason was that `min_encoder_length` value was too large for my data.
