### ISSUE TITLE
AttributeError: 'TimeSeriesDataSet' object has no attribute 'filter'

### ISSUE THREAD

**Issue by 123mitnik** [jdb78/pytorch-forecasting#358]
- PyTorch-Forecasting version: 0.8.3
- PyTorch version: 1.7.1
- pytorch-lightning: 1.1.8
- Python version: 3.7.6
- Operating System: OSX 11.1

When running the code from the Tutorial - Demand forecasting with the Temporal Fusion Transformer
https://pytorch-forecasting.readthedocs.io/en/latest/tutorials/stallion.html

**Predict on selected data**  - this code section fails with the following: "AttributeError: 'TimeSeriesDataSet' object has no attribute 'filter'"

![image](https://user-images.githubusercontent.com/1234337/108714249-00f00580-7522-11eb-84cf-17e8987019b9.png)

![image](https://user-images.githubusercontent.com/1234337/108714313-12391200-7522-11eb-88f4-06818338af67.png)

the rest of the code is running Ok

**Comment by jdb78** [comment]
The filter feature is currently unreleased so you have to install from the master branch.

**Comment by ikvision** [comment]
@jdb78 It would be great if a unreleased feature won't appear in the tutorial - it makes adoption of the package pretty steep.
Can you help me install it from master branch or replace the filter in the notebook please
