### ISSUE TITLE
TimeSeriesDataSet with time varying known features that depend on prediction time

### ISSUE THREAD

**Issue by TomSteenbergen** [jdb78/pytorch-forecasting#360]
- PyTorch-Forecasting version: 0.8.3
- PyTorch-Lightning version: 1.1.8
- Python version: 3.8.1
- Operating System: macOS Big Sur 11.2.1

I'm currently using the `TemporalFusionTransformer` for a demand forecasting problem. I have time varying known real features of which the value **depends on the moment of prediction**, and not only on the time step for which we predict. An example of such a feature is 'confirmed demand', i.e. the number of orders already placed before the prediction time for a given time step (day) that we want to predict for. 

E.g., if I would need to create a prediction **now**, I know that I have already 100 placed orders that need to be delivered **three days ahead**. When I create a prediction the next day, 200 orders might have been placed for that same time index, which is now **two days ahead.**

This is problematic since the `TimeSeriesDataSet` simply slices the dataset in various points in time, as long as it is able to generate a valid sequence. The way I fixed this for now, is by including `prediction_timestamp` in the `group_columns` and fix the `min_prediction_idx` when instantiating a `TimeSeriesDataset`. This ensures that these time varying known real features have the correct value. This of course explodes my data set since I now need to duplicate rows in my data set. Instead of having a row per article and per delivery date, I now have a row per article, delivery date, and prediction date.

**My question:** is there a better, more memory-efficient way to handle datasets with time varying known real features of which the value depends on the moment of prediction?

Many thanks in advance!

**Comment by jdb78** [comment]
You have to reduce your prediction_length to make sure your feature is known at prediction time. Alternatively, you can use a recurrent model such as DeepAR that is autoregressive.
