### ISSUE TITLE
Plans to add simple feedforward and recurrent baselines?

### ISSUE THREAD

**Issue by bradyneal** [jdb78/pytorch-forecasting#361]
Are there any near-term plans to add a simple feedforward network baseline that works with covariates and a LSTM/GRU baseline that works with covariates? For example, the `FullyConnectedModelWithCovariates` and the `LSTMModel` (but extended to work with covariates) [here](https://pytorch-forecasting.readthedocs.io/en/latest/tutorials/building.html) both seem like valuable baselines to have in the library.

**Comment by jdb78** [comment]
Yes. There is. It is on the roadmap :)
