### ISSUE TITLE
Question about the time_idx

### ISSUE THREAD

**Issue by 123mitnik** [jdb78/pytorch-forecasting#366]
what if we train our model on 'seconds' data (or the index is just auto-incremented)

should we include the time_idx in the encoder/decoder (i would guess - no). I'm asking this because let say we have a pre-trained model and we would like to do some predictions after few days; there won't be correct time_idx data for the encoder_data part in order to feed the model.

How we must handle the situation. Re-train from scratch every time , remove the time_idx from time_varying_known_reals. And how do we generate the encoder_data - are we just grabbing the last n-max_encoder_length points and feed the decoder with relevant covariates for prediction (what should be the time_idx) ?

Thank You!

**Comment by jdb78** [comment]
The time_idx should be monotonically increasing. Think of it as an additional covariant that you will always know in advance. Generally, it is a good idea to include it. Hope this helps
