### ISSUE TITLE
Hi, I am trying to train the pytorch forecasting model on google colab. but keep getting error when try to train: AttributeError: 'str' object has no attribute '__name__'           

### ISSUE THREAD

**Issue by GauriSaran** [jdb78/pytorch-forecasting#371]
this is my code:
tf.io.gfile = tb.compat.tensorflow_stub.io.gfile
trainer.fit(
    tft,
    train_dataloader=train_dataloader,
    val_dataloaders=val_dataloader,
)

And it keeps giving this error:
AttributeError: 'str' object has no attribute '__name__'

It was running fine until day before. I was rerunning the same notebook with no changes. But I keep getting this error.

**Comment by jdb78** [comment]
See #354

**Comment by GauriSaran** [comment]
Thanks. That resolved the problem.

**Comment by GauriSaran** [comment]
Closing the issue.
