### ISSUE TITLE
The following error occurred  when run 'stallion.ipynb' ，How to solve it？

### ISSUE THREAD

**Issue by 2017wxyzwxyz** [jdb78/pytorch-forecasting#377]
- PyTorch-Forecasting version:         0.8.2
- PyTorch version:                            1.7.1
- Python version:                              3.8
- Operating System:                         win10

### Expected behavior

I executed code 'stallion.ipynb' in order to learn  'PyTorch-Forecasting' and expected to get result as it is.

### Actual behavior
 
However, result was  :

---------------------------------------------------------------------------
gaierror                                  Traceback (most recent call last)
C:\Anaconda\lib\site-packages\urllib3\connection.py in _new_conn(self)
    158         try:
--> 159             conn = connection.create_connection(
    160                 (self._dns_host, self.port), self.timeout, **extra_kw

C:\Anaconda\lib\site-packages\urllib3\util\connection.py in create_connection(address, timeout, source_address, socket_options)
     60 
---> 61     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
     62         af, socktype, proto, canonname, sa = res

C:\Anaconda\lib\socket.py in getaddrinfo(host, port, family, type, proto, flags)
    917     addrlist = []
--> 918     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    919         af, socktype, proto, canonname, sa = res

gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

NewConnectionError                        Traceback (most recent call last)
C:\Anaconda\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    669             # Make the request on the httplib connection object.
--> 670             httplib_response = self._make_request(
    671                 conn,

C:\Anaconda\lib\site-packages\urllib3\connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    380         try:
--> 381             self._validate_conn(conn)
    382         except (SocketTimeout, BaseSSLError) as e:

C:\Anaconda\lib\site-packages\urllib3\connectionpool.py in _validate_conn(self, conn)
    975         if not getattr(conn, "sock", None):  # AppEngine might not have  `.sock`
--> 976             conn.connect()
    977 

C:\Anaconda\lib\site-packages\urllib3\connection.py in connect(self)
    307         # Add certificate verification
--> 308         conn = self._new_conn()
    309         hostname = self.host

C:\Anaconda\lib\site-packages\urllib3\connection.py in _new_conn(self)
    170         except SocketError as e:
--> 171             raise NewConnectionError(
    172                 self, "Failed to establish a new connection: %s" % e

NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00000296F72CCA90>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)
C:\Anaconda\lib\site-packages\requests\adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    438             if not chunked:
--> 439                 resp = conn.urlopen(
    440                     method=request.method,

C:\Anaconda\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    723 
--> 724             retries = retries.increment(
    725                 method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]

C:\Anaconda\lib\site-packages\urllib3\util\retry.py in increment(self, method, url, response, error, _pool, _stacktrace)
    438         if new_retry.is_exhausted():
--> 439             raise MaxRetryError(_pool, url, error or ResponseError(cause))
    440 

MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /jdb78/pytorch-forecasting/master/examples/data/stallion.parquet (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000296F72CCA90>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
<ipython-input-3-cb5b6f936372> in <module>
      1 from pytorch_forecasting.data.examples import get_stallion_data
      2 
----> 3 data = get_stallion_data()
      4 
      5 # add time index

C:\Anaconda\lib\site-packages\pytorch_forecasting\data\examples.py in get_stallion_data()
     48         pd.DataFrame: data
     49     """
---> 50     fname = _get_data_by_filename("stallion.parquet")
     51     return pd.read_parquet(fname)
     52 

C:\Anaconda\lib\site-packages\pytorch_forecasting\data\examples.py in _get_data_by_filename(fname)
     28     if not full_fname.exists():
     29         url = BASE_URL + fname
---> 30         download = requests.get(url, allow_redirects=True)
     31         with open(full_fname, "wb") as file:
     32             file.write(download.content)

C:\Anaconda\lib\site-packages\requests\api.py in get(url, params, **kwargs)
     74 
     75     kwargs.setdefault('allow_redirects', True)
---> 76     return request('get', url, params=params, **kwargs)
     77 
     78 

C:\Anaconda\lib\site-packages\requests\api.py in request(method, url, **kwargs)
     59     # cases, and look like a memory leak in others.
     60     with sessions.Session() as session:
---> 61         return session.request(method=method, url=url, **kwargs)
     62 
     63 

C:\Anaconda\lib\site-packages\requests\sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    528         }
    529         send_kwargs.update(settings)
--> 530         resp = self.send(prep, **send_kwargs)
    531 
    532         return resp

C:\Anaconda\lib\site-packages\requests\sessions.py in send(self, request, **kwargs)
    663             # Redirect resolving generator.
    664             gen = self.resolve_redirects(r, request, **kwargs)
--> 665             history = [resp for resp in gen]
    666         else:
    667             history = []

C:\Anaconda\lib\site-packages\requests\sessions.py in <listcomp>(.0)
    663             # Redirect resolving generator.
    664             gen = self.resolve_redirects(r, request, **kwargs)
--> 665             history = [resp for resp in gen]
    666         else:
    667             history = []

C:\Anaconda\lib\site-packages\requests\sessions.py in resolve_redirects(self, resp, req, stream, timeout, verify, cert, proxies, yield_requests, **adapter_kwargs)
    235             else:
    236 
--> 237                 resp = self.send(
    238                     req,
    239                     stream=stream,

C:\Anaconda\lib\site-packages\requests\sessions.py in send(self, request, **kwargs)
    641 
    642         # Send the request
--> 643         r = adapter.send(request, **kwargs)
    644 
    645         # Total elapsed time of the request (approximately)

C:\Anaconda\lib\site-packages\requests\adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    514                 raise SSLError(e, request=request)
    515 
--> 516             raise ConnectionError(e, request=request)
    517 
    518         except ClosedPoolError as e:

ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /jdb78/pytorch-forecasting/master/examples/data/stallion.parquet (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000296F72CCA90>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

**Comment by jdb78** [comment]
Could you try the newest release 0.8.4. It should work with the current PyTorch Lightning version.
