### ISSUE TITLE
Can PyTorch-Forecasting predict signal data?

### ISSUE THREAD

**Issue by 2017wxyzwxyz** [jdb78/pytorch-forecasting#378]
Can PyTorch-Forecasting predict signal data? For example, the signal in the figure below：

![Dat-w-Quasi periodic](https://user-images.githubusercontent.com/28821742/110049793-8464ee80-7d8d-11eb-8fad-f2be17b7aecb.png)

**Comment by jdb78** [comment]
In principle yes. But it always depends on the signal. If you know the physical generation process, writing a custom model might be the best way forward as you can induce great bias.

**Comment by 2017wxyzwxyz** [comment]
Thank you for your reply ！. I'll try first
