### ISSUE TITLE
got error running stallion.py 

### ISSUE THREAD

**Issue by wendongqu** [jdb78/pytorch-forecasting#381]
- PyTorch-Forecasting version: 0.8.3
- PyTorch version: 1.7.1
- Python version: 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
- Operating System: Windows 10 Home

### Expected behavior

I executed code     
# fit network
    trainer.fit(
        tft,
        train_dataloader=train_dataloader,
        val_dataloaders=val_dataloader,
    ) 
in order to run example and expected to get result

### Actual behavior

Traceback (most recent call last):
  File "D:/Projects/python/forecast/stallion.py", line 194, in <module>
    trainer.fit(
  File "D:\ProgramData\Miniconda3\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 474, in fit
    self.setup_trainer(model)
  File "D:\ProgramData\Miniconda3\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 423, in setup_trainer
    self.logger.save()
  File "D:\ProgramData\Miniconda3\lib\site-packages\pytorch_lightning\utilities\distributed.py", line 40, in wrapped_fn
    return fn(*args, **kwargs)
  File "D:\ProgramData\Miniconda3\lib\site-packages\pytorch_lightning\loggers\tensorboard.py", line 233, in save
    save_hparams_to_yaml(hparams_file, self.hparams)
  File "D:\ProgramData\Miniconda3\lib\site-packages\pytorch_lightning\core\saving.py", line 399, in save_hparams_to_yaml
    yaml.dump(v)
  File "D:\ProgramData\Miniconda3\lib\site-packages\yaml\__init__.py", line 290, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "D:\ProgramData\Miniconda3\lib\site-packages\yaml\__init__.py", line 278, in dump_all
    dumper.represent(data)
  File "D:\ProgramData\Miniconda3\lib\site-packages\yaml\representer.py", line 27, in represent
    node = self.represent_data(data)
  File "D:\ProgramData\Miniconda3\lib\site-packages\yaml\representer.py", line 52, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "D:\ProgramData\Miniconda3\lib\site-packages\yaml\representer.py", line 342, in represent_object
    return self.represent_mapping(
  File "D:\ProgramData\Miniconda3\lib\site-packages\yaml\representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
  File "D:\ProgramData\Miniconda3\lib\site-packages\yaml\representer.py", line 52, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "D:\ProgramData\Miniconda3\lib\site-packages\yaml\representer.py", line 356, in represent_object
    return self.represent_mapping(tag+function_name, value)
  File "D:\ProgramData\Miniconda3\lib\site-packages\yaml\representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
  File "D:\ProgramData\Miniconda3\lib\site-packages\yaml\representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "D:\ProgramData\Miniconda3\lib\site-packages\yaml\representer.py", line 199, in represent_list
    return self.represent_sequence('tag:yaml.org,2002:seq', data)
  File "D:\ProgramData\Miniconda3\lib\site-packages\yaml\representer.py", line 92, in represent_sequence
    node_item = self.represent_data(item)
  File "D:\ProgramData\Miniconda3\lib\site-packages\yaml\representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "D:\ProgramData\Miniconda3\lib\site-packages\yaml\representer.py", line 286, in represent_tuple
    return self.represent_sequence('tag:yaml.org,2002:python/tuple', data)
  File "D:\ProgramData\Miniconda3\lib\site-packages\yaml\representer.py", line 92, in represent_sequence
    node_item = self.represent_data(item)
  File "D:\ProgramData\Miniconda3\lib\site-packages\yaml\representer.py", line 52, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "D:\ProgramData\Miniconda3\lib\site-packages\yaml\representer.py", line 356, in represent_object
    return self.represent_mapping(tag+function_name, value)
  File "D:\ProgramData\Miniconda3\lib\site-packages\yaml\representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
  File "D:\ProgramData\Miniconda3\lib\site-packages\yaml\representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "D:\ProgramData\Miniconda3\lib\site-packages\yaml\representer.py", line 207, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "D:\ProgramData\Miniconda3\lib\site-packages\yaml\representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
  File "D:\ProgramData\Miniconda3\lib\site-packages\yaml\representer.py", line 52, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "D:\ProgramData\Miniconda3\lib\site-packages\yaml\representer.py", line 346, in represent_object
    return self.represent_sequence(tag+function_name, args)
  File "D:\ProgramData\Miniconda3\lib\site-packages\yaml\representer.py", line 92, in represent_sequence
    node_item = self.represent_data(item)
  File "D:\ProgramData\Miniconda3\lib\site-packages\yaml\representer.py", line 52, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "D:\ProgramData\Miniconda3\lib\site-packages\yaml\representer.py", line 331, in represent_object
    if function.__name__ == '__newobj__':
AttributeError: 'str' object has no attribute '__name__'

However, result was .... I think it has to do with ... because of ...

### Code to reproduce the problem

```

```

Paste the command(s) you ran and the output. Including a link to a colab notebook will speed up issue resolution.
If there was a crash, please include the traceback here.
The code used to initialize the TimeSeriesDataSet and model should be also included.

**Comment by RileyMShea** [comment]
I also gotten this just now:
- Ubuntu 20.04 x64
- python 3.8.8
- installed via conda as described in docs
  - yaml=0.2.5=h516909a_0
  - pytorch=1.8.0=py3.8_cuda11.1_cudnn8.0.5_0
  - pytorch-forecasting=0.8.3=pyhd8ed1ab_0
  - pytorch-lightning=1.2.2=pyhd8ed1ab_0

```
~/miniconda3/envs/blueberrypie/lib/python3.8/site-packages/yaml/representer.py in represent_object(self, data)
    329         if dictitems is not None:
    330             dictitems = dict(dictitems)
--> 331         if function.__name__ == '__newobj__':
    332             function = args[0]
    333             args = args[1:]

AttributeError: 'str' object has no attribute '__name__'
```

**Comment by 2017wxyzwxyz** [comment]
@wendongqu :Can you send me a copy stallion.ipynb 'run the required data？  My email address is NewWxy2016@163.com.

**Comment by wendongqu** [comment]
@2017wxyzwxyz: sent it over. thanks.

**Comment by wendongqu** [comment]
can not attach .py file. so I just paste the code here. pretty much same as the example notebook. thank you.

`import os
import warnings

warnings.filterwarnings("ignore")  # avoid printing out absolute paths

from pytorch_forecasting.data.examples import get_stallion_data
import copy
from pathlib import Path


import numpy as np
import pandas as pd
import pytorch_lightning as pl
from pytorch_lightning.callbacks import EarlyStopping, LearningRateMonitor
from pytorch_lightning.loggers import TensorBoardLogger
import torch

from pytorch_forecasting import Baseline, TemporalFusionTransformer, TimeSeriesDataSet
from pytorch_forecasting.data import GroupNormalizer
from pytorch_forecasting.metrics import SMAPE, PoissonLoss, QuantileLoss
from pytorch_forecasting.models.temporal_fusion_transformer.tuning import optimize_hyperparameters

import tensorflow as tf
import tensorboard as tb
tf.io.gfile = tb.compat.tensorflow_stub.io.gfile


def getdata(    max_prediction_length = 6,  # forecast 6 months
                max_encoder_length = 24,  # use 24 months of history
                batch_size = 128
            ):
    data = get_stallion_data()  # load data as pandas dataframe

    # add time index
    data["time_idx"] = data["date"].dt.year * 12 + data["date"].dt.month
    data["time_idx"] -= data["time_idx"].min()
    # add additional features
    # categories have to be strings
    data["month"] = data.date.dt.month.astype(str).astype("category")
    data["log_volume"] = np.log(data.volume + 1e-8)
    data["avg_volume_by_sku"] = (
        data
            .groupby(["time_idx", "sku"], observed=True)
            .volume.transform("mean")
    )
    data["avg_volume_by_agency"] = (
        data
            .groupby(["time_idx", "agency"], observed=True)
            .volume.transform("mean")
    )
    # we want to encode special days as one variable and
    # thus need to first reverse one-hot encoding
    special_days = [
        "easter_day", "good_friday", "new_year", "christmas",
        "labor_day", "independence_day", "revolution_day_memorial",
        "regional_games", "fifa_u_17_world_cup", "football_gold_cup",
        "beer_capital", "music_fest"
    ]
    data[special_days] = (
        data[special_days]
            .apply(lambda x: x.map({0: "-", 1: x.name}))
            .astype("category")
    )
    # show sample data
    print(data.sample(10, random_state=521))

    training_cutoff = data["time_idx"].max() - max_prediction_length
    training = TimeSeriesDataSet(
        data[lambda x: x.time_idx <= training_cutoff],
        time_idx="time_idx",
        target="volume",
        group_ids=["agency", "sku"],
        min_encoder_length=max_encoder_length // 2,  # keep encoder length long (as it is in the validation set)
        max_encoder_length=max_encoder_length,
        min_prediction_length=1,
        max_prediction_length=max_prediction_length,
        static_categoricals=["agency", "sku"],
        static_reals=["avg_population_2017", "avg_yearly_household_income_2017"],
        time_varying_known_categoricals=["special_days", "month"],
        variable_groups={"special_days": special_days},  # group of categorical variables can be treated as one variable
        time_varying_known_reals=["time_idx", "price_regular", "discount_in_percent"],
        time_varying_unknown_categoricals=[],
        time_varying_unknown_reals=[
            "volume",
            "log_volume",
            "industry_volume",
            "soda_volume",
            "avg_max_temp",
            "avg_volume_by_agency",
            "avg_volume_by_sku",
        ],
        target_normalizer=GroupNormalizer(
            groups=["agency", "sku"], transformation="softplus"
        ),  # use softplus and normalize by group
        add_relative_time_idx=True,
        add_target_scales=True,
        add_encoder_length=True,
    )

    # create validation set (predict=True) which means to predict the last max_prediction_length points in time
    # for each series
    validation = TimeSeriesDataSet.from_dataset(training, data, predict=True, stop_randomization=True)

    # create dataloaders for model
    batch_size = 128  # set this between 32 to 128
    train_dataloader = training.to_dataloader(train=True, batch_size=batch_size, num_workers=0)
    val_dataloader = validation.to_dataloader(train=False, batch_size=batch_size * 10, num_workers=0)
    return  training,validation,train_dataloader,val_dataloader,data

def getbaseerror(val_dataloader):
    # calculate baseline mean absolute error, i.e. predict next value as the last available value from the history
    actuals = torch.cat([y for x, (y, weight) in iter(val_dataloader)])
    baseline_predictions = Baseline().predict(val_dataloader)
    return (actuals - baseline_predictions).abs().mean().item()

def getlr(training):
    # configure network and trainer
    pl.seed_everything(42)
    trainer = pl.Trainer(
        gpus=0,
        # clipping gradients is a hyperparameter and important to prevent divergance
        # of the gradient for recurrent neural networks
        gradient_clip_val=0.1,
    )

    tft = TemporalFusionTransformer.from_dataset(
        training,
        # not meaningful for finding the learning rate but otherwise very important
        learning_rate=0.03,
        hidden_size=16,  # most important hyperparameter apart from learning rate
        # number of attention heads. Set to up to 4 for large datasets
        attention_head_size=1,
        dropout=0.1,  # between 0.1 and 0.3 are good values
        hidden_continuous_size=8,  # set to <= hidden_size
        output_size=7,  # 7 quantiles by default
        loss=QuantileLoss(),
        # reduce learning rate if no improvement in validation loss after x epochs
        reduce_on_plateau_patience=4,
    )
    print(f"Number of parameters in network: {tft.size() / 1e3:.1f}k")

    # find optimal learning rate
    res = trainer.tuner.lr_find(
        tft,
        train_dataloader=train_dataloader,
        val_dataloaders=val_dataloader,
        max_lr=10.0,
        min_lr=1e-6,
    )

    print(f"suggested learning rate: {res.suggestion()}")
    #fig = res.plot(show=True, suggest=True)
    #fig.show()
    return res.suggestion()


if __name__=='__main__':
    training,validation,train_dataloader,val_dataloader,data = getdata( )
    print(getbaseerror(val_dataloader))

    #lr=getlr(training)


    # configure network and trainer
    early_stop_callback = EarlyStopping(monitor="val_loss", min_delta=1e-4, patience=10, verbose=False, mode="min")
    lr_logger = LearningRateMonitor()  # log the learning rate
    logger = TensorBoardLogger("lightning_logs")  # logging results to a tensorboard

    trainer = pl.Trainer(
        max_epochs=30,
        gpus=1,
        weights_summary="top",
        gradient_clip_val=0.1,
        limit_train_batches=30,  # coment in for training, running valiation every 30 batches
        # fast_dev_run=True,  # comment in to check that networkor dataset has no serious bugs
        callbacks=[lr_logger, early_stop_callback],
        logger=logger,
    )

    tft = TemporalFusionTransformer.from_dataset(
        training,
        learning_rate=0.03,
        hidden_size=16,
        attention_head_size=1,
        dropout=0.1,
        hidden_continuous_size=8,
        output_size=7,  # 7 quantiles by default
        loss=QuantileLoss(),
        log_interval=10,  # uncomment for learning rate finder and otherwise, e.g. to 10 for logging every 10 batches
        reduce_on_plateau_patience=4,
    )
    print(f"Number of parameters in network: {tft.size() / 1e3:.1f}k")

    # fit network
    trainer.fit(
        tft,
        train_dataloader=train_dataloader,
        val_dataloaders=val_dataloader,
    )
`

**Comment by wendongqu** [comment]
Sorry for duplicating. this issue has been posted before in #354. simply downgrade pytorch-lightning to 1.1.8 fixed it.
