### ISSUE TITLE
why queries to multi head attention consist of only decoder part?

### ISSUE THREAD

**Issue by AtrCheema** [jdb78/pytorch-forecasting#382]
Why the [queries](https://github.com/jdb78/pytorch-forecasting/blob/master/pytorch_forecasting/models/temporal_fusion_transformer/__init__.py#L504) to multihead attention consist only of prediction part and not the whole sequence? This is in contrast to official tensorflow [code](https://github.com/google-research/google-research/blob/master/tft/libs/tft_model.py#L996) where the queries, keys and predictions are of same shape. Does it have no impact the way attention works. I understand that even in official tensorflow repo, they do [slice out the decoder prediction](https://github.com/google-research/google-research/blob/master/tft/libs/tft_model.py#L1046) and consider it as their final prediction.

**Comment by jdb78** [comment]
It speeds up training. The original implementation is not as efficient as it could be.
