### ISSUE TITLE
Error running tft tutorial

### ISSUE THREAD

**Issue by rivinduw** [jdb78/pytorch-forecasting#383]
- PyTorch-Forecasting version: 0.8.3
- PyTorch version: 1.7.1+cu101
- Python version: 3.7.10
- Operating System: posix (Google Colab)

### Expected behavior

Running [this](https://pytorch-forecasting.readthedocs.io/en/latest/tutorials/stallion.html) tutorial in official documentation would hopefully run without issues on Google Colab. 

### Actual behavior

However, result was AttributeError: 'str' object has no attribute '__name__' on running trainer.fit. 
From the traceback, seems to be when logging hyperparameters. 
When logger=None, a different error: AttributeError: 'NoneType' object has no attribute 'experiment'

Is this due to version incompatibility?

### Code to reproduce the problem

[Colab Notebook](https://colab.research.google.com/drive/1rnLlZ-7ofFrbEKnpkKGmNIIoiXx1Ghvj?usp=sharing)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-263e8be26564> in <module>()
      3     tft,
      4     train_dataloader=train_dataloader,
----> 5     val_dataloaders=val_dataloader,
      6 )

30 frames
/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py in fit(self, model, train_dataloader, val_dataloaders, datamodule)
    472         self.call_hook("on_before_accelerator_backend_setup", model)
    473         self.accelerator.setup(self, model)
--> 474         self.setup_trainer(model)
    475 
    476         # ----------------------------

/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py in setup_trainer(self, model)
    421             self.logger.log_hyperparams(model.hparams_initial)
    422             self.logger.log_graph(model)
--> 423             self.logger.save()
    424 
    425     def fit(

/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/distributed.py in wrapped_fn(*args, **kwargs)
     38     def wrapped_fn(*args, **kwargs):
     39         if rank_zero_only.rank == 0:
---> 40             return fn(*args, **kwargs)
     41 
     42     return wrapped_fn

/usr/local/lib/python3.7/dist-packages/pytorch_lightning/loggers/tensorboard.py in save(self)
    231         # save the metatags file if it doesn't exist and the log directory exists
    232         if self._fs.isdir(dir_path) and not self._fs.isfile(hparams_file):
--> 233             save_hparams_to_yaml(hparams_file, self.hparams)
    234 
    235     @rank_zero_only

/usr/local/lib/python3.7/dist-packages/pytorch_lightning/core/saving.py in save_hparams_to_yaml(config_yaml, hparams)
    397     for k, v in hparams.items():
    398         try:
--> 399             yaml.dump(v)
    400         except TypeError:
    401             warn(f"Skipping '{k}' parameter because it is not possible to safely dump to YAML.")

/usr/local/lib/python3.7/dist-packages/yaml/__init__.py in dump(data, stream, Dumper, **kwds)
    288     If stream is None, return the produced string instead.
    289     """
--> 290     return dump_all([data], stream, Dumper=Dumper, **kwds)
    291 
    292 def safe_dump_all(documents, stream=None, **kwds):

/usr/local/lib/python3.7/dist-packages/yaml/__init__.py in dump_all(documents, stream, Dumper, default_style, default_flow_style, canonical, indent, width, allow_unicode, line_break, encoding, explicit_start, explicit_end, version, tags, sort_keys)
    276         dumper.open()
    277         for data in documents:
--> 278             dumper.represent(data)
    279         dumper.close()
    280     finally:

/usr/local/lib/python3.7/dist-packages/yaml/representer.py in represent(self, data)
     25 
     26     def represent(self, data):
---> 27         node = self.represent_data(data)
     28         self.serialize(node)
     29         self.represented_objects = {}

/usr/local/lib/python3.7/dist-packages/yaml/representer.py in represent_data(self, data)
     50             for data_type in data_types:
     51                 if data_type in self.yaml_multi_representers:
---> 52                     node = self.yaml_multi_representers[data_type](self, data)
     53                     break
     54             else:

/usr/local/lib/python3.7/dist-packages/yaml/representer.py in represent_object(self, data)
    341                 and isinstance(state, dict) and newobj:
    342             return self.represent_mapping(
--> 343                     'tag:yaml.org,2002:python/object:'+function_name, state)
    344         if not listitems and not dictitems  \
    345                 and isinstance(state, dict) and not state:

/usr/local/lib/python3.7/dist-packages/yaml/representer.py in represent_mapping(self, tag, mapping, flow_style)
    116         for item_key, item_value in mapping:
    117             node_key = self.represent_data(item_key)
--> 118             node_value = self.represent_data(item_value)
    119             if not (isinstance(node_key, ScalarNode) and not node_key.style):
    120                 best_style = False

/usr/local/lib/python3.7/dist-packages/yaml/representer.py in represent_data(self, data)
     50             for data_type in data_types:
     51                 if data_type in self.yaml_multi_representers:
---> 52                     node = self.yaml_multi_representers[data_type](self, data)
     53                     break
     54             else:

/usr/local/lib/python3.7/dist-packages/yaml/representer.py in represent_object(self, data)
    354         if dictitems:
    355             value['dictitems'] = dictitems
--> 356         return self.represent_mapping(tag+function_name, value)
    357 
    358     def represent_ordered_dict(self, data):

/usr/local/lib/python3.7/dist-packages/yaml/representer.py in represent_mapping(self, tag, mapping, flow_style)
    116         for item_key, item_value in mapping:
    117             node_key = self.represent_data(item_key)
--> 118             node_value = self.represent_data(item_value)
    119             if not (isinstance(node_key, ScalarNode) and not node_key.style):
    120                 best_style = False

/usr/local/lib/python3.7/dist-packages/yaml/representer.py in represent_data(self, data)
     46         data_types = type(data).__mro__
     47         if data_types[0] in self.yaml_representers:
---> 48             node = self.yaml_representers[data_types[0]](self, data)
     49         else:
     50             for data_type in data_types:

/usr/local/lib/python3.7/dist-packages/yaml/representer.py in represent_list(self, data)
    197         #            break
    198         #if not pairs:
--> 199             return self.represent_sequence('tag:yaml.org,2002:seq', data)
    200         #value = []
    201         #for item_key, item_value in data:

/usr/local/lib/python3.7/dist-packages/yaml/representer.py in represent_sequence(self, tag, sequence, flow_style)
     90         best_style = True
     91         for item in sequence:
---> 92             node_item = self.represent_data(item)
     93             if not (isinstance(node_item, ScalarNode) and not node_item.style):
     94                 best_style = False

/usr/local/lib/python3.7/dist-packages/yaml/representer.py in represent_data(self, data)
     46         data_types = type(data).__mro__
     47         if data_types[0] in self.yaml_representers:
---> 48             node = self.yaml_representers[data_types[0]](self, data)
     49         else:
     50             for data_type in data_types:

/usr/local/lib/python3.7/dist-packages/yaml/representer.py in represent_tuple(self, data)
    284 
    285     def represent_tuple(self, data):
--> 286         return self.represent_sequence('tag:yaml.org,2002:python/tuple', data)
    287 
    288     def represent_name(self, data):

/usr/local/lib/python3.7/dist-packages/yaml/representer.py in represent_sequence(self, tag, sequence, flow_style)
     90         best_style = True
     91         for item in sequence:
---> 92             node_item = self.represent_data(item)
     93             if not (isinstance(node_item, ScalarNode) and not node_item.style):
     94                 best_style = False

/usr/local/lib/python3.7/dist-packages/yaml/representer.py in represent_data(self, data)
     50             for data_type in data_types:
     51                 if data_type in self.yaml_multi_representers:
---> 52                     node = self.yaml_multi_representers[data_type](self, data)
     53                     break
     54             else:

/usr/local/lib/python3.7/dist-packages/yaml/representer.py in represent_object(self, data)
    354         if dictitems:
    355             value['dictitems'] = dictitems
--> 356         return self.represent_mapping(tag+function_name, value)
    357 
    358     def represent_ordered_dict(self, data):

/usr/local/lib/python3.7/dist-packages/yaml/representer.py in represent_mapping(self, tag, mapping, flow_style)
    116         for item_key, item_value in mapping:
    117             node_key = self.represent_data(item_key)
--> 118             node_value = self.represent_data(item_value)
    119             if not (isinstance(node_key, ScalarNode) and not node_key.style):
    120                 best_style = False

/usr/local/lib/python3.7/dist-packages/yaml/representer.py in represent_data(self, data)
     46         data_types = type(data).__mro__
     47         if data_types[0] in self.yaml_representers:
---> 48             node = self.yaml_representers[data_types[0]](self, data)
     49         else:
     50             for data_type in data_types:

/usr/local/lib/python3.7/dist-packages/yaml/representer.py in represent_dict(self, data)
    205 
    206     def represent_dict(self, data):
--> 207         return self.represent_mapping('tag:yaml.org,2002:map', data)
    208 
    209     def represent_set(self, data):

/usr/local/lib/python3.7/dist-packages/yaml/representer.py in represent_mapping(self, tag, mapping, flow_style)
    116         for item_key, item_value in mapping:
    117             node_key = self.represent_data(item_key)
--> 118             node_value = self.represent_data(item_value)
    119             if not (isinstance(node_key, ScalarNode) and not node_key.style):
    120                 best_style = False

/usr/local/lib/python3.7/dist-packages/yaml/representer.py in represent_data(self, data)
     50             for data_type in data_types:
     51                 if data_type in self.yaml_multi_representers:
---> 52                     node = self.yaml_multi_representers[data_type](self, data)
     53                     break
     54             else:

/usr/local/lib/python3.7/dist-packages/yaml/representer.py in represent_object(self, data)
    344         if not listitems and not dictitems  \
    345                 and isinstance(state, dict) and not state:
--> 346             return self.represent_sequence(tag+function_name, args)
    347         value = {}
    348         if args:

/usr/local/lib/python3.7/dist-packages/yaml/representer.py in represent_sequence(self, tag, sequence, flow_style)
     90         best_style = True
     91         for item in sequence:
---> 92             node_item = self.represent_data(item)
     93             if not (isinstance(node_item, ScalarNode) and not node_item.style):
     94                 best_style = False

/usr/local/lib/python3.7/dist-packages/yaml/representer.py in represent_data(self, data)
     50             for data_type in data_types:
     51                 if data_type in self.yaml_multi_representers:
---> 52                     node = self.yaml_multi_representers[data_type](self, data)
     53                     break
     54             else:

/usr/local/lib/python3.7/dist-packages/yaml/representer.py in represent_object(self, data)
    329         if dictitems is not None:
    330             dictitems = dict(dictitems)
--> 331         if function.__name__ == '__newobj__':
    332             function = args[0]
    333             args = args[1:]

AttributeError: 'str' object has no attribute '__name__'

**Comment by geosaRW** [comment]
Same here. What is wrong?

**Comment by geosaRW** [comment]
Check this one. It was in the closed issues. You need a downgraded version of pytorch lighting
https://github.com/jdb78/pytorch-forecasting/issues/354

**Comment by jdb78** [comment]
Could you try the newest release 0.8.4. It should work with the current PyTorch Lightning version.

**Comment by rivinduw** [comment]
Thanks. 

Maybe it's a good idea to maintain a working google colab notebook?
Seems pytorch-lightning is also broken on the latest google colab (https://github.com/PyTorchLightning/pytorch-lightning/issues/6415)

Solution:
!pip install git+https://github.com/PyTorchLightning/pytorch-lightning
