### ISSUE TITLE
Cannot convert string to float: "GROUP_A"

### ISSUE THREAD

**Issue by NHQ** [jdb78/pytorch-forecasting#398]
- PyTorch-Forecasting version: 0.8.4
- PyTorch version: 1.2.3
- Python version: 3.x
- Operating System: Ubuntu 16.x

### Expected behavior

I have a basic dataset, with only known and unknown reals, and a column of group names and for idx.  I get different errors depending on how I try to parameterize the groups in the TimeSeriesDataSet.  If I run the code like beloe, I get the error about string coversion. 
 If I add a group normalizer, I get ```KeyError: "Unknown category '0' encountered. Set `add_nan=True` to allow unknown categories"```.  There is no group "0", and there are no categories.  I don't want to normalize anyway.

I did try setting the groups as categories, and that did not work either (all were converted to NaN, b/c I had to allow NaN for categorical encoders, or got another error).  But the groups are not categories, so really I don't want that, just basic grouping.  

Every row has a group.   Rows may contain features which are zero.

### Code to reproduce the problem

```py
training = TimeSeriesDataSet(
    data,
    time_idx="date",
    group_ids=["symbol"],
    target="volume",
    #group_ids=["agency", "sku"],
    min_encoder_length=50,
    max_encoder_length=100,
    min_prediction_length=20,
    max_prediction_length=20,
    time_varying_known_reals=meta["knownReals"],
    time_varying_unknown_reals=meta["unknownReals"],
    target_normalizer=None,
    add_encoder_length=True,
)
```

**Comment by jdb78** [comment]
Can you convert the `symbol` columns to a `str` type? That might solve the issue.

Can you also post the head of your dataframe and its dtypes. Might be useful for debugging.
