### ISSUE TITLE
return_index in predict returns only first index of all predicted sequence

### ISSUE THREAD

**Issue by Elllifa** [jdb78/pytorch-forecasting#416]
First of all, thank you for this realization!
I think, I found a bug, or may be I do something wrong. 

- PyTorch-Forecasting version: 0.8.3
- PyTorch version: 1.8.0+cu111
- Python version: 3.8.3
- Operating System: Win 10 x64

### Expected behavior

I executed code in stallion.ipynb in order to understand how to predict on new data. I tested option "return_idx in
best_tft.predict(new_prediction_data, return_index=True). As I understand, it must return all time_idx for which the prediction has been done.

### Actual behavior

However, it returns only the first time_idx  of prediction(60 in the example). I think this may be due to incorrect dataloader, which model sees while doing prediction. As I've seen in base_model.py in predict(...) it takes these indices from dataloader.dataset, but I'm not really sure.

### Code to reproduce the problem

```
Section "Insufficient quantity of time_idx"
https://colab.research.google.com/drive/19Uu_iZK7GD8A4xBB2h_P2-lee-2-z1jA?usp=sharing
```
Could you please check the above behavior and if it's proper, explain me what should I do to get all indices?

**Comment by dempseyryan** [comment]
My understanding is that the indices returned by `predict()` are just meant to be used as a key to determine which timeseries is where. The actual time indices would be identical for each timeseries, but the order of the timeseries' is different from the order in which they were input, so the index tells you which timeseries is available at which index.

I might be wrong but using it this way has worked for me.

Hope this helps!

**Comment by jdb78** [comment]
@dempseyryan is right, you get the first `time_idx` for each series which is all you need to know in order to determine the subsequent `time_idx` which is simply increasing by `1` for each time step.

**Comment by Elllifa** [comment]
@dempseyryan, @jdb78, Thank you for your explanations. Now I understand.
