### ISSUE TITLE
[Question] Known and unknown variables in TimeSeriesDataSet vs model performance

### ISSUE THREAD

**Issue by zvit3k** [jdb78/pytorch-forecasting#422]
- PyTorch-Forecasting version: 0.8.3
- PyTorch version: 1.1.8
- Python version: 3.7.10
- Operating System: Debian 10

Hi guys, 

I have a question related to the variables which can be set in TFT model. After reading this topic https://github.com/jdb78/pytorch-forecasting/issues/411 I have gained more insights into what is a time-varying known and unknown variables.

In my case most of my variables are calculated historical data, so I pass them as time-varying unknown reals. For the time-varying known reals I only have date related variables - day of week, day of year, month etc. 

With such configuration model will still perform well?

Unfortunately, my decoder looks poor and predictions are also not good, which bothers me a lot. It is based only on time/date related variables and that maybe is the issue.

Should model be enriched with more known data and more static variables to improve the decoder? Or should I look into completely different area of bad performance?

Thanks!

**Comment by arniwesth** [comment]
What are you trying to predict?

**Comment by jdb78** [comment]
You definitely want to to add time_idx to your known variables. Could you post your definition of the TimeSeriesDataSet here?

**Comment by zvit3k** [comment]
@jdb78 

Hi,

I use the time_idx as a known variable already :) I cannot share TimeSeriesDataSet due to sensitive information, I will try to overcome this issue somehow. What is more, my question was related to the general aspects of known variables importance or huge disproportion between many unknown variables combined with a few known (and mainly time related) variables. 

Thanks
