### ISSUE TITLE
Conflict saving hparams with newest PyLightning versionss

### ISSUE THREAD

**Issue by pnmartinez** [jdb78/pytorch-forecasting#428]
- PyTorch-Forecasting version: 0.8.3
- PyTorch version: 1.2.1+
- Python version: 3.8
- Operating System: Ubuntu 18.04 LTS

### Expected behavior

Running old-tested notebooks, everything should work fine, like a couple months ago.

### Actual behavior

An incompatibility of sorts between `PytorchForecasting` and last `PytorchLightning` versions.

You can find the **logs and model inits in the issue I opened** on `PytorchLightning` repo [here](https://github.com/PyTorchLightning/pytorch-lightning/issues/6772).

### Solution

**Downgrading PytorchLightning** from `1.2+` to `1.1.8` did it for me, as indicated in this [StackOverflow](https://stackoverflow.com/a/66383407/10440588) response.

**Comment by jdb78** [comment]
True, not all versions are backwards compatible as PyTorchLightning is changing a fair bit. You can look at the current notebooks to see how to adjust the trainer.

**Comment by pnmartinez** [comment]
I posted this in case somebody else bumps into the same case. I guess problems like this inescapable when using 3 different API layers one on top of the other...

Thanks, as usual @jdb78 . Keep doing this amazing work!
