### ISSUE TITLE
Bug with TFT raw predictions for multitarget predictions

### ISSUE THREAD

**Issue by polal2is** [jdb78/pytorch-forecasting#432]
- PyTorch-Forecasting version: 0.8.4 from pip install
- Operating System: Ubuntu 18.04.4 LTS
- Python: 3.9.1

Hi,
There seem to be a bug with TFT for multi targets (2 reals in my case) when using:

`raw_predictions, x = best_tft.predict(val_dataloader, mode="raw", return_x = True)`

The following error is raised:

> AttributeError                            Traceback (most recent call last)
> <ipython-input-15-211f4828176d> in <module>
>       1 # raw predictions are a dictionary from which all kind of information including quantiles can be extracted
> ----> 2 raw_predictions, x = best_tft.predict(val_dataloader, mode="raw", return_x = True)
>       3 raw_predictions
> 
> ~/miniconda3/envs/forecast/lib/python3.9/site-packages/pytorch_forecasting/models/base_model.py in predict(self, data, mode, return_index, return_decoder_lengths, batch_size, num_workers, fast_dev_run, show_progress_bar, return_x, **kwargs)
>     957                         if isinstance(out[name], (tuple, list)) and out[name][0].device != torch.device("cpu"):
>     958                             out[name] = [oi.to("cpu") for oi in out[name]]
> --> 959                         elif out[name].device != torch.device("cpu"):
>     960                             out[name] = out[name].to("cpu")
>     961                 elif isinstance(out, torch.Tensor) and out.device != torch.device("cpu"):
> 
> AttributeError: 'list' object has no attribute 'device'

Removing `mode="raw"` solves the issue but one cannot access quantiles then I guess ?

Thanks in advance!

**Comment by jdb78** [comment]
Thanks for identifying this issue. Will be fixed soon with the next release
