### ISSUE TITLE
Unscale predictions for obtaining unscaled evaluation metrics

### ISSUE THREAD

**Issue by andresC98** [jdb78/pytorch-forecasting#445]
Hi! First of all, again, thanks very much for the incredible work done on this library, is amazing and it is currently being of great use for my thesis project.

My question is quite simple, however I couldn't find any help on the documentation on how to address it:

**Is it possible to obtain the un-normalized error metrics for our models when the dataset is using e.g. group normalizers or target normalizers?** For example, after model training, I evaluate the model with

> predictions = best_tft.predict(val_dataloader)
tft_mae = (actuals - predictions).abs().mean().numpy()

but of course I guess the MAE obtained there is scaled. Is there any easy way to unscale it?

Thanks in advance!

**Comment by jdb78** [comment]
The error metrics are always unscaled. The scaled metrics are not of much use. If you really want to calculate the metric on the raw output of the network, you could do so by calling the module like `x, y  = next(iter(val_dataloader))`. `y_hat = best_tft(x)["predictions"]` and compare this to `(y - x["target_scale"][:, 0]) / x["target_scale"][:, 1]`.

**Comment by andresC98** [comment]
@jdb78 thanks for the response. However, when I try that I get the following error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-21-7c66bf7a2436> in <module>
      3 predictions = best_tft(x)["prediction"]
      4 
----> 5 unscaled_y_true = (y - x["target_scale"][:, 0])/x["target_scale"][:, 1]

~/opt/anaconda3/envs/eB2-Data/lib/python3.8/site-packages/torch/tensor.py in __rsub__(self, other)
    509         if type(self) is not Tensor and type(other) is not Tensor and has_torch_function(relevant_args):
    510             return handle_torch_function(Tensor.__rsub__, relevant_args, self, other)
--> 511         return _C._VariableFunctions.rsub(self, other)
    512 
    513     def __rdiv__(self, other):

TypeError: rsub() received an invalid combination of arguments - got (Tensor, tuple), but expected one of:
 * (Tensor input, Tensor other, *, Number alpha)
 * (Tensor input, Number other, Number alpha)

```
(Python version: Python 3.8.5, Pytorch-Library version: =0.8.4, Torch version: 1.7.1)

**Comment by jdb78** [comment]
Make sure you add the correct dimensions. The target scale is for each series the same.

**Comment by andresC98** [comment]
I don't get it, I have checked dimensions and they match, however I cannot perform the substraction.

**Comment by jdb78** [comment]
Yes, think it makes not much sense to calculate the metric in the normalized space.

FYI: `y` consists of the target and the weights.

**Comment by veds12** [comment]
Hi @jdb78. I understand that the error metrics should be calculated in the original un-scaled space while evaluating. But could you please explain why it won't make sense to backpropagate on loss calculated in scaled space (i.e. calculating errors during test time)? Calculating loss in original space might lead to problems like exploding loss (going to NaN); especially in series where the values are of the order of ten thousand or above. I didn't face this problem (exploding losses and exploding gradients) in normal training but found it to be very prominent in applications like Meta-Learning.
