### ISSUE TITLE
trying to understand min/max encoder/prediction length

### ISSUE THREAD

**Issue by turmeric-blend** [jdb78/pytorch-forecasting#448]
Hi, I am trying to understand the `TimeSeriesDataSet`'s parameters - `min_encoder_length`/`max_encoder_length`/`min_prediction_length`/`max_prediction_length`.

From my understanding of multi-step timeseries forecasting, there is usually an input window size of the data (lets call this lookback) and prediction label window size (lets call this horizon). If the lookback size is 10 and horizon size is 5, then a time-series of length 15 would be split into (t-9, t-8, ... ,t-1, t) for lookback, and (t+1, t+2, ... t+5) for horizon. Then, the lookback would be passed into the model and the loss computed using model output and horizon. Note that the total time-series maybe of length 3000, in which case every sample input to the model would be 10, taking random 10 (lookback) window from the 3000 on every iteration.

Does `encoder_length` mean lookback and `prediction_length` mean horizon for the context of `pytorch-forecasting`? If so, why is there a `min` and `max` associated with it?

(I have seen the tutorials but I it is still unclear to me sorry :/)

**Comment by jdb78** [comment]
Yes the `encoder_length` is the look-back-window and `prediction_length` the look-ahead-window. Some algorithms support flexible window sizes and `min` and `max` allows you to do that. If you want a fixed window length, set them to the same numbers.

**Comment by turmeric-blend** [comment]
thanks

**Comment by szemyd** [comment]
What could be the reason I get an error when I set the min_encoder_length larger than 0? 
The timeseries I am using has the same length. Loading works if I set it to 0. 

(Thanks for the clarification of these variables!)
