### ISSUE TITLE
Question: LSTM layer cannot set to 0

### ISSUE THREAD

**Issue by ss20212** [jdb78/pytorch-forecasting#450]
I am a beginner deep learning learner. Currently, I am learning with the tutorial of "Demand forecasting with the Temporal Fusion Transformer. Can LSTM layer set to 0?

I got this error when I set it to 0. Thanks.
---------------------------------------------------------------------------

IndexError                                Traceback (most recent call last)

<ipython-input-26-3b79e81f3e3a> in <module>()
     27     loss=QuantileLoss(),
     28     log_interval=10,  # uncomment for learning rate finder and otherwise, e.g. to 10 for logging every 10 batches
---> 29     reduce_on_plateau_patience=4,
     30 )
     31 print(f"Number of parameters in network: {tft.size()/1e3:.1f}k")

6 frames

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/rnn.py in flatten_parameters(self)
    144         # or the tensors in _flat_weights are of different dtypes
    145 
--> 146         first_fw = self._flat_weights[0]
    147         dtype = first_fw.dtype
    148         for fw in self._flat_weights:

IndexError: list index out of range

**Comment by jdb78** [comment]
No, you cannot remove the LSTM layer from the architecture completely.

**Comment by ss20212** [comment]
Thank ypI
