### ISSUE TITLE
predict get multi values 

### ISSUE THREAD

**Issue by iambyd** [jdb78/pytorch-forecasting#457]
- PyTorch-Forecasting version:0.8.4
- PyTorch version:1.8.1
- Python version:3.8.5
- Operating System:centos8

### Expected behavior

I make timeserisedataset with same params like : max_encoder_length=min_encoder_length=4,and max_prediction_length=min_prediction_length=2，when i predict, return  multi data： 

1. One is

- same group_ids 
- same values

2. another 

- same group_ids 
- one have value,but another is nan

**Comment by jdb78** [comment]
Could you provide a code example? and point out what exactly evaluates to `nan`?

**Comment by iambyd** [comment]
i use in a wrong way, now have fix it, thanks!
