### ISSUE TITLE
 # plot 10 examples error in Evaluate Results

### ISSUE THREAD

**Issue by leechaelim** [jdb78/pytorch-forecasting#481]
- PyTorch-Forecasting version:
- PyTorch version:
- Python version:
- Operating System:

Hi, Thanks for this library!!!
I want to predict the market price(Open price) of a stock.
I'm trying to apply my data to the N-beats tutorial.
but, I can't get 10 plots in the result evaluation step.

I executed code 

```
for idx in range(10):  # plot 10 examples
    best_model.plot_prediction(x, raw_predictions, idx=idx, add_loss_to_title=True);
```

### Actual behavior
![image](https://user-images.githubusercontent.com/58203135/116971178-26ed0f80-acf4-11eb-8535-4d59ac477557.png)

Why is there only one plot?
And can you tell me why the smape error increases abnormally??

Compare below with baseline error:
tensor(14734.1045)
Baseline error was:
tensor(0.2449)

here is my data and Colab notebook.

[Nbeats_Open.zip](https://github.com/jdb78/pytorch-forecasting/files/6419488/Nbeats_Open.zip)

**Comment by leechaelim** [comment]
here is my colab notebook.
https://colab.research.google.com/drive/1zpGWkSnq_LMuPbvAdbTfifMC90WGBcmt



![캡처](https://user-images.githubusercontent.com/58203135/117683828-67b2c000-b1ef-11eb-9057-b2b10ceb1166.PNG)
In the tutorial, the error calculation was done like a picture.
But it's different from baseline_error.
Why did you do that?

1. (actuals - predictions).abs().mean()

2. SMAPE()(predictions, actuals)

1 and 2 have different results.
What's right?

Thank you for your comment!

**Comment by jdb78** [comment]
SMAPE is defined as `((y - y_hat).abs()/(y.abs() + y_hat.abs())).mean()`, so it is not surprising that 1 (MAE) is not equal to 2 (SMAPE).

**Comment by leechaelim** [comment]
thank you!!!! I solved this issue
Thanks for your comments :) 👍
