### ISSUE TITLE
DeepAR Example Failure on Colab - Expected all tensors to be on the same device

### ISSUE THREAD

**Issue by Aljgutier** [jdb78/pytorch-forecasting#501]
- PyTorch-Forecasting version: pytorch-forecasting-0.8.5
- PyTorch version: pytorch-lightning-1.3.1
- Python version: 3.71
- Operating System: Linux
- Cloud Platform: Google Colab

First, PyTorch-forecasting is an awesome package and I'm beginning to use it to compare forecasting model performance on realistic large covariate data sets. I've previously had much experience developing ML and DL-based regression style, forecasting models - for retail, finance/stock, biosensing, and IoT - time-series real-life applications with many co-variates. I have some expertise in traditional forecasting methods, but not as much on the latest LSTM methods. I especially appreciate easily installing PyTorch-Forecasting independent of the target platform, e.g., AWS, GCP, Azure, or private computing environment.

I'm doing my experimentation on Colab and therein I'm running into the problem running the DeepAR example [DeepAR Example](https://github.com/jdb78/pytorch-forecasting/blob/master/examples/ar.py) as described below.

### Expected behavior
I'm running the following code from the DeepAR example in Colab with a GPU runtime environment. It should work out of the box, however, I'm getting a runtime error since it seems the data is on CPU and the model is on the GPU. See further ellaboration below.

### Actual behavior

I get the following error:   

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### Code to reproduce the problem
[DeepAR Example](https://github.com/jdb78/pytorch-forecasting/blob/master/examples/ar.py) code ... 

```
torch.set_num_threads(10)
trainer.fit(
    deepar,
    train_dataloader=train_dataloader,
    val_dataloaders=val_dataloader,
)
```

This has already been fixed in the main branch. I installed the main branch in Colab  (!pip install git+git://github.com/jdb78/pytorch-forecasting/) and the issue is resolved. It will be nice when this main branch is pushed back out to the released PyTorch-Forecasting package. Thank you again for all your help!!!

**Comment by jdb78** [comment]
Will make the release shortly!
