### ISSUE TITLE
In the stallion tutorial, should special days be accounted for when predicting new data?

### ISSUE THREAD

**Issue by tszumowski** [jdb78/pytorch-forecasting#510]
- PyTorch-Forecasting version: 0.8.5
- PyTorch version: 1.8.1
- Python version: 3.8.6
- Operating System: macOS

### Expected behavior

I executed the [stallion tutorial](https://pytorch-forecasting.readthedocs.io/en/latest/tutorials/stallion.html). But when running the [Predict on New Data](https://pytorch-forecasting.readthedocs.io/en/latest/tutorials/stallion.html#Predict-on-new-data) section, I inspected `decoder_data` and notice that every element has the `christmas` special day set, regardless of month. 

I attached a screenshot of a snippet:
![image](https://user-images.githubusercontent.com/10282962/118641485-2fd7e980-b7a8-11eb-8792-c69346b42c94.png)

### Actual behavior

The code comment says:
```
# select last known data point and create decoder data from it by repeating it and incrementing the month
# in a real world dataset, we should not just forward fill the covariates but specify them to account
# for changes in special days and prices
```

I got the impression that the special days need to be updated as well as the `month` field, but I didn't see where the special days covariates are specified. 

### Code to reproduce the problem

Run the current tutorial and print a snippet of `decoder_data`

**Comment by jdb78** [comment]
Yes, you should modify them. I am just too lazy here. Added a comment in the docs.
