### ISSUE TITLE
Missing import pickle

### ISSUE THREAD

**Issue by rickyxume** [jdb78/pytorch-forecasting#513]
`Missing import declaration`

![image-20210520010825291](https://i.loli.net/2021/05/20/QE4mxkTNc9y3F7L.png)

There is a little problem about code sample in the part of  [TFT Tutorial](https://pytorch-forecasting.readthedocs.io/en/latest/tutorials/stallion.html). A line of code is missing in Hyperparameter tuning.

It took me half a day to search for best hyperparameters, but give me a bad result. I think it's a great discouragement for me, as are other beginners. I hope you can add `**import pickle**` immediately. Thx!

**Comment by jdb78** [comment]
Good catch! Thank you!
