### ISSUE TITLE
Scaling Issues

### ISSUE THREAD

**Issue by DeastinY** [jdb78/pytorch-forecasting#528]
```
UserWarning: scale is below 1e-7 - consider not centering the data or using data with higher variance for numerical stability
  warnings.warn(
```
When running my model I get this error, but checking all data right before the creation of the TimeSeriesDataSet using sklearn's StandarScaler no scale is even below 1e-2.
Any pointers to further debug would be great.

**Comment by DeastinY** [comment]
float16 overflow error

**Comment by PMA65** [comment]
> float16 overflow error

@DeastinY 
Hi, facing the same problem were exactly is this float16 overflow is happening ?
Did you manage to fix this problem ?
thanks

**Comment by DeastinY** [comment]
hi @PMA65 sorry for the late reply, was on holidays :) 
Iirc it was something along those lines: https://github.com/scikit-learn/scikit-learn/issues/13007

**Comment by Sheldonfrith** [comment]
I'm also struggling with this issue. If there's any additional info you could share on how you solved it that would be very helpful. If/when I eventually solve it I will try to post my solution here. I assume I will have to add a custom scaler to my TimeSeriesDataFrame and either use the updated version of SKLearn Standard Scaler (as referenced in the link you shared) or implement the fix myself. Still trying to figure out how to add custom scalers to the TimeSeriesDataFrame, as the docs say the param should be a dict, but I'm not clear on what the keys to that dict should be....
