### ISSUE TITLE
Nbeats forward() method needs and returns a dict(). That goes against PL ability to log the computation graph

### ISSUE THREAD

**Issue by pnmartinez** [jdb78/pytorch-forecasting#529]
- PyTorch-Forecasting version: 0.8.4
- PyTorch Lightning version: 1.1.8
- Python version: 1.8.1
- Operating System: Ubuntu 18.4

### Expected behavior

Trying to **log the computation graph to `TensorBoardLogger` class**, which is done by passing `log_graph = True`.

### Actual behavior

Error: the TensorBoardLogger needs the model (Nbeats in my case) to have defined a `self.example_input_array`. I did that (easy peasy) but more convoluted errors arise, all the way down to Pytorch API. 

It seems that the **`.forward()` method** returning a `dict()` (with keys "prediction", "target_scale"... the expected format on `pytorch_forecasting`), **can only do the graph properly if returning a Tensor**.

Pytorch also recommends (see [here](https://pytorch.org/tutorials/beginner/examples_nn/two_layer_net_module.html), or [here](https://pytorch.org/docs/stable/notes/extending.html)) the forward method to accept and return Tensors, or tuples of them.

I know this is a **major modification** on the lib intermediate objects, and maybe there are other ways to get the computation graph, but I think **it would be a good change for the long term**.

Cheers!

**Comment by jdb78** [comment]
This is being fixed in the upcoming release. It's actually sufficient to use a namedtuple

**Comment by pnmartinez** [comment]
Nice!

This will be awesome in the case of custom models.
________________________________

**Comment by pnmartinez** [comment]
Hi @jdb78 

So, in the new version, is the `log_graph = True` flag supposed to be working on the `TensorBoardLogger`?

I am testing in a fresh environment, and can't seem to log it properly.
