### ISSUE TITLE
Wrong bug report

### ISSUE THREAD

**Issue by wangbingnan136** [jdb78/pytorch-forecasting#540]
![image](https://user-images.githubusercontent.com/42114835/120457716-42b60500-c3c9-11eb-823a-1ee111bddab1.png)

if I use columns that the dataframe dose not have.
![image](https://user-images.githubusercontent.com/42114835/120457860-5eb9a680-c3c9-11eb-8a37-441895345447.png)
the error report is
![image](https://user-images.githubusercontent.com/42114835/120457889-66794b00-c3c9-11eb-93a0-9212422e0483.png)

**Comment by wangbingnan136** [comment]
I think the "raise valueError" function need to be fixed.

**Comment by jdb78** [comment]
Should be fixed by #518
