### ISSUE TITLE
Is there a way to perform tft prediction on GPU?

### ISSUE THREAD

**Issue by QitianMa** [jdb78/pytorch-forecasting#541]
- PyTorch-Forecasting version: 0.8.5
- PyTorch version: 1.8.1
- Python version: 3.8.10
- Operating System: linux 3.10.0-1160.25.1.el7.x86_64

In tft tutorial tft predict is called on TemporalFusionTransformer. For the object returned by method from_dataset, the device attributes are default to "cpu". If I call predict method on it, the computation will be performed on CPU instead of GPU. Is there a way to do prediction on GPU? Thank you.

**Comment by jdb78** [comment]
Just move it to the GPU with `tft.to(device)` and then use the `predict()` method

**Comment by QitianMa** [comment]
Thank you. This solves my problem.
