### ISSUE TITLE
How to change the stride length of the lookback window

### ISSUE THREAD

**Issue by veds12** [jdb78/pytorch-forecasting#563]
- PyTorch-Forecasting version: 0.9.0
- PyTorch version: 1.8.1
- Python version: 3.1 
- Environment: Google Colaboratory

How can I change the slide length of the lookback window? It is one by default, i.e., if my time series is `1, 2, 3, 4, 5, 6, 7, 8, 9` with a lookback window of length of 5 and a prediction horizon of length 2, the sampled encodings will be `1, 2, 3, 4, 5` , `2, 3, 4, 5, 6` and `3, 4, 5, 6, 7`. However, I want to change the length of each slide s.t. the lookback window moves ahead with a stride of 2. So, the new sampled encoding will be `1, 2, 3, 4, 5` and `3, 4, 5, 6, 7`.

I went through the API of `TimeSeriesDataSet.to_dataloader()` but could find any option / flag to change the stride size.

**Comment by veds12** [comment]
Solved in #229

**Comment by korosig** [comment]
Have you solved this issue?

**Comment by veds12** [comment]
Yes. @korosig please see this:
https://github.com/jdb78/pytorch-forecasting/issues/229#issuecomment-753603424
You can define a new batch sampler class which inherits from `TimeSynchronousBatchSampler` and redefine the `__iter__` method with the desired stride length

**Comment by korosig** [comment]
> Yes. @korosig please see this: [#229 (comment)](https://github.com/jdb78/pytorch-forecasting/issues/229#issuecomment-753603424) You can define a new batch sampler class which inherits from `TimeSynchronousBatchSampler` and redefine the `__iter__` method with the desired stride length

Do you have a version with this modification somewhere? Github repo or Google colab?

**Comment by blacksnail789521** [comment]
> Yes. @korosig please see this: [#229 (comment)](https://github.com/jdb78/pytorch-forecasting/issues/229#issuecomment-753603424) You can define a new batch sampler class which inherits from `TimeSynchronousBatchSampler` and redefine the `__iter__` method with the desired stride length

Can you give us the minimal toy example of how we implement a `TimeSynchronousBatchSampler`?
I couldn't find any resource about `TimeSynchronousBatchSampler`.
Thanks for your time.

FYI, I've looked into [PyTorch's doc](https://pytorch.org/docs/stable/data.html#torch.utils.data.Sampler) and couldn't find `TimeSynchronousBatchSampler`.

**Comment by blacksnail789521** [comment]
Just a reminder that it's `TimeSynchronizedBatchSampler` instead of `TimeSynchronousBatchSampler`.
It took me some time digging into the [doc](https://pytorch-forecasting.readthedocs.io/en/latest/api/pytorch_forecasting.data.samplers.TimeSynchronizedBatchSampler.html?highlight=TimeSynchronizedBatchSampler#), so I hope this info would help someone save some time.
