### ISSUE TITLE
Different result with same model input with dropout =0 and seed is also set

### ISSUE THREAD

**Issue by AsthaSatsangi** [jdb78/pytorch-forecasting#564]
- PyTorch-Forecasting version:
- PyTorch version:
- Python version:
- Operating System:
While comparing result of same input in only CPU, we get different result each time.
 Is there a way to get same output using the same input.

I have seed set to 42pl.seed_everything(42) and dropout as 0 but yet each time I run the code I get different prediction for this,
stop randomization is also set to true.
 Is there a way to get same output using the same input.

We have tried few methods from the link here:
https://pytorch.org/docs/stable/notes/randomness.html
and have also set seed like:
pl.seed_everything(123)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(123)
CUDA = torch.cuda.is_available()
import random
random.seed(123)
np.random.seed(123)
torch.manual_seed(123)
if CUDA:
  torch.cuda.manual_seed(123)
  torch.cuda.manual_seed_all(123)
  torch.backends.cudnn.deterministic = True
  torch.backends.cudnn.benchmark = False  
torch.use_deterministic_algorithms(True)

**Comment by jdb78** [comment]
Have you tried the solution from #401?

**Comment by AsthaSatsangi** [comment]
Thanks it was solved
