### ISSUE TITLE
The TFT draws a plot of data that is not in the dataset.

### ISSUE THREAD

**Issue by anykeygitwalker** [jdb78/pytorch-forecasting#586]
Hi! Thanks for the great work on this package!

I'm new to python and data science, and I have a problem with the TFT:
The TFT draws a plot of data that is not in the dataset.

- PyTorch-Forecasting version: 0.9.0
- PyTorch version: 1.9.0
- Python version: 3.7.6 64-bit
- Operating System: Ubuntu 20.04.2 LTS

### Expected behavior
Sometimes*, when I call*:
best_tft.plot_prediction(x, raw_predictions, idx=0, add_loss_to_title=True)
I get a correct plot representing my dataset, like this one:
![1](https://user-images.githubusercontent.com/86418804/123279668-be125e80-d510-11eb-9900-3d313b1576ac.png)

### Actual behavior
This graph and the graph above should be almost the same (little time offset). But it is not:
![2](https://user-images.githubusercontent.com/86418804/123283259-e780b980-d513-11eb-8c30-38ee9cb2031b.png)
Sometimes* best_tft.plot_prediction draws the wrong plot. Which looks like a plot from a different dataset. But the dataset is the same. This happens occasionally*, but sometimes* I get the correct plot. If I change the dataset (more rows, add a group) the wrong plot may be displayed all the time.

*All words(call, sometimes, occasionally) imply "Run all cells" in my .ipynb notebook with TFT.

Maybe someone knows where to look for a solution? Thank you!

**Comment by JakeForsey** [comment]
Is it possible that the actual data is correct? But because of the y axis scale it looks different from what you expect?

The y axis scale will depend on the confidence interval, so when that is very wide, your data will look very flat.
