### ISSUE TITLE
AttributeError: module 'pytorch_forecasting.data' has no attribute 'examples'

### ISSUE THREAD

**Issue by Saatvik-droid** [jdb78/pytorch-forecasting#598]
- PyTorch-Forecasting version: 0.9.0
- PyTorch version: 1.9.0+cu102'
- Python version: 3.8
- Operating System: Linux

### Expected behavior

I am trying to import numerous functions and classes from pytorch_forecasting. So as to make it less tedious I am doing importing the entire package under an alias and using the dot (.) notation.

### Actual behavior

I was expecting to access methods and classes successfully but rather it gives me an AttributeError `AttributeError: module 'pytorch_forecasting.data' has no attribute 'examples'`. I can access the attribute if I import it specifically such as using `from pytorch_forecasting.data.examples.get_stallion_data`.

### Code to reproduce the problem

```
import pytorch_forecasting as torchf
x = torchf.data.examples.get_stallion_data()
```

**Comment by jdb78** [comment]
Think this is a potentially due to a misunderstanding of python. You have to use
`from pytorch_forecasting.data.examples import get_stallion_data`

**Comment by Saatvik-droid** [comment]
So the issue is I want to use numerous functions from pytorch_forecasting, so instead of having to do a number of `from ... import ...` imports, I want to do a single import of pytorch_forecasting and then call the methods using dot(.) notation. I think this is valid python.

**Comment by jdb78** [comment]
See https://stackoverflow.com/questions/4871369/python-error-attributeerror-module-object-has-no-attribute
