### ISSUE TITLE
Cold start problem

### ISSUE THREAD

**Issue by Gsj49** [jdb78/pytorch-forecasting#605]
- PyTorch-Forecasting version: 0.9.0
- PyTorch version: 1.9.0
- Python version: 3.8.0
- Operating System: macOS Catalina 10.15.7

### Expected behavior

I had a data set containing 10,000 time series, each time series contains records of many time steps up to a certain recent day. A few days ago, thanks to the tutorials, I trained the TFT model successfully and got a pretty good result based on that dataset. However, when I obtained the new data on which I originally planned to make predictions, I found that some of the time series ids were not in the training dataset, and this led to errors. 

To solve this problem, I added ```categorical_encoders={"id": NaNLabelEncoder(add_nan=True)}``` to the parameter of ```TimeSeriesDataSet``` and retrained the model, but then the model seemed to perform very bad on validation set (more than 10times larger MAPE compared to the previous model).

I thought maybe this doesn't work well, so I remove ```categorical_encoders={"id": NaNLabelEncoder(add_nan=True)}```, and then I attempted to fit a model that didn't take the column of id ```"id"``` as input (previous model: ```static_categoricals=["id"]```  current model: ```static_categoricals=[]```)  and therefore ids were only use for grouping in my understanding. I expected that this model could work well when facing data with new ids.

### Actual behavior

When making predictions on data with ```id==“anchor”```(this id is not in the training set), I get the error message:
```
KeyError: "Unknown category 'anchor' encountered. Set `add_nan=True` to allow unknown categories"
```

### Code to reproduce the problem
The current definition of ```TimeSeriesDataSet``` in my code is shown below:
```
training = TimeSeriesDataSet(
    data[lambda x: x.time_idx <= training_cutoff],
    time_idx="time_idx",
    target="y",
    group_ids=["id"],
    min_encoder_length=min_encoder_length,  
    max_encoder_length=max_encoder_length,
    min_prediction_length=1,
    max_prediction_length=max_prediction_length,
    static_categoricals=[],
    static_reals=[],
    time_varying_known_categoricals=[],
    variable_groups={},  
    time_varying_known_reals=["time_idx"],
    time_varying_unknown_categoricals=[],
    time_varying_unknown_reals=["y"],
    target_normalizer=GroupNormalizer(groups=["id"], transformation=None), 
    # categorical_encoders = {"id": NaNLabelEncoder(add_nan=True)},
    allow_missing_timesteps=True,
)
```
I have two questions (i) I didn't use any categorical column as input, so why does the error message indicate that I encountered an unknown category?(ii) is there any method to solve my cold start problem？(Maybe with ```NaNLabelEncoder``` but I don't know how to improve its very bad performance. Once I use ```NaNLabelEncoder``` with ```add_nan=True```, the loss will be very large with nothing being changed in any other part of my code). I would be very grateful if you can answer. Thanks!

**Comment by bgeils** [comment]
same issue solved with
```
categorical_encoders={
        'product_id': NaNLabelEncoder().fit(df.product_id),
        'shop_id': NaNLabelEncoder().fit(df.shop_id),
        'product_type': NaNLabelEncoder().fit(df.product_type)
    },
```
