### ISSUE TITLE
expected dtype object, got 'numpy.dtype[int64]'

### ISSUE THREAD

**Issue by fxfviolet** [jdb78/pytorch-forecasting#633]
I create  a dataset  according to tutorials, but it shows following error:

expected dtype object, got 'numpy.dtype[int64]'
CPUDispatcher(<function _find_end_indices at 0x000001DCE3E15D90>) returned a result with an error set

**Comment by MelchiorReihlenBorgers** [comment]
Do you have the code maybe? Otherwise it is hard to see where the problem might be coming from.

**Comment by fxfviolet** [comment]
I find the above error is caused by the high version of numpy and pandas. I reduced the version to numpy==1.19.3 and pandas==1.2.5, then no above error again. 
Thanks a lot!
