### ISSUE TITLE
Always raise warnings with NaNLabelEncoder(add_nan=True)

### ISSUE THREAD

**Issue by Gsj49** [jdb78/pytorch-forecasting#635]
- PyTorch-Forecasting version: 0.9.0
- PyTorch version: 1.9.0
- Python version: 3.8
- Operating System: MacOs

I think there might be some problem with NaNLabelEncoder because it always raises warnings. Test code shown below:

Input:
```
df = pd.DataFrame({"id":["a","b","c"],"y":[1,2,3]})
encoder = NaNLabelEncoder(add_nan=True).fit(df["id"])
print(encoder.classes_)
```
output:```{'nan': 0, 'a': 1, 'b': 2, 'c': 3}``` (this works as expected)

Input:
```
print(encoder.transform(df["id"]))
```
or
```
print(encoder.transform(["a","b","c"]))
```
output:```[1 2 3]``` with warnings:
```
/Users/.conda/envs/pythonProject/lib/python3.8/site-packages/pytorch_forecasting/data/encoders.py:119: UserWarning: Found 3 unknown classes which were set to NaN
  warnings.warn(
```
I don't understand why I could see this warning. I didn't input any unknown classes since ```["a","b","c"]``` these three classes were known seen from the output of ```print(encoder.classes_)``` . I want to make sure whether the model will be influenced by this warning. Thanks in advance for your reply.

**Comment by Gsj49** [comment]
I found that the line 117 of ```pytorch_forecasting/data/encoders.py```, the source code where ```NaNLabelEncoder``` locates is 
```
cond = ~np.isin(y, self.classes_)
```
but self.classes_ is a dict and y is not, so ```cond.any()``` is always True and a warning is raised.

Judging from the subsequent code, the effect of the model should not be affected by ```add_nan =True```. However, this led to model's bad performance from my testing result.  I still can't understand why this is happening

**Comment by gcbirzan** [comment]
Are you saying it performed better after fixing that piece of code?

**Comment by tianshudetian** [comment]
I use the “month” category and always warn.
