### ISSUE TITLE
Example from the documentation does not work

### ISSUE THREAD

**Issue by protw** [jdb78/pytorch-forecasting#647]
- PyTorch-Forecasting version: 0.9.0
- PyTorch version: 1.9.0
- Python version: 3.9.6
- Operating System: windows 10 home v. 20h2

### Expected behavior

I executed code from the following article in the documentation: https://pytorch-forecasting.readthedocs.io/en/latest/tutorials/stallion.html in order to test _pytorch-forecasting_ package and expected just to repeat this demo

### Actual behavior

However, I encountered the warning:

![image](https://user-images.githubusercontent.com/1643432/129957479-1ef4e9e6-f6dd-4564-87ca-b3be1f72cf12.png)

ended by the error:

![image](https://user-images.githubusercontent.com/1643432/129957706-a6ca8020-4c66-4362-9920-dc99094336ba.png)

**Comment by gcbirzan** [comment]
You need `pandas==1.2.5` in your requirements file.

**Comment by protw** [comment]
@gcbirzan , thanks a lot - it works, I passed this line successfully
