### ISSUE TITLE
dictionary update sequence element #0 has length 1; 2 is required

### ISSUE THREAD

**Issue by cristianegea** [jdb78/pytorch-forecasting#665]
I'm trying to forecast a time series. For that, I decided to redo the tutorial "[Demand forecasting with the Temporal Fusion Transformer](https://pytorch-forecasting.readthedocs.io/en/latest/tutorials/stallion.html)".  As the version that is on the [GitHub](https://github.com/jdb78/pytorch-forecasting) seems to be more recent, I solved the instructions that are there. However, when executing the instruction `trainer.fit(tft, train_dataloaders = train_dataloader, val_dataloaders = val_dataloader,)`, the following error message appears: "dictionary update sequence element #0 has length 1; 2 is required".

I've tried all the possibilities I knew, but the error persists. 

My notebook on Google Colab: https://colab.research.google.com/drive/1NX-ah_Nuqyt6m2Wsn2WcKkadRariISFu?usp=sharing

**Comment by rafmacalaba** [comment]
same error, encountered. +1

**Comment by jiahao87** [comment]
Same error. I am able to run model training on my laptop but not Google Colab. Checked the packages versions but they are the same:
* torch==1.9.0 
* torchvision==0.10.0
* pytorch-forecasting==0.9.0
* pytorch-lightning==1.4.2

**Comment by cristianegea** [comment]
Hi @jiahao87!
Thank you very much for your help, however, the error remains... I have installed these versions of the packages you mentioned on both my notebook and Google Colab, but the same message appears...

**Comment by Antoine-Schwartz** [comment]
Same error on AWS Sagemaker notebooks, both based on persistent environments and on a new one created from scratch.

**Comment by dlopespenna** [comment]
> Same error. I am able to run model training on my laptop but not Google Colab. Checked the packages versions but they are the same:
> 
> * torch==1.9.0
> * torchvision==0.10.0
> * pytorch-forecasting==0.9.0
> * pytorch-lightning==1.4.2

Hi @jiahao87 could you tell us the python version you are using on your laptop?

**Comment by cmrodolfo** [comment]
Same problem here:

I'm trying to reproduce the tutorial [Interpretable forecasting with N-Beats](https://pytorch-forecasting.readthedocs.io/en/latest/tutorials/ar.html), which led to the same error mentioned here.
[Here](https://colab.research.google.com/drive/1JIjk0FkjXZkcz1ybdDvM5M3AW709NQj_?usp=sharing)'s the colab notebook I used for reproducing the example.

The changes I made with respect to the tutorial are:
- installing the libraries in the first two cells
- comenting the line which says `os.chdir("../../..")` from the third cell

<details><summary>traceback</summary>

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-2b28d4f8c7f1> in <module>()
     23     net,
     24     train_dataloader=train_dataloader,
---> 25     val_dataloaders=val_dataloader,
     26 )

/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py in fit(self, model, train_dataloaders, val_dataloaders, datamodule, train_dataloader)
    550         self.checkpoint_connector.resume_start()
    551 
--> 552         self._run(model)
    553 
    554         assert self.state.stopped

/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py in _run(self, model)
    909 
    910         # plugin will setup fitting (e.g. ddp will launch child processes)
--> 911         self._pre_dispatch()
    912 
    913         # restore optimizers, etc.

/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py in _pre_dispatch(self)
    938     def _pre_dispatch(self):
    939         self.accelerator.pre_dispatch(self)
--> 940         self._log_hyperparams()
    941 
    942     def _log_hyperparams(self):

/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py in _log_hyperparams(self)
    967                 self.logger.log_hyperparams(hparams_initial)
    968             self.logger.log_graph(self.lightning_module)
--> 969             self.logger.save()
    970 
    971     def _post_dispatch(self):

/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/distributed.py in wrapped_fn(*args, **kwargs)
     46     def wrapped_fn(*args, **kwargs):
     47         if rank_zero_only.rank == 0:
---> 48             return fn(*args, **kwargs)
     49 
     50     return wrapped_fn

/usr/local/lib/python3.7/dist-packages/pytorch_lightning/loggers/tensorboard.py in save(self)
    248         # save the metatags file if it doesn't exist and the log directory exists
    249         if self._fs.isdir(dir_path) and not self._fs.isfile(hparams_file):
--> 250             save_hparams_to_yaml(hparams_file, self.hparams)
    251 
    252     @rank_zero_only

/usr/local/lib/python3.7/dist-packages/pytorch_lightning/core/saving.py in save_hparams_to_yaml(config_yaml, hparams)
    403     for k, v in hparams.items():
    404         try:
--> 405             yaml.dump(v)
    406         except TypeError:
    407             warn(f"Skipping '{k}' parameter because it is not possible to safely dump to YAML.")

/usr/local/lib/python3.7/dist-packages/yaml/__init__.py in dump(data, stream, Dumper, **kwds)
    288     If stream is None, return the produced string instead.
    289     """
--> 290     return dump_all([data], stream, Dumper=Dumper, **kwds)
    291 
    292 def safe_dump_all(documents, stream=None, **kwds):

/usr/local/lib/python3.7/dist-packages/yaml/__init__.py in dump_all(documents, stream, Dumper, default_style, default_flow_style, canonical, indent, width, allow_unicode, line_break, encoding, explicit_start, explicit_end, version, tags, sort_keys)
    276         dumper.open()
    277         for data in documents:
--> 278             dumper.represent(data)
    279         dumper.close()
    280     finally:

/usr/local/lib/python3.7/dist-packages/yaml/representer.py in represent(self, data)
     25 
     26     def represent(self, data):
---> 27         node = self.represent_data(data)
     28         self.serialize(node)
     29         self.represented_objects = {}

/usr/local/lib/python3.7/dist-packages/yaml/representer.py in represent_data(self, data)
     50             for data_type in data_types:
     51                 if data_type in self.yaml_multi_representers:
---> 52                     node = self.yaml_multi_representers[data_type](self, data)
     53                     break
     54             else:

/usr/local/lib/python3.7/dist-packages/yaml/representer.py in represent_object(self, data)
    341                 and isinstance(state, dict) and newobj:
    342             return self.represent_mapping(
--> 343                     'tag:yaml.org,2002:python/object:'+function_name, state)
    344         if not listitems and not dictitems  \
    345                 and isinstance(state, dict) and not state:

/usr/local/lib/python3.7/dist-packages/yaml/representer.py in represent_mapping(self, tag, mapping, flow_style)
    116         for item_key, item_value in mapping:
    117             node_key = self.represent_data(item_key)
--> 118             node_value = self.represent_data(item_value)
    119             if not (isinstance(node_key, ScalarNode) and not node_key.style):
    120                 best_style = False

/usr/local/lib/python3.7/dist-packages/yaml/representer.py in represent_data(self, data)
     50             for data_type in data_types:
     51                 if data_type in self.yaml_multi_representers:
---> 52                     node = self.yaml_multi_representers[data_type](self, data)
     53                     break
     54             else:

/usr/local/lib/python3.7/dist-packages/yaml/representer.py in represent_object(self, data)
    328             listitems = list(listitems)
    329         if dictitems is not None:
--> 330             dictitems = dict(dictitems)
    331         if function.__name__ == '__newobj__':
    332             function = args[0]

ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

</details>

Any help with this would be appreciated. I was able to run the same code a couple weeks ago without problems.

**Comment by igorkf** [comment]
I encountered the same error when trying to reproduce example from DeepAR from [here](https://github.com/jdb78/pytorch-forecasting/blob/master/examples/ar.py).    
The error occured in line 109 (on `trainer.fit`):    
https://github.com/jdb78/pytorch-forecasting/blob/master/examples/ar.py#L109

**Comment by jiahao87** [comment]
Managed to get model training in Colab by installing the list of packages in my laptop environment. In Colab, I uploaded a requirements.txt with the following packages and did a `!pip install -r requirements.txt` and lo and behold, training worked. Not sure which package is the culprit though... Time is precious, I need to move on.
```
absl-py==0.13.0
aiohttp==3.7.4.post0
alembic==1.6.5
async-timeout==3.0.1
attrs==21.2.0
cachetools==4.2.2
certifi==2021.5.30
chardet==4.0.0
charset-normalizer==2.0.4
cliff==3.8.0
cmaes==0.8.2
cmd2==2.1.2
colorama
colorlog==5.0.1
cycler==0.10.0
debugpy 
decorator 
entrypoints 
fsspec==2021.7.0
future==0.18.2
google-auth==1.35.0
google-auth-oauthlib==0.4.5
greenlet==1.1.1
grpcio==1.39.0
idna==3.2
importlib-metadata 
ipykernel 
ipython 
ipython-genutils==0.2.0
jedi 
joblib==1.0.1
jupyter-client
jupyter-core
kiwisolver==1.3.1
Mako==1.1.4
Markdown==3.3.4
MarkupSafe==2.0.1
matplotlib==3.4.3
matplotlib-inline 
multidict==5.1.0
nest-asyncio
numpy
oauthlib==3.1.1
olefile 
optuna==2.9.1
packaging==21.0
pandas==1.3.2
parso 
patsy==0.5.1
pbr==5.6.0
pickleshare 
Pillow
prettytable==2.1.0
prompt-toolkit
protobuf==3.17.3
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyDeprecate==0.3.1
Pygments
pyparsing==2.4.7
pyperclip==1.8.2
pyreadline==2.1
python-dateutil 
python-editor==1.0.4
pytorch-forecasting==0.9.0
pytorch-lightning==1.4.2
pytz==2021.1
PyYAML==5.4.1
pyzmq 
requests==2.26.0
requests-oauthlib==1.3.0
rsa==4.7.2
scikit-learn==0.24.2
scipy==1.7.1
six 
SQLAlchemy==1.4.23
statsmodels==0.12.2
stevedore==3.4.0
tensorboard==2.6.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
threadpoolctl==2.2.0
torch==1.9.0
torchaudio==0.9.0
torchmetrics==0.5.0
torchvision==0.10.0
tornado
tqdm==4.62.1
traitlets
typing-extensions 
urllib3==1.26.6
wcwidth 
Werkzeug==2.0.1
yarl==1.6.3
zipp
```

**Comment by cristianegea** [comment]
Hi!
I received the suggestion to change the version of the `torchmetrics` package. Apparently, the version (0.5.1) being used is buggy. I made the change and apparently the notebook is running without error (it's still running)...

The `torchmetrics` package version must be <= 0.5. The version 0.51 is buggy.

**Comment by jcha7071** [comment]
After downgrading torchmetrics to 0.5.0, now I am getting "AttributeError: 'functools.partial' object has no attribute '__name__'"

**Comment by Adsanvar** [comment]
@jcha7071 
I was able to bypass this error by downgrading pandas as mentioned [here](https://stackoverflow.com/questions/68694047/pytorch-lightning-functools-partial-error).
pip install --upgrade pandas==1.3.2
My version:
pandas = 1.3.2 
pytorch = 1.9.0 
pytorch-forecasting  = 0.9.0 
pytorch-lightning = 1.4.2

**Comment by cristianegea** [comment]
Hi @jcha7071!

The versions of some packages I'm using on this notebook: 

- folium==0.2.1
- urllib3!==1.25.0
- torch==1.9.0
- torchvision==0.10.0
- pytorch-forecasting==0.9.0
- pytorch-lightning==1.4.5
- black==21.8b0
- pytest==6.2.5
- appnope==0.1.2
- pathspec==0.9.0
- ipython>=7.8.0
- tokenize-rt>=3.2.0
- typing-extensions==3.10.0.2
- colorama>=0.4.3
- aiohttp>=3.6.0
- aiohttp-cors>=0.4.0
- fsspec==2021.8.1
- torchmetrics==0.5.0

**Comment by cristianegea** [comment]
Hi @jcha7071!

I am currently working on Google Colab and this error message does not appear for me. However, when trying to run the notebook on my personal computer, the error message also appears.

Have you ever tried running your notebook on Google Colab?

**Comment by jcha7071** [comment]
Hi @Cristinegea!

Thank you so much to getting back to me!!
After searching around the postings and struggling with different combinations of trials, I could solve my problems by "downgrading" two packages:

torchmetrics - 0.5.0
pandas - 1.2.5

I created new conda env with these packages, and now everything works fine!

Thanks!!

**Comment by jcha7071** [comment]
Since I am working with our corporate data, I am avoiding working in Colab :)

**Comment by rafmacalaba** [comment]
@cristianegea whats the solution to this?

I've downgraded the packages:
torchmetrics = 0.5
pandas = 1.2.5

but still getting the same error.

```ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

**Comment by russellbrooks** [comment]
Confirmed downgrading torchmetrics `0.5.0` did the trick for me.
