### ISSUE TITLE
Issue between Temporal Fusion Transform Demo and Scikit Learn

### ISSUE THREAD

**Issue by RBarron01** [jdb78/pytorch-forecasting#705]
- PyTorch-Forecasting version: 0.9.1
- PyTorch version: 1.9.1
- Python version: 3.7.0
- Operating System: Ubuntu 20.04 (WSL)

### Expected behavior
In the "Actuals vs predictions by variables" section of the [TFT ](https://pytorch-forecasting.readthedocs.io/en/latest/tutorials/stallion.html) demo. 

### Actual behavior

Error on line "best_tft.plot_prediction_actual_by_variable(predictions_vs_actuals);"
Error: "Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample." 
Here is the traceback:
`Traceback (most recent call last):
  File "test_TFT.py", line 254, in <module>
    best_tft.plot_prediction_actual_by_variable(predictions_vs_actuals)
  File "/home/rbarron/.local/lib/python3.8/site-packages/pytorch_forecasting/models/base_model.py", line 1555, in plot_prediction_actual_by_variable
    figs = {name: self.plot_prediction_actual_by_variable(data, name) for name in data["support"].keys()}
  File "/home/rbarron/.local/lib/python3.8/site-packages/pytorch_forecasting/models/base_model.py", line 1555, in <dictcomp>
    figs = {name: self.plot_prediction_actual_by_variable(data, name) for name in data["support"].keys()}
  File "/home/rbarron/.local/lib/python3.8/site-packages/pytorch_forecasting/models/base_model.py", line 1606, in plot_prediction_actual_by_variable
    x = scaler.inverse_transform(x)
  File "/home/rbarron/.local/lib/python3.8/site-packages/sklearn/preprocessing/_data.py", line 1016, in inverse_transform
    X = check_array(
  File "/home/rbarron/.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 761, in check_array
    raise ValueError(
ValueError: Expected 2D array, got 1D array instead:
array=[-2.         -1.95744681 -1.91489362 -1.87234043 -1.82978723 -1.78723404
 -1.74468085 -1.70212766 -1.65957447 -1.61702128 -1.57446809 -1.53191489
 -1.4893617  -1.44680851 -1.40425532 -1.36170213 -1.31914894 -1.27659574
 -1.23404255 -1.19148936 -1.14893617 -1.10638298 -1.06382979 -1.0212766
 -0.9787234  -0.93617021 -0.89361702 -0.85106383 -0.80851064 -0.76595745
 -0.72340426 -0.68085106 -0.63829787 -0.59574468 -0.55319149 -0.5106383
 -0.46808511 -0.42553191 -0.38297872 -0.34042553 -0.29787234 -0.25531915
 -0.21276596 -0.17021277 -0.12765957 -0.08510638 -0.04255319  0.
  0.04255319  0.08510638  0.12765957  0.17021277  0.21276596  0.25531915
  0.29787234  0.34042553  0.38297872  0.42553191  0.46808511  0.5106383
  0.55319149  0.59574468  0.63829787  0.68085106  0.72340426  0.76595745
  0.80851064  0.85106383  0.89361702  0.93617021  0.9787234   1.0212766
  1.06382979  1.10638298  1.14893617  1.19148936  1.23404255  1.27659574
  1.31914894  1.36170213  1.40425532  1.44680851  1.4893617   1.53191489
  1.57446809  1.61702128  1.65957447  1.70212766  1.74468085  1.78723404
  1.82978723  1.87234043  1.91489362  1.95744681  2.        ].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.`

### Code to reproduce the problem
Running the [demo](https://pytorch-forecasting.readthedocs.io/en/latest/tutorials/stallion.html) as it is published.

I'm working on a solution but if anyone has suggestions to fix the demo, that would be much appreciated. 
Thanks!

**Comment by sebneale** [comment]
For a temporary fix, revert back to sklearn 0.24.2 if you've updated to version 1.0.

I was having the exact same issue, but running for a production pipeline, not the demo. You reminded me that the demo did work for me in the past (perhaps a month ago or so), thus the issue must be more recent. I remembered that I updated to sklearn 1.0 recently, and after downgrading back to 0.24.2, the problem was solved.
