### ISSUE TITLE
Creating a tensor from a list of numpy arrays now raises a warning, and is claimed to be inefficient

### ISSUE THREAD

**Issue by chefPony** [jdb78/pytorch-forecasting#754]
- PyTorch-Forecasting version: 0.9.1
- PyTorch version: 1.10.0+cu102
- Python version: 3.7

### Issue

The following warning is now raised when running the trainer:
```
/home/ec2-user/SageMaker/custom-miniconda/miniconda/envs/tremo_env/lib/python3.7/site-packages/pytorch_forecasting/data/timeseries.py:1657: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ../torch/csrc/utils/tensor_new.cpp:201.)
  target_scale = torch.tensor([batch[0]["target_scale"] for batch in batches], dtype=torch.float)
```
Suggesting that current implementation: 

https://github.com/jdb78/pytorch-forecasting/blob/b87e71befe713b55bcaf4e4b1c7161a010a7d6fc/pytorch_forecasting/data/timeseries.py#L1657

is not efficient 

### Proposed change:

Change the implementation, as suggested by the warning to increase efficiency.

**Comment by DeastinY** [comment]
https://github.com/jdb78/pytorch-forecasting/issues/714

**Comment by jdb78** [comment]
Should be fixed
