### ISSUE TITLE
Error installing from github since poetry_core latest version is 1.0.7 not 1.1.0

### ISSUE THREAD

**Issue by christy** [jdb78/pytorch-forecasting#797]
- PyTorch-Forecasting version:  0.9.2
- PyTorch version:  1.10.0
- Python version:  3.8
- Operating System:  osx M1 

### Expected behavior

I executed code `pip install git+https://github.com/jdb78/pytorch-forecasting@master`  in order to pip install from github and expected it to work.

### Actual behavior

However, result was `ERROR: No matching distribution found for poetry_core>=1.1.0`.   I think it has to do with https://github.com/jdb78/pytorch-forecasting/blob/master/pyproject.toml#L108 because https://pypi.org/project/poetry-core/ says latest version of poetry_core is 1.0.7.

I personally am confused, why is poetry version 1.1.0 and poetry-core version 1.0.7.  

### Code to reproduce the problem

```
pip install git+https://github.com/jdb78/pytorch-forecasting@master
```

If there was a crash, please include the traceback here.

Collecting git+https://github.com/jdb78/pytorch-forecasting@master
  Cloning https://github.com/jdb78/pytorch-forecasting (to revision master) to /private/var/folders/0g/jfs_l_113_356_c0rfp4jd8c0000gn/T/pip-req-build-icdqi63v
  Running command git clone --filter=blob:none -q https://github.com/jdb78/pytorch-forecasting /private/var/folders/0g/jfs_l_113_356_c0rfp4jd8c0000gn/T/pip-req-build-icdqi63v
  Resolved https://github.com/jdb78/pytorch-forecasting to commit b8583ec75909385b732eae61cbef18c84f523960
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/christy/mambaforge/envs/test/bin/python3.8 /private/var/folders/0g/jfs_l_113_356_c0rfp4jd8c0000gn/T/pip-standalone-pip-f97r1a3r/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/var/folders/0g/jfs_l_113_356_c0rfp4jd8c0000gn/T/pip-build-env-y78ykl7r/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'poetry_core>=1.1.0' 'poetry-dynamic-versioning>=0.9.0'
       cwd: None
  Complete output (2 lines):
  ERROR: Could not find a version that satisfies the requirement poetry_core>=1.1.0 (from versions: 1.0.0a0, 1.0.0a1, 1.0.0a2, 1.0.0a3, 1.0.0a4, 1.0.0a5, 1.0.0a6, 1.0.0a7, 1.0.0a8, 1.0.0a9, 1.0.0b1, 1.0.0rc1, 1.0.0rc2, 1.0.0rc3, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.1.0a1, 1.1.0a2, 1.1.0a3, 1.1.0a4, 1.1.0a5, 1.1.0a6)
  ERROR: No matching distribution found for poetry_core>=1.1.0
  ----------------------------------------
WARNING: Discarding git+https://github.com/jdb78/pytorch-forecasting@master. Command errored out with exit status 1: /Users/christy/mambaforge/envs/test/bin/python3.8 /private/var/folders/0g/jfs_l_113_356_c0rfp4jd8c0000gn/T/pip-standalone-pip-f97r1a3r/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/var/folders/0g/jfs_l_113_356_c0rfp4jd8c0000gn/T/pip-build-env-y78ykl7r/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'poetry_core>=1.1.0' 'poetry-dynamic-versioning>=0.9.0' Check the logs for full command output.
ERROR: Command errored out with exit status 1: /Users/christy/mambaforge/envs/test/bin/python3.8 /private/var/folders/0g/jfs_l_113_356_c0rfp4jd8c0000gn/T/pip-standalone-pip-f97r1a3r/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/var/folders/0g/jfs_l_113_356_c0rfp4jd8c0000gn/T/pip-build-env-y78ykl7r/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'poetry_core>=1.1.0' 'poetry-dynamic-versioning>=0.9.0' Check the logs for full command output.

**Comment by jdb78** [comment]
Could you try `pip install git+https://github.com/jdb78/pytorch-forecasting@maintenance/pip-install`?

**Comment by christy** [comment]
It works!!  Thank you so much!

**Comment by christy** [comment]
resolved
