### ISSUE TITLE
Trainer.fit might not work with 0.10.0 on GPU.

### ISSUE THREAD

**Issue by hm2200** [jdb78/pytorch-forecasting#906]
- PyTorch-Forecasting version: 0.10.0
- PyTorch-Lightning version: 1.5.10 
- Python version: 3.7.12
- Operating System: Ubuntu 18.04.5 LTS (Bionic Beaver)

### Expected behavior

At Google Colaboratory with GPU,
I executed the following code with modification for the environment.
https://pytorch-forecasting.readthedocs.io/en/latest/tutorials/stallion.html

### Actual behavior

However, result was trainer.fit does not work due to the following error:

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

I think it has to do with the latest update because the same code works on the previous version 0.9.2.

### Code to reproduce the problem

```
pip install pytorch-lightning
pip install pytorch-forecasting
# (snip)
# For pl.Trainer,
#gpus=0,
gpus=-1, auto_select_gpus=True,
```

**Comment by jdb78** [comment]
#908

**Comment by hm2200** [comment]
Thank you for the super fast fix!
