### ISSUE TITLE
AttributeError of Newly Issued Model NHiTS

### ISSUE THREAD

**Issue by Lcy2018** [jdb78/pytorch-forecasting#910]
- PyTorch-Forecasting version:0.9.0
- PyTorch version: 1.10.2
- Python version:3.6.9
- Operating System:Ubuntu 18.04 LTS

### Expected behavior

I want to test the newly issued model NHiTS on my dataset. The pre-set dataset parameters are worked in the model TemporalFusionTransformer. I also set the object parameters as told in the document.
By the way, I pasted the fold nhits in my previous package (version:0.9.0).

### Actual behavior

However, the code has the AttributeErrors which warn that some attributes of the NHiTS object cannot be found. The first error is that it can not find the attribute 'target_names'. I fixed that problem by modifying the source code. But then I found another error that it can not find the attribute 'extract_features'. 
I don't know whether it is due to my miscoding or some drawbacks in the source code.

### Code to reproduce the problem

Here is the setting of my dataset and the setting of NHiTS:

```
![1](https://user-images.githubusercontent.com/102346346/160076025-cf8a954d-8d85-4d0e-a4d7-114b916de013.jpg)
![2](https://user-images.githubusercontent.com/102346346/160076074-48ea8fee-afa9-445d-b84a-fe161accca05.jpg)

```
And the command ：
File "/home/lcy/.local/lib/python3.6/site-packages/pytorch_forecasting/models/nhits/__init__.py", line 247, in forward
    encoder_features = self.extract_features(x, self.embeddings, period="encoder")
  File "/home/lcy/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1178, in __getattr__
    type(self).__name__, name))
AttributeError: 'NHiTS' object has no attribute 'extract_features'

It will be very nice of you to answer that. Thanks a lot!

**Comment by jdb78** [comment]
the function is in the base_model.py. You need to install the newest version of pytorch-forecasting. Copy-paste will not work.
